package me.moros.bending.platform.item;

/**
 * Code autogenerated, do not edit! v1.19.2
 */
@SuppressWarnings("unused")
interface Tags {
  ItemTag WOOL_CARPETS = TagImpl.get("wool_carpets");

  ItemTag COALS = TagImpl.get("coals");

  ItemTag TALL_FLOWERS = TagImpl.get("tall_flowers");

  ItemTag STAIRS = TagImpl.get("stairs");

  ItemTag ARROWS = TagImpl.get("arrows");

  ItemTag DARK_OAK_LOGS = TagImpl.get("dark_oak_logs");

  ItemTag RAILS = TagImpl.get("rails");

  ItemTag FOX_FOOD = TagImpl.get("fox_food");

  ItemTag CRIMSON_STEMS = TagImpl.get("crimson_stems");

  ItemTag PLANKS = TagImpl.get("planks");

  ItemTag CREEPER_DROP_MUSIC_DISCS = TagImpl.get("creeper_drop_music_discs");

  ItemTag IGNORED_BY_PIGLIN_BABIES = TagImpl.get("ignored_by_piglin_babies");

  ItemTag SMALL_FLOWERS = TagImpl.get("small_flowers");

  ItemTag SAPLINGS = TagImpl.get("saplings");

  ItemTag MUSIC_DISCS = TagImpl.get("music_discs");

  ItemTag CHEST_BOATS = TagImpl.get("chest_boats");

  ItemTag WART_BLOCKS = TagImpl.get("wart_blocks");

  ItemTag SAND = TagImpl.get("sand");

  ItemTag SOUL_FIRE_BASE_BLOCKS = TagImpl.get("soul_fire_base_blocks");

  ItemTag ACACIA_LOGS = TagImpl.get("acacia_logs");

  ItemTag DIAMOND_ORES = TagImpl.get("diamond_ores");

  ItemTag FISHES = TagImpl.get("fishes");

  ItemTag WARPED_STEMS = TagImpl.get("warped_stems");

  ItemTag LOGS = TagImpl.get("logs");

  ItemTag STONE_BRICKS = TagImpl.get("stone_bricks");

  ItemTag SLABS = TagImpl.get("slabs");

  ItemTag SIGNS = TagImpl.get("signs");

  ItemTag ANVIL = TagImpl.get("anvil");

  ItemTag BANNERS = TagImpl.get("banners");

  ItemTag MANGROVE_LOGS = TagImpl.get("mangrove_logs");

  ItemTag BOATS = TagImpl.get("boats");

  ItemTag WALLS = TagImpl.get("walls");

  ItemTag BEDS = TagImpl.get("beds");

  ItemTag STONE_TOOL_MATERIALS = TagImpl.get("stone_tool_materials");

  ItemTag JUNGLE_LOGS = TagImpl.get("jungle_logs");

  ItemTag LECTERN_BOOKS = TagImpl.get("lectern_books");

  ItemTag GOLD_ORES = TagImpl.get("gold_ores");

  ItemTag BEACON_PAYMENT_ITEMS = TagImpl.get("beacon_payment_items");

  ItemTag WOODEN_TRAPDOORS = TagImpl.get("wooden_trapdoors");

  ItemTag TRAPDOORS = TagImpl.get("trapdoors");

  ItemTag LOGS_THAT_BURN = TagImpl.get("logs_that_burn");

  ItemTag FREEZE_IMMUNE_WEARABLES = TagImpl.get("freeze_immune_wearables");

  ItemTag CANDLES = TagImpl.get("candles");

  ItemTag OAK_LOGS = TagImpl.get("oak_logs");

  ItemTag EMERALD_ORES = TagImpl.get("emerald_ores");

  ItemTag COMPLETES_FIND_TREE_TUTORIAL = TagImpl.get("completes_find_tree_tutorial");

  ItemTag FLOWERS = TagImpl.get("flowers");

  ItemTag WOODEN_BUTTONS = TagImpl.get("wooden_buttons");

  ItemTag DAMPENS_VIBRATIONS = TagImpl.get("dampens_vibrations");

  ItemTag OVERWORLD_NATURAL_LOGS = TagImpl.get("overworld_natural_logs");

  ItemTag WOODEN_DOORS = TagImpl.get("wooden_doors");

  ItemTag BUTTONS = TagImpl.get("buttons");

  ItemTag PIGLIN_LOVED = TagImpl.get("piglin_loved");

  ItemTag IRON_ORES = TagImpl.get("iron_ores");

  ItemTag PIGLIN_FOOD = TagImpl.get("piglin_food");

  ItemTag DIRT = TagImpl.get("dirt");

  ItemTag STONE_CRAFTING_MATERIALS = TagImpl.get("stone_crafting_materials");

  ItemTag WOOL = TagImpl.get("wool");

  ItemTag WOODEN_FENCES = TagImpl.get("wooden_fences");

  ItemTag WOODEN_PRESSURE_PLATES = TagImpl.get("wooden_pressure_plates");

  ItemTag PIGLIN_REPELLENTS = TagImpl.get("piglin_repellents");

  ItemTag COMPASSES = TagImpl.get("compasses");

  ItemTag AXOLOTL_TEMPT_ITEMS = TagImpl.get("axolotl_tempt_items");

  ItemTag WOODEN_STAIRS = TagImpl.get("wooden_stairs");

  ItemTag LEAVES = TagImpl.get("leaves");

  ItemTag DOORS = TagImpl.get("doors");

  ItemTag WOODEN_SLABS = TagImpl.get("wooden_slabs");

  ItemTag CLUSTER_MAX_HARVESTABLES = TagImpl.get("cluster_max_harvestables");

  ItemTag FENCES = TagImpl.get("fences");

  ItemTag REDSTONE_ORES = TagImpl.get("redstone_ores");

  ItemTag NON_FLAMMABLE_WOOD = TagImpl.get("non_flammable_wood");

  ItemTag LAPIS_ORES = TagImpl.get("lapis_ores");

  ItemTag TERRACOTTA = TagImpl.get("terracotta");

  ItemTag COAL_ORES = TagImpl.get("coal_ores");

  ItemTag BIRCH_LOGS = TagImpl.get("birch_logs");

  ItemTag COPPER_ORES = TagImpl.get("copper_ores");

  ItemTag SPRUCE_LOGS = TagImpl.get("spruce_logs");
}
