plugins {
    application
}

application {
    mainClass.set("me.moros.codegen.Generators")
}

repositories {
    mavenLocal()
}

dependencies {
    implementation(libs.gson)
    implementation(libs.javapoet)
    implementation(libs.articdata)
}

tasks {
    getByName<JavaExec>("run") {
        args = listOf(rootProject.projectDir.resolve("bending-api/src/autogenerated/java").absolutePath)
    }
}
