plugins {
    application
    id("bending.base-conventions")
}

application {
    mainClass = "me.moros.codegen.Generators"
}

repositories {
    maven("https://repo.moros.me/snapshots/")
}

dependencies {
    implementation(libs.gson)
    implementation(libs.javapoet)
    implementation(libs.articdata)
}

tasks {
    getByName<JavaExec>("run") {
        args = listOf(rootProject.projectDir.resolve("api/src/autogenerated/java").absolutePath)
    }
}
