package me.moros.bending.api.platform.block;

/**
 * Code autogenerated, do not edit! v1.21.6
 */
@SuppressWarnings("unused")
interface BlockTypes {
  BlockType ACACIA_BUTTON = BlockTypeImpl.get("acacia_button");

  BlockType ACACIA_DOOR = BlockTypeImpl.get("acacia_door");

  BlockType ACACIA_FENCE = BlockTypeImpl.get("acacia_fence");

  BlockType ACACIA_FENCE_GATE = BlockTypeImpl.get("acacia_fence_gate");

  BlockType ACACIA_HANGING_SIGN = BlockTypeImpl.get("acacia_hanging_sign");

  BlockType ACACIA_LEAVES = BlockTypeImpl.get("acacia_leaves");

  BlockType ACACIA_LOG = BlockTypeImpl.get("acacia_log");

  BlockType ACACIA_PLANKS = BlockTypeImpl.get("acacia_planks");

  BlockType ACACIA_PRESSURE_PLATE = BlockTypeImpl.get("acacia_pressure_plate");

  BlockType ACACIA_SAPLING = BlockTypeImpl.get("acacia_sapling");

  BlockType ACACIA_SIGN = BlockTypeImpl.get("acacia_sign");

  BlockType ACACIA_SLAB = BlockTypeImpl.get("acacia_slab");

  BlockType ACACIA_STAIRS = BlockTypeImpl.get("acacia_stairs");

  BlockType ACACIA_TRAPDOOR = BlockTypeImpl.get("acacia_trapdoor");

  BlockType ACACIA_WALL_HANGING_SIGN = BlockTypeImpl.get("acacia_wall_hanging_sign");

  BlockType ACACIA_WALL_SIGN = BlockTypeImpl.get("acacia_wall_sign");

  BlockType ACACIA_WOOD = BlockTypeImpl.get("acacia_wood");

  BlockType ACTIVATOR_RAIL = BlockTypeImpl.get("activator_rail");

  BlockType AIR = BlockTypeImpl.get("air");

  BlockType ALLIUM = BlockTypeImpl.get("allium");

  BlockType AMETHYST_BLOCK = BlockTypeImpl.get("amethyst_block");

  BlockType AMETHYST_CLUSTER = BlockTypeImpl.get("amethyst_cluster");

  BlockType ANCIENT_DEBRIS = BlockTypeImpl.get("ancient_debris");

  BlockType ANDESITE = BlockTypeImpl.get("andesite");

  BlockType ANDESITE_SLAB = BlockTypeImpl.get("andesite_slab");

  BlockType ANDESITE_STAIRS = BlockTypeImpl.get("andesite_stairs");

  BlockType ANDESITE_WALL = BlockTypeImpl.get("andesite_wall");

  BlockType ANVIL = BlockTypeImpl.get("anvil");

  BlockType ATTACHED_MELON_STEM = BlockTypeImpl.get("attached_melon_stem");

  BlockType ATTACHED_PUMPKIN_STEM = BlockTypeImpl.get("attached_pumpkin_stem");

  BlockType AZALEA = BlockTypeImpl.get("azalea");

  BlockType AZALEA_LEAVES = BlockTypeImpl.get("azalea_leaves");

  BlockType AZURE_BLUET = BlockTypeImpl.get("azure_bluet");

  BlockType BAMBOO = BlockTypeImpl.get("bamboo");

  BlockType BAMBOO_BLOCK = BlockTypeImpl.get("bamboo_block");

  BlockType BAMBOO_BUTTON = BlockTypeImpl.get("bamboo_button");

  BlockType BAMBOO_DOOR = BlockTypeImpl.get("bamboo_door");

  BlockType BAMBOO_FENCE = BlockTypeImpl.get("bamboo_fence");

  BlockType BAMBOO_FENCE_GATE = BlockTypeImpl.get("bamboo_fence_gate");

  BlockType BAMBOO_HANGING_SIGN = BlockTypeImpl.get("bamboo_hanging_sign");

  BlockType BAMBOO_MOSAIC = BlockTypeImpl.get("bamboo_mosaic");

  BlockType BAMBOO_MOSAIC_SLAB = BlockTypeImpl.get("bamboo_mosaic_slab");

  BlockType BAMBOO_MOSAIC_STAIRS = BlockTypeImpl.get("bamboo_mosaic_stairs");

  BlockType BAMBOO_PLANKS = BlockTypeImpl.get("bamboo_planks");

  BlockType BAMBOO_PRESSURE_PLATE = BlockTypeImpl.get("bamboo_pressure_plate");

  BlockType BAMBOO_SAPLING = BlockTypeImpl.get("bamboo_sapling");

  BlockType BAMBOO_SIGN = BlockTypeImpl.get("bamboo_sign");

  BlockType BAMBOO_SLAB = BlockTypeImpl.get("bamboo_slab");

  BlockType BAMBOO_STAIRS = BlockTypeImpl.get("bamboo_stairs");

  BlockType BAMBOO_TRAPDOOR = BlockTypeImpl.get("bamboo_trapdoor");

  BlockType BAMBOO_WALL_HANGING_SIGN = BlockTypeImpl.get("bamboo_wall_hanging_sign");

  BlockType BAMBOO_WALL_SIGN = BlockTypeImpl.get("bamboo_wall_sign");

  BlockType BARREL = BlockTypeImpl.get("barrel");

  BlockType BARRIER = BlockTypeImpl.get("barrier");

  BlockType BASALT = BlockTypeImpl.get("basalt");

  BlockType BEACON = BlockTypeImpl.get("beacon");

  BlockType BEDROCK = BlockTypeImpl.get("bedrock");

  BlockType BEE_NEST = BlockTypeImpl.get("bee_nest");

  BlockType BEEHIVE = BlockTypeImpl.get("beehive");

  BlockType BEETROOTS = BlockTypeImpl.get("beetroots");

  BlockType BELL = BlockTypeImpl.get("bell");

  BlockType BIG_DRIPLEAF = BlockTypeImpl.get("big_dripleaf");

  BlockType BIG_DRIPLEAF_STEM = BlockTypeImpl.get("big_dripleaf_stem");

  BlockType BIRCH_BUTTON = BlockTypeImpl.get("birch_button");

  BlockType BIRCH_DOOR = BlockTypeImpl.get("birch_door");

  BlockType BIRCH_FENCE = BlockTypeImpl.get("birch_fence");

  BlockType BIRCH_FENCE_GATE = BlockTypeImpl.get("birch_fence_gate");

  BlockType BIRCH_HANGING_SIGN = BlockTypeImpl.get("birch_hanging_sign");

  BlockType BIRCH_LEAVES = BlockTypeImpl.get("birch_leaves");

  BlockType BIRCH_LOG = BlockTypeImpl.get("birch_log");

  BlockType BIRCH_PLANKS = BlockTypeImpl.get("birch_planks");

  BlockType BIRCH_PRESSURE_PLATE = BlockTypeImpl.get("birch_pressure_plate");

  BlockType BIRCH_SAPLING = BlockTypeImpl.get("birch_sapling");

  BlockType BIRCH_SIGN = BlockTypeImpl.get("birch_sign");

  BlockType BIRCH_SLAB = BlockTypeImpl.get("birch_slab");

  BlockType BIRCH_STAIRS = BlockTypeImpl.get("birch_stairs");

  BlockType BIRCH_TRAPDOOR = BlockTypeImpl.get("birch_trapdoor");

  BlockType BIRCH_WALL_HANGING_SIGN = BlockTypeImpl.get("birch_wall_hanging_sign");

  BlockType BIRCH_WALL_SIGN = BlockTypeImpl.get("birch_wall_sign");

  BlockType BIRCH_WOOD = BlockTypeImpl.get("birch_wood");

  BlockType BLACK_BANNER = BlockTypeImpl.get("black_banner");

  BlockType BLACK_BED = BlockTypeImpl.get("black_bed");

  BlockType BLACK_CANDLE = BlockTypeImpl.get("black_candle");

  BlockType BLACK_CANDLE_CAKE = BlockTypeImpl.get("black_candle_cake");

  BlockType BLACK_CARPET = BlockTypeImpl.get("black_carpet");

  BlockType BLACK_CONCRETE = BlockTypeImpl.get("black_concrete");

  BlockType BLACK_CONCRETE_POWDER = BlockTypeImpl.get("black_concrete_powder");

  BlockType BLACK_GLAZED_TERRACOTTA = BlockTypeImpl.get("black_glazed_terracotta");

  BlockType BLACK_SHULKER_BOX = BlockTypeImpl.get("black_shulker_box");

  BlockType BLACK_STAINED_GLASS = BlockTypeImpl.get("black_stained_glass");

  BlockType BLACK_STAINED_GLASS_PANE = BlockTypeImpl.get("black_stained_glass_pane");

  BlockType BLACK_TERRACOTTA = BlockTypeImpl.get("black_terracotta");

  BlockType BLACK_WALL_BANNER = BlockTypeImpl.get("black_wall_banner");

  BlockType BLACK_WOOL = BlockTypeImpl.get("black_wool");

  BlockType BLACKSTONE = BlockTypeImpl.get("blackstone");

  BlockType BLACKSTONE_SLAB = BlockTypeImpl.get("blackstone_slab");

  BlockType BLACKSTONE_STAIRS = BlockTypeImpl.get("blackstone_stairs");

  BlockType BLACKSTONE_WALL = BlockTypeImpl.get("blackstone_wall");

  BlockType BLAST_FURNACE = BlockTypeImpl.get("blast_furnace");

  BlockType BLUE_BANNER = BlockTypeImpl.get("blue_banner");

  BlockType BLUE_BED = BlockTypeImpl.get("blue_bed");

  BlockType BLUE_CANDLE = BlockTypeImpl.get("blue_candle");

  BlockType BLUE_CANDLE_CAKE = BlockTypeImpl.get("blue_candle_cake");

  BlockType BLUE_CARPET = BlockTypeImpl.get("blue_carpet");

  BlockType BLUE_CONCRETE = BlockTypeImpl.get("blue_concrete");

  BlockType BLUE_CONCRETE_POWDER = BlockTypeImpl.get("blue_concrete_powder");

  BlockType BLUE_GLAZED_TERRACOTTA = BlockTypeImpl.get("blue_glazed_terracotta");

  BlockType BLUE_ICE = BlockTypeImpl.get("blue_ice");

  BlockType BLUE_ORCHID = BlockTypeImpl.get("blue_orchid");

  BlockType BLUE_SHULKER_BOX = BlockTypeImpl.get("blue_shulker_box");

  BlockType BLUE_STAINED_GLASS = BlockTypeImpl.get("blue_stained_glass");

  BlockType BLUE_STAINED_GLASS_PANE = BlockTypeImpl.get("blue_stained_glass_pane");

  BlockType BLUE_TERRACOTTA = BlockTypeImpl.get("blue_terracotta");

  BlockType BLUE_WALL_BANNER = BlockTypeImpl.get("blue_wall_banner");

  BlockType BLUE_WOOL = BlockTypeImpl.get("blue_wool");

  BlockType BONE_BLOCK = BlockTypeImpl.get("bone_block");

  BlockType BOOKSHELF = BlockTypeImpl.get("bookshelf");

  BlockType BRAIN_CORAL = BlockTypeImpl.get("brain_coral");

  BlockType BRAIN_CORAL_BLOCK = BlockTypeImpl.get("brain_coral_block");

  BlockType BRAIN_CORAL_FAN = BlockTypeImpl.get("brain_coral_fan");

  BlockType BRAIN_CORAL_WALL_FAN = BlockTypeImpl.get("brain_coral_wall_fan");

  BlockType BREWING_STAND = BlockTypeImpl.get("brewing_stand");

  BlockType BRICK_SLAB = BlockTypeImpl.get("brick_slab");

  BlockType BRICK_STAIRS = BlockTypeImpl.get("brick_stairs");

  BlockType BRICK_WALL = BlockTypeImpl.get("brick_wall");

  BlockType BRICKS = BlockTypeImpl.get("bricks");

  BlockType BROWN_BANNER = BlockTypeImpl.get("brown_banner");

  BlockType BROWN_BED = BlockTypeImpl.get("brown_bed");

  BlockType BROWN_CANDLE = BlockTypeImpl.get("brown_candle");

  BlockType BROWN_CANDLE_CAKE = BlockTypeImpl.get("brown_candle_cake");

  BlockType BROWN_CARPET = BlockTypeImpl.get("brown_carpet");

  BlockType BROWN_CONCRETE = BlockTypeImpl.get("brown_concrete");

  BlockType BROWN_CONCRETE_POWDER = BlockTypeImpl.get("brown_concrete_powder");

  BlockType BROWN_GLAZED_TERRACOTTA = BlockTypeImpl.get("brown_glazed_terracotta");

  BlockType BROWN_MUSHROOM = BlockTypeImpl.get("brown_mushroom");

  BlockType BROWN_MUSHROOM_BLOCK = BlockTypeImpl.get("brown_mushroom_block");

  BlockType BROWN_SHULKER_BOX = BlockTypeImpl.get("brown_shulker_box");

  BlockType BROWN_STAINED_GLASS = BlockTypeImpl.get("brown_stained_glass");

  BlockType BROWN_STAINED_GLASS_PANE = BlockTypeImpl.get("brown_stained_glass_pane");

  BlockType BROWN_TERRACOTTA = BlockTypeImpl.get("brown_terracotta");

  BlockType BROWN_WALL_BANNER = BlockTypeImpl.get("brown_wall_banner");

  BlockType BROWN_WOOL = BlockTypeImpl.get("brown_wool");

  BlockType BUBBLE_COLUMN = BlockTypeImpl.get("bubble_column");

  BlockType BUBBLE_CORAL = BlockTypeImpl.get("bubble_coral");

  BlockType BUBBLE_CORAL_BLOCK = BlockTypeImpl.get("bubble_coral_block");

  BlockType BUBBLE_CORAL_FAN = BlockTypeImpl.get("bubble_coral_fan");

  BlockType BUBBLE_CORAL_WALL_FAN = BlockTypeImpl.get("bubble_coral_wall_fan");

  BlockType BUDDING_AMETHYST = BlockTypeImpl.get("budding_amethyst");

  BlockType BUSH = BlockTypeImpl.get("bush");

  BlockType CACTUS = BlockTypeImpl.get("cactus");

  BlockType CACTUS_FLOWER = BlockTypeImpl.get("cactus_flower");

  BlockType CAKE = BlockTypeImpl.get("cake");

  BlockType CALCITE = BlockTypeImpl.get("calcite");

  BlockType CALIBRATED_SCULK_SENSOR = BlockTypeImpl.get("calibrated_sculk_sensor");

  BlockType CAMPFIRE = BlockTypeImpl.get("campfire");

  BlockType CANDLE = BlockTypeImpl.get("candle");

  BlockType CANDLE_CAKE = BlockTypeImpl.get("candle_cake");

  BlockType CARROTS = BlockTypeImpl.get("carrots");

  BlockType CARTOGRAPHY_TABLE = BlockTypeImpl.get("cartography_table");

  BlockType CARVED_PUMPKIN = BlockTypeImpl.get("carved_pumpkin");

  BlockType CAULDRON = BlockTypeImpl.get("cauldron");

  BlockType CAVE_AIR = BlockTypeImpl.get("cave_air");

  BlockType CAVE_VINES = BlockTypeImpl.get("cave_vines");

  BlockType CAVE_VINES_PLANT = BlockTypeImpl.get("cave_vines_plant");

  BlockType CHAIN = BlockTypeImpl.get("chain");

  BlockType CHAIN_COMMAND_BLOCK = BlockTypeImpl.get("chain_command_block");

  BlockType CHERRY_BUTTON = BlockTypeImpl.get("cherry_button");

  BlockType CHERRY_DOOR = BlockTypeImpl.get("cherry_door");

  BlockType CHERRY_FENCE = BlockTypeImpl.get("cherry_fence");

  BlockType CHERRY_FENCE_GATE = BlockTypeImpl.get("cherry_fence_gate");

  BlockType CHERRY_HANGING_SIGN = BlockTypeImpl.get("cherry_hanging_sign");

  BlockType CHERRY_LEAVES = BlockTypeImpl.get("cherry_leaves");

  BlockType CHERRY_LOG = BlockTypeImpl.get("cherry_log");

  BlockType CHERRY_PLANKS = BlockTypeImpl.get("cherry_planks");

  BlockType CHERRY_PRESSURE_PLATE = BlockTypeImpl.get("cherry_pressure_plate");

  BlockType CHERRY_SAPLING = BlockTypeImpl.get("cherry_sapling");

  BlockType CHERRY_SIGN = BlockTypeImpl.get("cherry_sign");

  BlockType CHERRY_SLAB = BlockTypeImpl.get("cherry_slab");

  BlockType CHERRY_STAIRS = BlockTypeImpl.get("cherry_stairs");

  BlockType CHERRY_TRAPDOOR = BlockTypeImpl.get("cherry_trapdoor");

  BlockType CHERRY_WALL_HANGING_SIGN = BlockTypeImpl.get("cherry_wall_hanging_sign");

  BlockType CHERRY_WALL_SIGN = BlockTypeImpl.get("cherry_wall_sign");

  BlockType CHERRY_WOOD = BlockTypeImpl.get("cherry_wood");

  BlockType CHEST = BlockTypeImpl.get("chest");

  BlockType CHIPPED_ANVIL = BlockTypeImpl.get("chipped_anvil");

  BlockType CHISELED_BOOKSHELF = BlockTypeImpl.get("chiseled_bookshelf");

  BlockType CHISELED_COPPER = BlockTypeImpl.get("chiseled_copper");

  BlockType CHISELED_DEEPSLATE = BlockTypeImpl.get("chiseled_deepslate");

  BlockType CHISELED_NETHER_BRICKS = BlockTypeImpl.get("chiseled_nether_bricks");

  BlockType CHISELED_POLISHED_BLACKSTONE = BlockTypeImpl.get("chiseled_polished_blackstone");

  BlockType CHISELED_QUARTZ_BLOCK = BlockTypeImpl.get("chiseled_quartz_block");

  BlockType CHISELED_RED_SANDSTONE = BlockTypeImpl.get("chiseled_red_sandstone");

  BlockType CHISELED_RESIN_BRICKS = BlockTypeImpl.get("chiseled_resin_bricks");

  BlockType CHISELED_SANDSTONE = BlockTypeImpl.get("chiseled_sandstone");

  BlockType CHISELED_STONE_BRICKS = BlockTypeImpl.get("chiseled_stone_bricks");

  BlockType CHISELED_TUFF = BlockTypeImpl.get("chiseled_tuff");

  BlockType CHISELED_TUFF_BRICKS = BlockTypeImpl.get("chiseled_tuff_bricks");

  BlockType CHORUS_FLOWER = BlockTypeImpl.get("chorus_flower");

  BlockType CHORUS_PLANT = BlockTypeImpl.get("chorus_plant");

  BlockType CLAY = BlockTypeImpl.get("clay");

  BlockType CLOSED_EYEBLOSSOM = BlockTypeImpl.get("closed_eyeblossom");

  BlockType COAL_BLOCK = BlockTypeImpl.get("coal_block");

  BlockType COAL_ORE = BlockTypeImpl.get("coal_ore");

  BlockType COARSE_DIRT = BlockTypeImpl.get("coarse_dirt");

  BlockType COBBLED_DEEPSLATE = BlockTypeImpl.get("cobbled_deepslate");

  BlockType COBBLED_DEEPSLATE_SLAB = BlockTypeImpl.get("cobbled_deepslate_slab");

  BlockType COBBLED_DEEPSLATE_STAIRS = BlockTypeImpl.get("cobbled_deepslate_stairs");

  BlockType COBBLED_DEEPSLATE_WALL = BlockTypeImpl.get("cobbled_deepslate_wall");

  BlockType COBBLESTONE = BlockTypeImpl.get("cobblestone");

  BlockType COBBLESTONE_SLAB = BlockTypeImpl.get("cobblestone_slab");

  BlockType COBBLESTONE_STAIRS = BlockTypeImpl.get("cobblestone_stairs");

  BlockType COBBLESTONE_WALL = BlockTypeImpl.get("cobblestone_wall");

  BlockType COBWEB = BlockTypeImpl.get("cobweb");

  BlockType COCOA = BlockTypeImpl.get("cocoa");

  BlockType COMMAND_BLOCK = BlockTypeImpl.get("command_block");

  BlockType COMPARATOR = BlockTypeImpl.get("comparator");

  BlockType COMPOSTER = BlockTypeImpl.get("composter");

  BlockType CONDUIT = BlockTypeImpl.get("conduit");

  BlockType COPPER_BLOCK = BlockTypeImpl.get("copper_block");

  BlockType COPPER_BULB = BlockTypeImpl.get("copper_bulb");

  BlockType COPPER_DOOR = BlockTypeImpl.get("copper_door");

  BlockType COPPER_GRATE = BlockTypeImpl.get("copper_grate");

  BlockType COPPER_ORE = BlockTypeImpl.get("copper_ore");

  BlockType COPPER_TRAPDOOR = BlockTypeImpl.get("copper_trapdoor");

  BlockType CORNFLOWER = BlockTypeImpl.get("cornflower");

  BlockType CRACKED_DEEPSLATE_BRICKS = BlockTypeImpl.get("cracked_deepslate_bricks");

  BlockType CRACKED_DEEPSLATE_TILES = BlockTypeImpl.get("cracked_deepslate_tiles");

  BlockType CRACKED_NETHER_BRICKS = BlockTypeImpl.get("cracked_nether_bricks");

  BlockType CRACKED_POLISHED_BLACKSTONE_BRICKS = BlockTypeImpl.get("cracked_polished_blackstone_bricks");

  BlockType CRACKED_STONE_BRICKS = BlockTypeImpl.get("cracked_stone_bricks");

  BlockType CRAFTER = BlockTypeImpl.get("crafter");

  BlockType CRAFTING_TABLE = BlockTypeImpl.get("crafting_table");

  BlockType CREAKING_HEART = BlockTypeImpl.get("creaking_heart");

  BlockType CREEPER_HEAD = BlockTypeImpl.get("creeper_head");

  BlockType CREEPER_WALL_HEAD = BlockTypeImpl.get("creeper_wall_head");

  BlockType CRIMSON_BUTTON = BlockTypeImpl.get("crimson_button");

  BlockType CRIMSON_DOOR = BlockTypeImpl.get("crimson_door");

  BlockType CRIMSON_FENCE = BlockTypeImpl.get("crimson_fence");

  BlockType CRIMSON_FENCE_GATE = BlockTypeImpl.get("crimson_fence_gate");

  BlockType CRIMSON_FUNGUS = BlockTypeImpl.get("crimson_fungus");

  BlockType CRIMSON_HANGING_SIGN = BlockTypeImpl.get("crimson_hanging_sign");

  BlockType CRIMSON_HYPHAE = BlockTypeImpl.get("crimson_hyphae");

  BlockType CRIMSON_NYLIUM = BlockTypeImpl.get("crimson_nylium");

  BlockType CRIMSON_PLANKS = BlockTypeImpl.get("crimson_planks");

  BlockType CRIMSON_PRESSURE_PLATE = BlockTypeImpl.get("crimson_pressure_plate");

  BlockType CRIMSON_ROOTS = BlockTypeImpl.get("crimson_roots");

  BlockType CRIMSON_SIGN = BlockTypeImpl.get("crimson_sign");

  BlockType CRIMSON_SLAB = BlockTypeImpl.get("crimson_slab");

  BlockType CRIMSON_STAIRS = BlockTypeImpl.get("crimson_stairs");

  BlockType CRIMSON_STEM = BlockTypeImpl.get("crimson_stem");

  BlockType CRIMSON_TRAPDOOR = BlockTypeImpl.get("crimson_trapdoor");

  BlockType CRIMSON_WALL_HANGING_SIGN = BlockTypeImpl.get("crimson_wall_hanging_sign");

  BlockType CRIMSON_WALL_SIGN = BlockTypeImpl.get("crimson_wall_sign");

  BlockType CRYING_OBSIDIAN = BlockTypeImpl.get("crying_obsidian");

  BlockType CUT_COPPER = BlockTypeImpl.get("cut_copper");

  BlockType CUT_COPPER_SLAB = BlockTypeImpl.get("cut_copper_slab");

  BlockType CUT_COPPER_STAIRS = BlockTypeImpl.get("cut_copper_stairs");

  BlockType CUT_RED_SANDSTONE = BlockTypeImpl.get("cut_red_sandstone");

  BlockType CUT_RED_SANDSTONE_SLAB = BlockTypeImpl.get("cut_red_sandstone_slab");

  BlockType CUT_SANDSTONE = BlockTypeImpl.get("cut_sandstone");

  BlockType CUT_SANDSTONE_SLAB = BlockTypeImpl.get("cut_sandstone_slab");

  BlockType CYAN_BANNER = BlockTypeImpl.get("cyan_banner");

  BlockType CYAN_BED = BlockTypeImpl.get("cyan_bed");

  BlockType CYAN_CANDLE = BlockTypeImpl.get("cyan_candle");

  BlockType CYAN_CANDLE_CAKE = BlockTypeImpl.get("cyan_candle_cake");

  BlockType CYAN_CARPET = BlockTypeImpl.get("cyan_carpet");

  BlockType CYAN_CONCRETE = BlockTypeImpl.get("cyan_concrete");

  BlockType CYAN_CONCRETE_POWDER = BlockTypeImpl.get("cyan_concrete_powder");

  BlockType CYAN_GLAZED_TERRACOTTA = BlockTypeImpl.get("cyan_glazed_terracotta");

  BlockType CYAN_SHULKER_BOX = BlockTypeImpl.get("cyan_shulker_box");

  BlockType CYAN_STAINED_GLASS = BlockTypeImpl.get("cyan_stained_glass");

  BlockType CYAN_STAINED_GLASS_PANE = BlockTypeImpl.get("cyan_stained_glass_pane");

  BlockType CYAN_TERRACOTTA = BlockTypeImpl.get("cyan_terracotta");

  BlockType CYAN_WALL_BANNER = BlockTypeImpl.get("cyan_wall_banner");

  BlockType CYAN_WOOL = BlockTypeImpl.get("cyan_wool");

  BlockType DAMAGED_ANVIL = BlockTypeImpl.get("damaged_anvil");

  BlockType DANDELION = BlockTypeImpl.get("dandelion");

  BlockType DARK_OAK_BUTTON = BlockTypeImpl.get("dark_oak_button");

  BlockType DARK_OAK_DOOR = BlockTypeImpl.get("dark_oak_door");

  BlockType DARK_OAK_FENCE = BlockTypeImpl.get("dark_oak_fence");

  BlockType DARK_OAK_FENCE_GATE = BlockTypeImpl.get("dark_oak_fence_gate");

  BlockType DARK_OAK_HANGING_SIGN = BlockTypeImpl.get("dark_oak_hanging_sign");

  BlockType DARK_OAK_LEAVES = BlockTypeImpl.get("dark_oak_leaves");

  BlockType DARK_OAK_LOG = BlockTypeImpl.get("dark_oak_log");

  BlockType DARK_OAK_PLANKS = BlockTypeImpl.get("dark_oak_planks");

  BlockType DARK_OAK_PRESSURE_PLATE = BlockTypeImpl.get("dark_oak_pressure_plate");

  BlockType DARK_OAK_SAPLING = BlockTypeImpl.get("dark_oak_sapling");

  BlockType DARK_OAK_SIGN = BlockTypeImpl.get("dark_oak_sign");

  BlockType DARK_OAK_SLAB = BlockTypeImpl.get("dark_oak_slab");

  BlockType DARK_OAK_STAIRS = BlockTypeImpl.get("dark_oak_stairs");

  BlockType DARK_OAK_TRAPDOOR = BlockTypeImpl.get("dark_oak_trapdoor");

  BlockType DARK_OAK_WALL_HANGING_SIGN = BlockTypeImpl.get("dark_oak_wall_hanging_sign");

  BlockType DARK_OAK_WALL_SIGN = BlockTypeImpl.get("dark_oak_wall_sign");

  BlockType DARK_OAK_WOOD = BlockTypeImpl.get("dark_oak_wood");

  BlockType DARK_PRISMARINE = BlockTypeImpl.get("dark_prismarine");

  BlockType DARK_PRISMARINE_SLAB = BlockTypeImpl.get("dark_prismarine_slab");

  BlockType DARK_PRISMARINE_STAIRS = BlockTypeImpl.get("dark_prismarine_stairs");

  BlockType DAYLIGHT_DETECTOR = BlockTypeImpl.get("daylight_detector");

  BlockType DEAD_BRAIN_CORAL = BlockTypeImpl.get("dead_brain_coral");

  BlockType DEAD_BRAIN_CORAL_BLOCK = BlockTypeImpl.get("dead_brain_coral_block");

  BlockType DEAD_BRAIN_CORAL_FAN = BlockTypeImpl.get("dead_brain_coral_fan");

  BlockType DEAD_BRAIN_CORAL_WALL_FAN = BlockTypeImpl.get("dead_brain_coral_wall_fan");

  BlockType DEAD_BUBBLE_CORAL = BlockTypeImpl.get("dead_bubble_coral");

  BlockType DEAD_BUBBLE_CORAL_BLOCK = BlockTypeImpl.get("dead_bubble_coral_block");

  BlockType DEAD_BUBBLE_CORAL_FAN = BlockTypeImpl.get("dead_bubble_coral_fan");

  BlockType DEAD_BUBBLE_CORAL_WALL_FAN = BlockTypeImpl.get("dead_bubble_coral_wall_fan");

  BlockType DEAD_BUSH = BlockTypeImpl.get("dead_bush");

  BlockType DEAD_FIRE_CORAL = BlockTypeImpl.get("dead_fire_coral");

  BlockType DEAD_FIRE_CORAL_BLOCK = BlockTypeImpl.get("dead_fire_coral_block");

  BlockType DEAD_FIRE_CORAL_FAN = BlockTypeImpl.get("dead_fire_coral_fan");

  BlockType DEAD_FIRE_CORAL_WALL_FAN = BlockTypeImpl.get("dead_fire_coral_wall_fan");

  BlockType DEAD_HORN_CORAL = BlockTypeImpl.get("dead_horn_coral");

  BlockType DEAD_HORN_CORAL_BLOCK = BlockTypeImpl.get("dead_horn_coral_block");

  BlockType DEAD_HORN_CORAL_FAN = BlockTypeImpl.get("dead_horn_coral_fan");

  BlockType DEAD_HORN_CORAL_WALL_FAN = BlockTypeImpl.get("dead_horn_coral_wall_fan");

  BlockType DEAD_TUBE_CORAL = BlockTypeImpl.get("dead_tube_coral");

  BlockType DEAD_TUBE_CORAL_BLOCK = BlockTypeImpl.get("dead_tube_coral_block");

  BlockType DEAD_TUBE_CORAL_FAN = BlockTypeImpl.get("dead_tube_coral_fan");

  BlockType DEAD_TUBE_CORAL_WALL_FAN = BlockTypeImpl.get("dead_tube_coral_wall_fan");

  BlockType DECORATED_POT = BlockTypeImpl.get("decorated_pot");

  BlockType DEEPSLATE = BlockTypeImpl.get("deepslate");

  BlockType DEEPSLATE_BRICK_SLAB = BlockTypeImpl.get("deepslate_brick_slab");

  BlockType DEEPSLATE_BRICK_STAIRS = BlockTypeImpl.get("deepslate_brick_stairs");

  BlockType DEEPSLATE_BRICK_WALL = BlockTypeImpl.get("deepslate_brick_wall");

  BlockType DEEPSLATE_BRICKS = BlockTypeImpl.get("deepslate_bricks");

  BlockType DEEPSLATE_COAL_ORE = BlockTypeImpl.get("deepslate_coal_ore");

  BlockType DEEPSLATE_COPPER_ORE = BlockTypeImpl.get("deepslate_copper_ore");

  BlockType DEEPSLATE_DIAMOND_ORE = BlockTypeImpl.get("deepslate_diamond_ore");

  BlockType DEEPSLATE_EMERALD_ORE = BlockTypeImpl.get("deepslate_emerald_ore");

  BlockType DEEPSLATE_GOLD_ORE = BlockTypeImpl.get("deepslate_gold_ore");

  BlockType DEEPSLATE_IRON_ORE = BlockTypeImpl.get("deepslate_iron_ore");

  BlockType DEEPSLATE_LAPIS_ORE = BlockTypeImpl.get("deepslate_lapis_ore");

  BlockType DEEPSLATE_REDSTONE_ORE = BlockTypeImpl.get("deepslate_redstone_ore");

  BlockType DEEPSLATE_TILE_SLAB = BlockTypeImpl.get("deepslate_tile_slab");

  BlockType DEEPSLATE_TILE_STAIRS = BlockTypeImpl.get("deepslate_tile_stairs");

  BlockType DEEPSLATE_TILE_WALL = BlockTypeImpl.get("deepslate_tile_wall");

  BlockType DEEPSLATE_TILES = BlockTypeImpl.get("deepslate_tiles");

  BlockType DETECTOR_RAIL = BlockTypeImpl.get("detector_rail");

  BlockType DIAMOND_BLOCK = BlockTypeImpl.get("diamond_block");

  BlockType DIAMOND_ORE = BlockTypeImpl.get("diamond_ore");

  BlockType DIORITE = BlockTypeImpl.get("diorite");

  BlockType DIORITE_SLAB = BlockTypeImpl.get("diorite_slab");

  BlockType DIORITE_STAIRS = BlockTypeImpl.get("diorite_stairs");

  BlockType DIORITE_WALL = BlockTypeImpl.get("diorite_wall");

  BlockType DIRT = BlockTypeImpl.get("dirt");

  BlockType DIRT_PATH = BlockTypeImpl.get("dirt_path");

  BlockType DISPENSER = BlockTypeImpl.get("dispenser");

  BlockType DRAGON_EGG = BlockTypeImpl.get("dragon_egg");

  BlockType DRAGON_HEAD = BlockTypeImpl.get("dragon_head");

  BlockType DRAGON_WALL_HEAD = BlockTypeImpl.get("dragon_wall_head");

  BlockType DRIED_GHAST = BlockTypeImpl.get("dried_ghast");

  BlockType DRIED_KELP_BLOCK = BlockTypeImpl.get("dried_kelp_block");

  BlockType DRIPSTONE_BLOCK = BlockTypeImpl.get("dripstone_block");

  BlockType DROPPER = BlockTypeImpl.get("dropper");

  BlockType EMERALD_BLOCK = BlockTypeImpl.get("emerald_block");

  BlockType EMERALD_ORE = BlockTypeImpl.get("emerald_ore");

  BlockType ENCHANTING_TABLE = BlockTypeImpl.get("enchanting_table");

  BlockType END_GATEWAY = BlockTypeImpl.get("end_gateway");

  BlockType END_PORTAL = BlockTypeImpl.get("end_portal");

  BlockType END_PORTAL_FRAME = BlockTypeImpl.get("end_portal_frame");

  BlockType END_ROD = BlockTypeImpl.get("end_rod");

  BlockType END_STONE = BlockTypeImpl.get("end_stone");

  BlockType END_STONE_BRICK_SLAB = BlockTypeImpl.get("end_stone_brick_slab");

  BlockType END_STONE_BRICK_STAIRS = BlockTypeImpl.get("end_stone_brick_stairs");

  BlockType END_STONE_BRICK_WALL = BlockTypeImpl.get("end_stone_brick_wall");

  BlockType END_STONE_BRICKS = BlockTypeImpl.get("end_stone_bricks");

  BlockType ENDER_CHEST = BlockTypeImpl.get("ender_chest");

  BlockType EXPOSED_CHISELED_COPPER = BlockTypeImpl.get("exposed_chiseled_copper");

  BlockType EXPOSED_COPPER = BlockTypeImpl.get("exposed_copper");

  BlockType EXPOSED_COPPER_BULB = BlockTypeImpl.get("exposed_copper_bulb");

  BlockType EXPOSED_COPPER_DOOR = BlockTypeImpl.get("exposed_copper_door");

  BlockType EXPOSED_COPPER_GRATE = BlockTypeImpl.get("exposed_copper_grate");

  BlockType EXPOSED_COPPER_TRAPDOOR = BlockTypeImpl.get("exposed_copper_trapdoor");

  BlockType EXPOSED_CUT_COPPER = BlockTypeImpl.get("exposed_cut_copper");

  BlockType EXPOSED_CUT_COPPER_SLAB = BlockTypeImpl.get("exposed_cut_copper_slab");

  BlockType EXPOSED_CUT_COPPER_STAIRS = BlockTypeImpl.get("exposed_cut_copper_stairs");

  BlockType FARMLAND = BlockTypeImpl.get("farmland");

  BlockType FERN = BlockTypeImpl.get("fern");

  BlockType FIRE = BlockTypeImpl.get("fire");

  BlockType FIRE_CORAL = BlockTypeImpl.get("fire_coral");

  BlockType FIRE_CORAL_BLOCK = BlockTypeImpl.get("fire_coral_block");

  BlockType FIRE_CORAL_FAN = BlockTypeImpl.get("fire_coral_fan");

  BlockType FIRE_CORAL_WALL_FAN = BlockTypeImpl.get("fire_coral_wall_fan");

  BlockType FIREFLY_BUSH = BlockTypeImpl.get("firefly_bush");

  BlockType FLETCHING_TABLE = BlockTypeImpl.get("fletching_table");

  BlockType FLOWER_POT = BlockTypeImpl.get("flower_pot");

  BlockType FLOWERING_AZALEA = BlockTypeImpl.get("flowering_azalea");

  BlockType FLOWERING_AZALEA_LEAVES = BlockTypeImpl.get("flowering_azalea_leaves");

  BlockType FROGSPAWN = BlockTypeImpl.get("frogspawn");

  BlockType FROSTED_ICE = BlockTypeImpl.get("frosted_ice");

  BlockType FURNACE = BlockTypeImpl.get("furnace");

  BlockType GILDED_BLACKSTONE = BlockTypeImpl.get("gilded_blackstone");

  BlockType GLASS = BlockTypeImpl.get("glass");

  BlockType GLASS_PANE = BlockTypeImpl.get("glass_pane");

  BlockType GLOW_LICHEN = BlockTypeImpl.get("glow_lichen");

  BlockType GLOWSTONE = BlockTypeImpl.get("glowstone");

  BlockType GOLD_BLOCK = BlockTypeImpl.get("gold_block");

  BlockType GOLD_ORE = BlockTypeImpl.get("gold_ore");

  BlockType GRANITE = BlockTypeImpl.get("granite");

  BlockType GRANITE_SLAB = BlockTypeImpl.get("granite_slab");

  BlockType GRANITE_STAIRS = BlockTypeImpl.get("granite_stairs");

  BlockType GRANITE_WALL = BlockTypeImpl.get("granite_wall");

  BlockType GRASS_BLOCK = BlockTypeImpl.get("grass_block");

  BlockType GRAVEL = BlockTypeImpl.get("gravel");

  BlockType GRAY_BANNER = BlockTypeImpl.get("gray_banner");

  BlockType GRAY_BED = BlockTypeImpl.get("gray_bed");

  BlockType GRAY_CANDLE = BlockTypeImpl.get("gray_candle");

  BlockType GRAY_CANDLE_CAKE = BlockTypeImpl.get("gray_candle_cake");

  BlockType GRAY_CARPET = BlockTypeImpl.get("gray_carpet");

  BlockType GRAY_CONCRETE = BlockTypeImpl.get("gray_concrete");

  BlockType GRAY_CONCRETE_POWDER = BlockTypeImpl.get("gray_concrete_powder");

  BlockType GRAY_GLAZED_TERRACOTTA = BlockTypeImpl.get("gray_glazed_terracotta");

  BlockType GRAY_SHULKER_BOX = BlockTypeImpl.get("gray_shulker_box");

  BlockType GRAY_STAINED_GLASS = BlockTypeImpl.get("gray_stained_glass");

  BlockType GRAY_STAINED_GLASS_PANE = BlockTypeImpl.get("gray_stained_glass_pane");

  BlockType GRAY_TERRACOTTA = BlockTypeImpl.get("gray_terracotta");

  BlockType GRAY_WALL_BANNER = BlockTypeImpl.get("gray_wall_banner");

  BlockType GRAY_WOOL = BlockTypeImpl.get("gray_wool");

  BlockType GREEN_BANNER = BlockTypeImpl.get("green_banner");

  BlockType GREEN_BED = BlockTypeImpl.get("green_bed");

  BlockType GREEN_CANDLE = BlockTypeImpl.get("green_candle");

  BlockType GREEN_CANDLE_CAKE = BlockTypeImpl.get("green_candle_cake");

  BlockType GREEN_CARPET = BlockTypeImpl.get("green_carpet");

  BlockType GREEN_CONCRETE = BlockTypeImpl.get("green_concrete");

  BlockType GREEN_CONCRETE_POWDER = BlockTypeImpl.get("green_concrete_powder");

  BlockType GREEN_GLAZED_TERRACOTTA = BlockTypeImpl.get("green_glazed_terracotta");

  BlockType GREEN_SHULKER_BOX = BlockTypeImpl.get("green_shulker_box");

  BlockType GREEN_STAINED_GLASS = BlockTypeImpl.get("green_stained_glass");

  BlockType GREEN_STAINED_GLASS_PANE = BlockTypeImpl.get("green_stained_glass_pane");

  BlockType GREEN_TERRACOTTA = BlockTypeImpl.get("green_terracotta");

  BlockType GREEN_WALL_BANNER = BlockTypeImpl.get("green_wall_banner");

  BlockType GREEN_WOOL = BlockTypeImpl.get("green_wool");

  BlockType GRINDSTONE = BlockTypeImpl.get("grindstone");

  BlockType HANGING_ROOTS = BlockTypeImpl.get("hanging_roots");

  BlockType HAY_BLOCK = BlockTypeImpl.get("hay_block");

  BlockType HEAVY_CORE = BlockTypeImpl.get("heavy_core");

  BlockType HEAVY_WEIGHTED_PRESSURE_PLATE = BlockTypeImpl.get("heavy_weighted_pressure_plate");

  BlockType HONEY_BLOCK = BlockTypeImpl.get("honey_block");

  BlockType HONEYCOMB_BLOCK = BlockTypeImpl.get("honeycomb_block");

  BlockType HOPPER = BlockTypeImpl.get("hopper");

  BlockType HORN_CORAL = BlockTypeImpl.get("horn_coral");

  BlockType HORN_CORAL_BLOCK = BlockTypeImpl.get("horn_coral_block");

  BlockType HORN_CORAL_FAN = BlockTypeImpl.get("horn_coral_fan");

  BlockType HORN_CORAL_WALL_FAN = BlockTypeImpl.get("horn_coral_wall_fan");

  BlockType ICE = BlockTypeImpl.get("ice");

  BlockType INFESTED_CHISELED_STONE_BRICKS = BlockTypeImpl.get("infested_chiseled_stone_bricks");

  BlockType INFESTED_COBBLESTONE = BlockTypeImpl.get("infested_cobblestone");

  BlockType INFESTED_CRACKED_STONE_BRICKS = BlockTypeImpl.get("infested_cracked_stone_bricks");

  BlockType INFESTED_DEEPSLATE = BlockTypeImpl.get("infested_deepslate");

  BlockType INFESTED_MOSSY_STONE_BRICKS = BlockTypeImpl.get("infested_mossy_stone_bricks");

  BlockType INFESTED_STONE = BlockTypeImpl.get("infested_stone");

  BlockType INFESTED_STONE_BRICKS = BlockTypeImpl.get("infested_stone_bricks");

  BlockType IRON_BARS = BlockTypeImpl.get("iron_bars");

  BlockType IRON_BLOCK = BlockTypeImpl.get("iron_block");

  BlockType IRON_DOOR = BlockTypeImpl.get("iron_door");

  BlockType IRON_ORE = BlockTypeImpl.get("iron_ore");

  BlockType IRON_TRAPDOOR = BlockTypeImpl.get("iron_trapdoor");

  BlockType JACK_O_LANTERN = BlockTypeImpl.get("jack_o_lantern");

  BlockType JIGSAW = BlockTypeImpl.get("jigsaw");

  BlockType JUKEBOX = BlockTypeImpl.get("jukebox");

  BlockType JUNGLE_BUTTON = BlockTypeImpl.get("jungle_button");

  BlockType JUNGLE_DOOR = BlockTypeImpl.get("jungle_door");

  BlockType JUNGLE_FENCE = BlockTypeImpl.get("jungle_fence");

  BlockType JUNGLE_FENCE_GATE = BlockTypeImpl.get("jungle_fence_gate");

  BlockType JUNGLE_HANGING_SIGN = BlockTypeImpl.get("jungle_hanging_sign");

  BlockType JUNGLE_LEAVES = BlockTypeImpl.get("jungle_leaves");

  BlockType JUNGLE_LOG = BlockTypeImpl.get("jungle_log");

  BlockType JUNGLE_PLANKS = BlockTypeImpl.get("jungle_planks");

  BlockType JUNGLE_PRESSURE_PLATE = BlockTypeImpl.get("jungle_pressure_plate");

  BlockType JUNGLE_SAPLING = BlockTypeImpl.get("jungle_sapling");

  BlockType JUNGLE_SIGN = BlockTypeImpl.get("jungle_sign");

  BlockType JUNGLE_SLAB = BlockTypeImpl.get("jungle_slab");

  BlockType JUNGLE_STAIRS = BlockTypeImpl.get("jungle_stairs");

  BlockType JUNGLE_TRAPDOOR = BlockTypeImpl.get("jungle_trapdoor");

  BlockType JUNGLE_WALL_HANGING_SIGN = BlockTypeImpl.get("jungle_wall_hanging_sign");

  BlockType JUNGLE_WALL_SIGN = BlockTypeImpl.get("jungle_wall_sign");

  BlockType JUNGLE_WOOD = BlockTypeImpl.get("jungle_wood");

  BlockType KELP = BlockTypeImpl.get("kelp");

  BlockType KELP_PLANT = BlockTypeImpl.get("kelp_plant");

  BlockType LADDER = BlockTypeImpl.get("ladder");

  BlockType LANTERN = BlockTypeImpl.get("lantern");

  BlockType LAPIS_BLOCK = BlockTypeImpl.get("lapis_block");

  BlockType LAPIS_ORE = BlockTypeImpl.get("lapis_ore");

  BlockType LARGE_AMETHYST_BUD = BlockTypeImpl.get("large_amethyst_bud");

  BlockType LARGE_FERN = BlockTypeImpl.get("large_fern");

  BlockType LAVA = BlockTypeImpl.get("lava");

  BlockType LAVA_CAULDRON = BlockTypeImpl.get("lava_cauldron");

  BlockType LEAF_LITTER = BlockTypeImpl.get("leaf_litter");

  BlockType LECTERN = BlockTypeImpl.get("lectern");

  BlockType LEVER = BlockTypeImpl.get("lever");

  BlockType LIGHT = BlockTypeImpl.get("light");

  BlockType LIGHT_BLUE_BANNER = BlockTypeImpl.get("light_blue_banner");

  BlockType LIGHT_BLUE_BED = BlockTypeImpl.get("light_blue_bed");

  BlockType LIGHT_BLUE_CANDLE = BlockTypeImpl.get("light_blue_candle");

  BlockType LIGHT_BLUE_CANDLE_CAKE = BlockTypeImpl.get("light_blue_candle_cake");

  BlockType LIGHT_BLUE_CARPET = BlockTypeImpl.get("light_blue_carpet");

  BlockType LIGHT_BLUE_CONCRETE = BlockTypeImpl.get("light_blue_concrete");

  BlockType LIGHT_BLUE_CONCRETE_POWDER = BlockTypeImpl.get("light_blue_concrete_powder");

  BlockType LIGHT_BLUE_GLAZED_TERRACOTTA = BlockTypeImpl.get("light_blue_glazed_terracotta");

  BlockType LIGHT_BLUE_SHULKER_BOX = BlockTypeImpl.get("light_blue_shulker_box");

  BlockType LIGHT_BLUE_STAINED_GLASS = BlockTypeImpl.get("light_blue_stained_glass");

  BlockType LIGHT_BLUE_STAINED_GLASS_PANE = BlockTypeImpl.get("light_blue_stained_glass_pane");

  BlockType LIGHT_BLUE_TERRACOTTA = BlockTypeImpl.get("light_blue_terracotta");

  BlockType LIGHT_BLUE_WALL_BANNER = BlockTypeImpl.get("light_blue_wall_banner");

  BlockType LIGHT_BLUE_WOOL = BlockTypeImpl.get("light_blue_wool");

  BlockType LIGHT_GRAY_BANNER = BlockTypeImpl.get("light_gray_banner");

  BlockType LIGHT_GRAY_BED = BlockTypeImpl.get("light_gray_bed");

  BlockType LIGHT_GRAY_CANDLE = BlockTypeImpl.get("light_gray_candle");

  BlockType LIGHT_GRAY_CANDLE_CAKE = BlockTypeImpl.get("light_gray_candle_cake");

  BlockType LIGHT_GRAY_CARPET = BlockTypeImpl.get("light_gray_carpet");

  BlockType LIGHT_GRAY_CONCRETE = BlockTypeImpl.get("light_gray_concrete");

  BlockType LIGHT_GRAY_CONCRETE_POWDER = BlockTypeImpl.get("light_gray_concrete_powder");

  BlockType LIGHT_GRAY_GLAZED_TERRACOTTA = BlockTypeImpl.get("light_gray_glazed_terracotta");

  BlockType LIGHT_GRAY_SHULKER_BOX = BlockTypeImpl.get("light_gray_shulker_box");

  BlockType LIGHT_GRAY_STAINED_GLASS = BlockTypeImpl.get("light_gray_stained_glass");

  BlockType LIGHT_GRAY_STAINED_GLASS_PANE = BlockTypeImpl.get("light_gray_stained_glass_pane");

  BlockType LIGHT_GRAY_TERRACOTTA = BlockTypeImpl.get("light_gray_terracotta");

  BlockType LIGHT_GRAY_WALL_BANNER = BlockTypeImpl.get("light_gray_wall_banner");

  BlockType LIGHT_GRAY_WOOL = BlockTypeImpl.get("light_gray_wool");

  BlockType LIGHT_WEIGHTED_PRESSURE_PLATE = BlockTypeImpl.get("light_weighted_pressure_plate");

  BlockType LIGHTNING_ROD = BlockTypeImpl.get("lightning_rod");

  BlockType LILAC = BlockTypeImpl.get("lilac");

  BlockType LILY_OF_THE_VALLEY = BlockTypeImpl.get("lily_of_the_valley");

  BlockType LILY_PAD = BlockTypeImpl.get("lily_pad");

  BlockType LIME_BANNER = BlockTypeImpl.get("lime_banner");

  BlockType LIME_BED = BlockTypeImpl.get("lime_bed");

  BlockType LIME_CANDLE = BlockTypeImpl.get("lime_candle");

  BlockType LIME_CANDLE_CAKE = BlockTypeImpl.get("lime_candle_cake");

  BlockType LIME_CARPET = BlockTypeImpl.get("lime_carpet");

  BlockType LIME_CONCRETE = BlockTypeImpl.get("lime_concrete");

  BlockType LIME_CONCRETE_POWDER = BlockTypeImpl.get("lime_concrete_powder");

  BlockType LIME_GLAZED_TERRACOTTA = BlockTypeImpl.get("lime_glazed_terracotta");

  BlockType LIME_SHULKER_BOX = BlockTypeImpl.get("lime_shulker_box");

  BlockType LIME_STAINED_GLASS = BlockTypeImpl.get("lime_stained_glass");

  BlockType LIME_STAINED_GLASS_PANE = BlockTypeImpl.get("lime_stained_glass_pane");

  BlockType LIME_TERRACOTTA = BlockTypeImpl.get("lime_terracotta");

  BlockType LIME_WALL_BANNER = BlockTypeImpl.get("lime_wall_banner");

  BlockType LIME_WOOL = BlockTypeImpl.get("lime_wool");

  BlockType LODESTONE = BlockTypeImpl.get("lodestone");

  BlockType LOOM = BlockTypeImpl.get("loom");

  BlockType MAGENTA_BANNER = BlockTypeImpl.get("magenta_banner");

  BlockType MAGENTA_BED = BlockTypeImpl.get("magenta_bed");

  BlockType MAGENTA_CANDLE = BlockTypeImpl.get("magenta_candle");

  BlockType MAGENTA_CANDLE_CAKE = BlockTypeImpl.get("magenta_candle_cake");

  BlockType MAGENTA_CARPET = BlockTypeImpl.get("magenta_carpet");

  BlockType MAGENTA_CONCRETE = BlockTypeImpl.get("magenta_concrete");

  BlockType MAGENTA_CONCRETE_POWDER = BlockTypeImpl.get("magenta_concrete_powder");

  BlockType MAGENTA_GLAZED_TERRACOTTA = BlockTypeImpl.get("magenta_glazed_terracotta");

  BlockType MAGENTA_SHULKER_BOX = BlockTypeImpl.get("magenta_shulker_box");

  BlockType MAGENTA_STAINED_GLASS = BlockTypeImpl.get("magenta_stained_glass");

  BlockType MAGENTA_STAINED_GLASS_PANE = BlockTypeImpl.get("magenta_stained_glass_pane");

  BlockType MAGENTA_TERRACOTTA = BlockTypeImpl.get("magenta_terracotta");

  BlockType MAGENTA_WALL_BANNER = BlockTypeImpl.get("magenta_wall_banner");

  BlockType MAGENTA_WOOL = BlockTypeImpl.get("magenta_wool");

  BlockType MAGMA_BLOCK = BlockTypeImpl.get("magma_block");

  BlockType MANGROVE_BUTTON = BlockTypeImpl.get("mangrove_button");

  BlockType MANGROVE_DOOR = BlockTypeImpl.get("mangrove_door");

  BlockType MANGROVE_FENCE = BlockTypeImpl.get("mangrove_fence");

  BlockType MANGROVE_FENCE_GATE = BlockTypeImpl.get("mangrove_fence_gate");

  BlockType MANGROVE_HANGING_SIGN = BlockTypeImpl.get("mangrove_hanging_sign");

  BlockType MANGROVE_LEAVES = BlockTypeImpl.get("mangrove_leaves");

  BlockType MANGROVE_LOG = BlockTypeImpl.get("mangrove_log");

  BlockType MANGROVE_PLANKS = BlockTypeImpl.get("mangrove_planks");

  BlockType MANGROVE_PRESSURE_PLATE = BlockTypeImpl.get("mangrove_pressure_plate");

  BlockType MANGROVE_PROPAGULE = BlockTypeImpl.get("mangrove_propagule");

  BlockType MANGROVE_ROOTS = BlockTypeImpl.get("mangrove_roots");

  BlockType MANGROVE_SIGN = BlockTypeImpl.get("mangrove_sign");

  BlockType MANGROVE_SLAB = BlockTypeImpl.get("mangrove_slab");

  BlockType MANGROVE_STAIRS = BlockTypeImpl.get("mangrove_stairs");

  BlockType MANGROVE_TRAPDOOR = BlockTypeImpl.get("mangrove_trapdoor");

  BlockType MANGROVE_WALL_HANGING_SIGN = BlockTypeImpl.get("mangrove_wall_hanging_sign");

  BlockType MANGROVE_WALL_SIGN = BlockTypeImpl.get("mangrove_wall_sign");

  BlockType MANGROVE_WOOD = BlockTypeImpl.get("mangrove_wood");

  BlockType MEDIUM_AMETHYST_BUD = BlockTypeImpl.get("medium_amethyst_bud");

  BlockType MELON = BlockTypeImpl.get("melon");

  BlockType MELON_STEM = BlockTypeImpl.get("melon_stem");

  BlockType MOSS_BLOCK = BlockTypeImpl.get("moss_block");

  BlockType MOSS_CARPET = BlockTypeImpl.get("moss_carpet");

  BlockType MOSSY_COBBLESTONE = BlockTypeImpl.get("mossy_cobblestone");

  BlockType MOSSY_COBBLESTONE_SLAB = BlockTypeImpl.get("mossy_cobblestone_slab");

  BlockType MOSSY_COBBLESTONE_STAIRS = BlockTypeImpl.get("mossy_cobblestone_stairs");

  BlockType MOSSY_COBBLESTONE_WALL = BlockTypeImpl.get("mossy_cobblestone_wall");

  BlockType MOSSY_STONE_BRICK_SLAB = BlockTypeImpl.get("mossy_stone_brick_slab");

  BlockType MOSSY_STONE_BRICK_STAIRS = BlockTypeImpl.get("mossy_stone_brick_stairs");

  BlockType MOSSY_STONE_BRICK_WALL = BlockTypeImpl.get("mossy_stone_brick_wall");

  BlockType MOSSY_STONE_BRICKS = BlockTypeImpl.get("mossy_stone_bricks");

  BlockType MOVING_PISTON = BlockTypeImpl.get("moving_piston");

  BlockType MUD = BlockTypeImpl.get("mud");

  BlockType MUD_BRICK_SLAB = BlockTypeImpl.get("mud_brick_slab");

  BlockType MUD_BRICK_STAIRS = BlockTypeImpl.get("mud_brick_stairs");

  BlockType MUD_BRICK_WALL = BlockTypeImpl.get("mud_brick_wall");

  BlockType MUD_BRICKS = BlockTypeImpl.get("mud_bricks");

  BlockType MUDDY_MANGROVE_ROOTS = BlockTypeImpl.get("muddy_mangrove_roots");

  BlockType MUSHROOM_STEM = BlockTypeImpl.get("mushroom_stem");

  BlockType MYCELIUM = BlockTypeImpl.get("mycelium");

  BlockType NETHER_BRICK_FENCE = BlockTypeImpl.get("nether_brick_fence");

  BlockType NETHER_BRICK_SLAB = BlockTypeImpl.get("nether_brick_slab");

  BlockType NETHER_BRICK_STAIRS = BlockTypeImpl.get("nether_brick_stairs");

  BlockType NETHER_BRICK_WALL = BlockTypeImpl.get("nether_brick_wall");

  BlockType NETHER_BRICKS = BlockTypeImpl.get("nether_bricks");

  BlockType NETHER_GOLD_ORE = BlockTypeImpl.get("nether_gold_ore");

  BlockType NETHER_PORTAL = BlockTypeImpl.get("nether_portal");

  BlockType NETHER_QUARTZ_ORE = BlockTypeImpl.get("nether_quartz_ore");

  BlockType NETHER_SPROUTS = BlockTypeImpl.get("nether_sprouts");

  BlockType NETHER_WART = BlockTypeImpl.get("nether_wart");

  BlockType NETHER_WART_BLOCK = BlockTypeImpl.get("nether_wart_block");

  BlockType NETHERITE_BLOCK = BlockTypeImpl.get("netherite_block");

  BlockType NETHERRACK = BlockTypeImpl.get("netherrack");

  BlockType NOTE_BLOCK = BlockTypeImpl.get("note_block");

  BlockType OAK_BUTTON = BlockTypeImpl.get("oak_button");

  BlockType OAK_DOOR = BlockTypeImpl.get("oak_door");

  BlockType OAK_FENCE = BlockTypeImpl.get("oak_fence");

  BlockType OAK_FENCE_GATE = BlockTypeImpl.get("oak_fence_gate");

  BlockType OAK_HANGING_SIGN = BlockTypeImpl.get("oak_hanging_sign");

  BlockType OAK_LEAVES = BlockTypeImpl.get("oak_leaves");

  BlockType OAK_LOG = BlockTypeImpl.get("oak_log");

  BlockType OAK_PLANKS = BlockTypeImpl.get("oak_planks");

  BlockType OAK_PRESSURE_PLATE = BlockTypeImpl.get("oak_pressure_plate");

  BlockType OAK_SAPLING = BlockTypeImpl.get("oak_sapling");

  BlockType OAK_SIGN = BlockTypeImpl.get("oak_sign");

  BlockType OAK_SLAB = BlockTypeImpl.get("oak_slab");

  BlockType OAK_STAIRS = BlockTypeImpl.get("oak_stairs");

  BlockType OAK_TRAPDOOR = BlockTypeImpl.get("oak_trapdoor");

  BlockType OAK_WALL_HANGING_SIGN = BlockTypeImpl.get("oak_wall_hanging_sign");

  BlockType OAK_WALL_SIGN = BlockTypeImpl.get("oak_wall_sign");

  BlockType OAK_WOOD = BlockTypeImpl.get("oak_wood");

  BlockType OBSERVER = BlockTypeImpl.get("observer");

  BlockType OBSIDIAN = BlockTypeImpl.get("obsidian");

  BlockType OCHRE_FROGLIGHT = BlockTypeImpl.get("ochre_froglight");

  BlockType OPEN_EYEBLOSSOM = BlockTypeImpl.get("open_eyeblossom");

  BlockType ORANGE_BANNER = BlockTypeImpl.get("orange_banner");

  BlockType ORANGE_BED = BlockTypeImpl.get("orange_bed");

  BlockType ORANGE_CANDLE = BlockTypeImpl.get("orange_candle");

  BlockType ORANGE_CANDLE_CAKE = BlockTypeImpl.get("orange_candle_cake");

  BlockType ORANGE_CARPET = BlockTypeImpl.get("orange_carpet");

  BlockType ORANGE_CONCRETE = BlockTypeImpl.get("orange_concrete");

  BlockType ORANGE_CONCRETE_POWDER = BlockTypeImpl.get("orange_concrete_powder");

  BlockType ORANGE_GLAZED_TERRACOTTA = BlockTypeImpl.get("orange_glazed_terracotta");

  BlockType ORANGE_SHULKER_BOX = BlockTypeImpl.get("orange_shulker_box");

  BlockType ORANGE_STAINED_GLASS = BlockTypeImpl.get("orange_stained_glass");

  BlockType ORANGE_STAINED_GLASS_PANE = BlockTypeImpl.get("orange_stained_glass_pane");

  BlockType ORANGE_TERRACOTTA = BlockTypeImpl.get("orange_terracotta");

  BlockType ORANGE_TULIP = BlockTypeImpl.get("orange_tulip");

  BlockType ORANGE_WALL_BANNER = BlockTypeImpl.get("orange_wall_banner");

  BlockType ORANGE_WOOL = BlockTypeImpl.get("orange_wool");

  BlockType OXEYE_DAISY = BlockTypeImpl.get("oxeye_daisy");

  BlockType OXIDIZED_CHISELED_COPPER = BlockTypeImpl.get("oxidized_chiseled_copper");

  BlockType OXIDIZED_COPPER = BlockTypeImpl.get("oxidized_copper");

  BlockType OXIDIZED_COPPER_BULB = BlockTypeImpl.get("oxidized_copper_bulb");

  BlockType OXIDIZED_COPPER_DOOR = BlockTypeImpl.get("oxidized_copper_door");

  BlockType OXIDIZED_COPPER_GRATE = BlockTypeImpl.get("oxidized_copper_grate");

  BlockType OXIDIZED_COPPER_TRAPDOOR = BlockTypeImpl.get("oxidized_copper_trapdoor");

  BlockType OXIDIZED_CUT_COPPER = BlockTypeImpl.get("oxidized_cut_copper");

  BlockType OXIDIZED_CUT_COPPER_SLAB = BlockTypeImpl.get("oxidized_cut_copper_slab");

  BlockType OXIDIZED_CUT_COPPER_STAIRS = BlockTypeImpl.get("oxidized_cut_copper_stairs");

  BlockType PACKED_ICE = BlockTypeImpl.get("packed_ice");

  BlockType PACKED_MUD = BlockTypeImpl.get("packed_mud");

  BlockType PALE_HANGING_MOSS = BlockTypeImpl.get("pale_hanging_moss");

  BlockType PALE_MOSS_BLOCK = BlockTypeImpl.get("pale_moss_block");

  BlockType PALE_MOSS_CARPET = BlockTypeImpl.get("pale_moss_carpet");

  BlockType PALE_OAK_BUTTON = BlockTypeImpl.get("pale_oak_button");

  BlockType PALE_OAK_DOOR = BlockTypeImpl.get("pale_oak_door");

  BlockType PALE_OAK_FENCE = BlockTypeImpl.get("pale_oak_fence");

  BlockType PALE_OAK_FENCE_GATE = BlockTypeImpl.get("pale_oak_fence_gate");

  BlockType PALE_OAK_HANGING_SIGN = BlockTypeImpl.get("pale_oak_hanging_sign");

  BlockType PALE_OAK_LEAVES = BlockTypeImpl.get("pale_oak_leaves");

  BlockType PALE_OAK_LOG = BlockTypeImpl.get("pale_oak_log");

  BlockType PALE_OAK_PLANKS = BlockTypeImpl.get("pale_oak_planks");

  BlockType PALE_OAK_PRESSURE_PLATE = BlockTypeImpl.get("pale_oak_pressure_plate");

  BlockType PALE_OAK_SAPLING = BlockTypeImpl.get("pale_oak_sapling");

  BlockType PALE_OAK_SIGN = BlockTypeImpl.get("pale_oak_sign");

  BlockType PALE_OAK_SLAB = BlockTypeImpl.get("pale_oak_slab");

  BlockType PALE_OAK_STAIRS = BlockTypeImpl.get("pale_oak_stairs");

  BlockType PALE_OAK_TRAPDOOR = BlockTypeImpl.get("pale_oak_trapdoor");

  BlockType PALE_OAK_WALL_HANGING_SIGN = BlockTypeImpl.get("pale_oak_wall_hanging_sign");

  BlockType PALE_OAK_WALL_SIGN = BlockTypeImpl.get("pale_oak_wall_sign");

  BlockType PALE_OAK_WOOD = BlockTypeImpl.get("pale_oak_wood");

  BlockType PEARLESCENT_FROGLIGHT = BlockTypeImpl.get("pearlescent_froglight");

  BlockType PEONY = BlockTypeImpl.get("peony");

  BlockType PETRIFIED_OAK_SLAB = BlockTypeImpl.get("petrified_oak_slab");

  BlockType PIGLIN_HEAD = BlockTypeImpl.get("piglin_head");

  BlockType PIGLIN_WALL_HEAD = BlockTypeImpl.get("piglin_wall_head");

  BlockType PINK_BANNER = BlockTypeImpl.get("pink_banner");

  BlockType PINK_BED = BlockTypeImpl.get("pink_bed");

  BlockType PINK_CANDLE = BlockTypeImpl.get("pink_candle");

  BlockType PINK_CANDLE_CAKE = BlockTypeImpl.get("pink_candle_cake");

  BlockType PINK_CARPET = BlockTypeImpl.get("pink_carpet");

  BlockType PINK_CONCRETE = BlockTypeImpl.get("pink_concrete");

  BlockType PINK_CONCRETE_POWDER = BlockTypeImpl.get("pink_concrete_powder");

  BlockType PINK_GLAZED_TERRACOTTA = BlockTypeImpl.get("pink_glazed_terracotta");

  BlockType PINK_PETALS = BlockTypeImpl.get("pink_petals");

  BlockType PINK_SHULKER_BOX = BlockTypeImpl.get("pink_shulker_box");

  BlockType PINK_STAINED_GLASS = BlockTypeImpl.get("pink_stained_glass");

  BlockType PINK_STAINED_GLASS_PANE = BlockTypeImpl.get("pink_stained_glass_pane");

  BlockType PINK_TERRACOTTA = BlockTypeImpl.get("pink_terracotta");

  BlockType PINK_TULIP = BlockTypeImpl.get("pink_tulip");

  BlockType PINK_WALL_BANNER = BlockTypeImpl.get("pink_wall_banner");

  BlockType PINK_WOOL = BlockTypeImpl.get("pink_wool");

  BlockType PISTON = BlockTypeImpl.get("piston");

  BlockType PISTON_HEAD = BlockTypeImpl.get("piston_head");

  BlockType PITCHER_CROP = BlockTypeImpl.get("pitcher_crop");

  BlockType PITCHER_PLANT = BlockTypeImpl.get("pitcher_plant");

  BlockType PLAYER_HEAD = BlockTypeImpl.get("player_head");

  BlockType PLAYER_WALL_HEAD = BlockTypeImpl.get("player_wall_head");

  BlockType PODZOL = BlockTypeImpl.get("podzol");

  BlockType POINTED_DRIPSTONE = BlockTypeImpl.get("pointed_dripstone");

  BlockType POLISHED_ANDESITE = BlockTypeImpl.get("polished_andesite");

  BlockType POLISHED_ANDESITE_SLAB = BlockTypeImpl.get("polished_andesite_slab");

  BlockType POLISHED_ANDESITE_STAIRS = BlockTypeImpl.get("polished_andesite_stairs");

  BlockType POLISHED_BASALT = BlockTypeImpl.get("polished_basalt");

  BlockType POLISHED_BLACKSTONE = BlockTypeImpl.get("polished_blackstone");

  BlockType POLISHED_BLACKSTONE_BRICK_SLAB = BlockTypeImpl.get("polished_blackstone_brick_slab");

  BlockType POLISHED_BLACKSTONE_BRICK_STAIRS = BlockTypeImpl.get("polished_blackstone_brick_stairs");

  BlockType POLISHED_BLACKSTONE_BRICK_WALL = BlockTypeImpl.get("polished_blackstone_brick_wall");

  BlockType POLISHED_BLACKSTONE_BRICKS = BlockTypeImpl.get("polished_blackstone_bricks");

  BlockType POLISHED_BLACKSTONE_BUTTON = BlockTypeImpl.get("polished_blackstone_button");

  BlockType POLISHED_BLACKSTONE_PRESSURE_PLATE = BlockTypeImpl.get("polished_blackstone_pressure_plate");

  BlockType POLISHED_BLACKSTONE_SLAB = BlockTypeImpl.get("polished_blackstone_slab");

  BlockType POLISHED_BLACKSTONE_STAIRS = BlockTypeImpl.get("polished_blackstone_stairs");

  BlockType POLISHED_BLACKSTONE_WALL = BlockTypeImpl.get("polished_blackstone_wall");

  BlockType POLISHED_DEEPSLATE = BlockTypeImpl.get("polished_deepslate");

  BlockType POLISHED_DEEPSLATE_SLAB = BlockTypeImpl.get("polished_deepslate_slab");

  BlockType POLISHED_DEEPSLATE_STAIRS = BlockTypeImpl.get("polished_deepslate_stairs");

  BlockType POLISHED_DEEPSLATE_WALL = BlockTypeImpl.get("polished_deepslate_wall");

  BlockType POLISHED_DIORITE = BlockTypeImpl.get("polished_diorite");

  BlockType POLISHED_DIORITE_SLAB = BlockTypeImpl.get("polished_diorite_slab");

  BlockType POLISHED_DIORITE_STAIRS = BlockTypeImpl.get("polished_diorite_stairs");

  BlockType POLISHED_GRANITE = BlockTypeImpl.get("polished_granite");

  BlockType POLISHED_GRANITE_SLAB = BlockTypeImpl.get("polished_granite_slab");

  BlockType POLISHED_GRANITE_STAIRS = BlockTypeImpl.get("polished_granite_stairs");

  BlockType POLISHED_TUFF = BlockTypeImpl.get("polished_tuff");

  BlockType POLISHED_TUFF_SLAB = BlockTypeImpl.get("polished_tuff_slab");

  BlockType POLISHED_TUFF_STAIRS = BlockTypeImpl.get("polished_tuff_stairs");

  BlockType POLISHED_TUFF_WALL = BlockTypeImpl.get("polished_tuff_wall");

  BlockType POPPY = BlockTypeImpl.get("poppy");

  BlockType POTATOES = BlockTypeImpl.get("potatoes");

  BlockType POTTED_ACACIA_SAPLING = BlockTypeImpl.get("potted_acacia_sapling");

  BlockType POTTED_ALLIUM = BlockTypeImpl.get("potted_allium");

  BlockType POTTED_AZALEA_BUSH = BlockTypeImpl.get("potted_azalea_bush");

  BlockType POTTED_AZURE_BLUET = BlockTypeImpl.get("potted_azure_bluet");

  BlockType POTTED_BAMBOO = BlockTypeImpl.get("potted_bamboo");

  BlockType POTTED_BIRCH_SAPLING = BlockTypeImpl.get("potted_birch_sapling");

  BlockType POTTED_BLUE_ORCHID = BlockTypeImpl.get("potted_blue_orchid");

  BlockType POTTED_BROWN_MUSHROOM = BlockTypeImpl.get("potted_brown_mushroom");

  BlockType POTTED_CACTUS = BlockTypeImpl.get("potted_cactus");

  BlockType POTTED_CHERRY_SAPLING = BlockTypeImpl.get("potted_cherry_sapling");

  BlockType POTTED_CLOSED_EYEBLOSSOM = BlockTypeImpl.get("potted_closed_eyeblossom");

  BlockType POTTED_CORNFLOWER = BlockTypeImpl.get("potted_cornflower");

  BlockType POTTED_CRIMSON_FUNGUS = BlockTypeImpl.get("potted_crimson_fungus");

  BlockType POTTED_CRIMSON_ROOTS = BlockTypeImpl.get("potted_crimson_roots");

  BlockType POTTED_DANDELION = BlockTypeImpl.get("potted_dandelion");

  BlockType POTTED_DARK_OAK_SAPLING = BlockTypeImpl.get("potted_dark_oak_sapling");

  BlockType POTTED_DEAD_BUSH = BlockTypeImpl.get("potted_dead_bush");

  BlockType POTTED_FERN = BlockTypeImpl.get("potted_fern");

  BlockType POTTED_FLOWERING_AZALEA_BUSH = BlockTypeImpl.get("potted_flowering_azalea_bush");

  BlockType POTTED_JUNGLE_SAPLING = BlockTypeImpl.get("potted_jungle_sapling");

  BlockType POTTED_LILY_OF_THE_VALLEY = BlockTypeImpl.get("potted_lily_of_the_valley");

  BlockType POTTED_MANGROVE_PROPAGULE = BlockTypeImpl.get("potted_mangrove_propagule");

  BlockType POTTED_OAK_SAPLING = BlockTypeImpl.get("potted_oak_sapling");

  BlockType POTTED_OPEN_EYEBLOSSOM = BlockTypeImpl.get("potted_open_eyeblossom");

  BlockType POTTED_ORANGE_TULIP = BlockTypeImpl.get("potted_orange_tulip");

  BlockType POTTED_OXEYE_DAISY = BlockTypeImpl.get("potted_oxeye_daisy");

  BlockType POTTED_PALE_OAK_SAPLING = BlockTypeImpl.get("potted_pale_oak_sapling");

  BlockType POTTED_PINK_TULIP = BlockTypeImpl.get("potted_pink_tulip");

  BlockType POTTED_POPPY = BlockTypeImpl.get("potted_poppy");

  BlockType POTTED_RED_MUSHROOM = BlockTypeImpl.get("potted_red_mushroom");

  BlockType POTTED_RED_TULIP = BlockTypeImpl.get("potted_red_tulip");

  BlockType POTTED_SPRUCE_SAPLING = BlockTypeImpl.get("potted_spruce_sapling");

  BlockType POTTED_TORCHFLOWER = BlockTypeImpl.get("potted_torchflower");

  BlockType POTTED_WARPED_FUNGUS = BlockTypeImpl.get("potted_warped_fungus");

  BlockType POTTED_WARPED_ROOTS = BlockTypeImpl.get("potted_warped_roots");

  BlockType POTTED_WHITE_TULIP = BlockTypeImpl.get("potted_white_tulip");

  BlockType POTTED_WITHER_ROSE = BlockTypeImpl.get("potted_wither_rose");

  BlockType POWDER_SNOW = BlockTypeImpl.get("powder_snow");

  BlockType POWDER_SNOW_CAULDRON = BlockTypeImpl.get("powder_snow_cauldron");

  BlockType POWERED_RAIL = BlockTypeImpl.get("powered_rail");

  BlockType PRISMARINE = BlockTypeImpl.get("prismarine");

  BlockType PRISMARINE_BRICK_SLAB = BlockTypeImpl.get("prismarine_brick_slab");

  BlockType PRISMARINE_BRICK_STAIRS = BlockTypeImpl.get("prismarine_brick_stairs");

  BlockType PRISMARINE_BRICKS = BlockTypeImpl.get("prismarine_bricks");

  BlockType PRISMARINE_SLAB = BlockTypeImpl.get("prismarine_slab");

  BlockType PRISMARINE_STAIRS = BlockTypeImpl.get("prismarine_stairs");

  BlockType PRISMARINE_WALL = BlockTypeImpl.get("prismarine_wall");

  BlockType PUMPKIN = BlockTypeImpl.get("pumpkin");

  BlockType PUMPKIN_STEM = BlockTypeImpl.get("pumpkin_stem");

  BlockType PURPLE_BANNER = BlockTypeImpl.get("purple_banner");

  BlockType PURPLE_BED = BlockTypeImpl.get("purple_bed");

  BlockType PURPLE_CANDLE = BlockTypeImpl.get("purple_candle");

  BlockType PURPLE_CANDLE_CAKE = BlockTypeImpl.get("purple_candle_cake");

  BlockType PURPLE_CARPET = BlockTypeImpl.get("purple_carpet");

  BlockType PURPLE_CONCRETE = BlockTypeImpl.get("purple_concrete");

  BlockType PURPLE_CONCRETE_POWDER = BlockTypeImpl.get("purple_concrete_powder");

  BlockType PURPLE_GLAZED_TERRACOTTA = BlockTypeImpl.get("purple_glazed_terracotta");

  BlockType PURPLE_SHULKER_BOX = BlockTypeImpl.get("purple_shulker_box");

  BlockType PURPLE_STAINED_GLASS = BlockTypeImpl.get("purple_stained_glass");

  BlockType PURPLE_STAINED_GLASS_PANE = BlockTypeImpl.get("purple_stained_glass_pane");

  BlockType PURPLE_TERRACOTTA = BlockTypeImpl.get("purple_terracotta");

  BlockType PURPLE_WALL_BANNER = BlockTypeImpl.get("purple_wall_banner");

  BlockType PURPLE_WOOL = BlockTypeImpl.get("purple_wool");

  BlockType PURPUR_BLOCK = BlockTypeImpl.get("purpur_block");

  BlockType PURPUR_PILLAR = BlockTypeImpl.get("purpur_pillar");

  BlockType PURPUR_SLAB = BlockTypeImpl.get("purpur_slab");

  BlockType PURPUR_STAIRS = BlockTypeImpl.get("purpur_stairs");

  BlockType QUARTZ_BLOCK = BlockTypeImpl.get("quartz_block");

  BlockType QUARTZ_BRICKS = BlockTypeImpl.get("quartz_bricks");

  BlockType QUARTZ_PILLAR = BlockTypeImpl.get("quartz_pillar");

  BlockType QUARTZ_SLAB = BlockTypeImpl.get("quartz_slab");

  BlockType QUARTZ_STAIRS = BlockTypeImpl.get("quartz_stairs");

  BlockType RAIL = BlockTypeImpl.get("rail");

  BlockType RAW_COPPER_BLOCK = BlockTypeImpl.get("raw_copper_block");

  BlockType RAW_GOLD_BLOCK = BlockTypeImpl.get("raw_gold_block");

  BlockType RAW_IRON_BLOCK = BlockTypeImpl.get("raw_iron_block");

  BlockType RED_BANNER = BlockTypeImpl.get("red_banner");

  BlockType RED_BED = BlockTypeImpl.get("red_bed");

  BlockType RED_CANDLE = BlockTypeImpl.get("red_candle");

  BlockType RED_CANDLE_CAKE = BlockTypeImpl.get("red_candle_cake");

  BlockType RED_CARPET = BlockTypeImpl.get("red_carpet");

  BlockType RED_CONCRETE = BlockTypeImpl.get("red_concrete");

  BlockType RED_CONCRETE_POWDER = BlockTypeImpl.get("red_concrete_powder");

  BlockType RED_GLAZED_TERRACOTTA = BlockTypeImpl.get("red_glazed_terracotta");

  BlockType RED_MUSHROOM = BlockTypeImpl.get("red_mushroom");

  BlockType RED_MUSHROOM_BLOCK = BlockTypeImpl.get("red_mushroom_block");

  BlockType RED_NETHER_BRICK_SLAB = BlockTypeImpl.get("red_nether_brick_slab");

  BlockType RED_NETHER_BRICK_STAIRS = BlockTypeImpl.get("red_nether_brick_stairs");

  BlockType RED_NETHER_BRICK_WALL = BlockTypeImpl.get("red_nether_brick_wall");

  BlockType RED_NETHER_BRICKS = BlockTypeImpl.get("red_nether_bricks");

  BlockType RED_SAND = BlockTypeImpl.get("red_sand");

  BlockType RED_SANDSTONE = BlockTypeImpl.get("red_sandstone");

  BlockType RED_SANDSTONE_SLAB = BlockTypeImpl.get("red_sandstone_slab");

  BlockType RED_SANDSTONE_STAIRS = BlockTypeImpl.get("red_sandstone_stairs");

  BlockType RED_SANDSTONE_WALL = BlockTypeImpl.get("red_sandstone_wall");

  BlockType RED_SHULKER_BOX = BlockTypeImpl.get("red_shulker_box");

  BlockType RED_STAINED_GLASS = BlockTypeImpl.get("red_stained_glass");

  BlockType RED_STAINED_GLASS_PANE = BlockTypeImpl.get("red_stained_glass_pane");

  BlockType RED_TERRACOTTA = BlockTypeImpl.get("red_terracotta");

  BlockType RED_TULIP = BlockTypeImpl.get("red_tulip");

  BlockType RED_WALL_BANNER = BlockTypeImpl.get("red_wall_banner");

  BlockType RED_WOOL = BlockTypeImpl.get("red_wool");

  BlockType REDSTONE_BLOCK = BlockTypeImpl.get("redstone_block");

  BlockType REDSTONE_LAMP = BlockTypeImpl.get("redstone_lamp");

  BlockType REDSTONE_ORE = BlockTypeImpl.get("redstone_ore");

  BlockType REDSTONE_TORCH = BlockTypeImpl.get("redstone_torch");

  BlockType REDSTONE_WALL_TORCH = BlockTypeImpl.get("redstone_wall_torch");

  BlockType REDSTONE_WIRE = BlockTypeImpl.get("redstone_wire");

  BlockType REINFORCED_DEEPSLATE = BlockTypeImpl.get("reinforced_deepslate");

  BlockType REPEATER = BlockTypeImpl.get("repeater");

  BlockType REPEATING_COMMAND_BLOCK = BlockTypeImpl.get("repeating_command_block");

  BlockType RESIN_BLOCK = BlockTypeImpl.get("resin_block");

  BlockType RESIN_BRICK_SLAB = BlockTypeImpl.get("resin_brick_slab");

  BlockType RESIN_BRICK_STAIRS = BlockTypeImpl.get("resin_brick_stairs");

  BlockType RESIN_BRICK_WALL = BlockTypeImpl.get("resin_brick_wall");

  BlockType RESIN_BRICKS = BlockTypeImpl.get("resin_bricks");

  BlockType RESIN_CLUMP = BlockTypeImpl.get("resin_clump");

  BlockType RESPAWN_ANCHOR = BlockTypeImpl.get("respawn_anchor");

  BlockType ROOTED_DIRT = BlockTypeImpl.get("rooted_dirt");

  BlockType ROSE_BUSH = BlockTypeImpl.get("rose_bush");

  BlockType SAND = BlockTypeImpl.get("sand");

  BlockType SANDSTONE = BlockTypeImpl.get("sandstone");

  BlockType SANDSTONE_SLAB = BlockTypeImpl.get("sandstone_slab");

  BlockType SANDSTONE_STAIRS = BlockTypeImpl.get("sandstone_stairs");

  BlockType SANDSTONE_WALL = BlockTypeImpl.get("sandstone_wall");

  BlockType SCAFFOLDING = BlockTypeImpl.get("scaffolding");

  BlockType SCULK = BlockTypeImpl.get("sculk");

  BlockType SCULK_CATALYST = BlockTypeImpl.get("sculk_catalyst");

  BlockType SCULK_SENSOR = BlockTypeImpl.get("sculk_sensor");

  BlockType SCULK_SHRIEKER = BlockTypeImpl.get("sculk_shrieker");

  BlockType SCULK_VEIN = BlockTypeImpl.get("sculk_vein");

  BlockType SEA_LANTERN = BlockTypeImpl.get("sea_lantern");

  BlockType SEA_PICKLE = BlockTypeImpl.get("sea_pickle");

  BlockType SEAGRASS = BlockTypeImpl.get("seagrass");

  BlockType SHORT_DRY_GRASS = BlockTypeImpl.get("short_dry_grass");

  BlockType SHORT_GRASS = BlockTypeImpl.get("short_grass");

  BlockType SHROOMLIGHT = BlockTypeImpl.get("shroomlight");

  BlockType SHULKER_BOX = BlockTypeImpl.get("shulker_box");

  BlockType SKELETON_SKULL = BlockTypeImpl.get("skeleton_skull");

  BlockType SKELETON_WALL_SKULL = BlockTypeImpl.get("skeleton_wall_skull");

  BlockType SLIME_BLOCK = BlockTypeImpl.get("slime_block");

  BlockType SMALL_AMETHYST_BUD = BlockTypeImpl.get("small_amethyst_bud");

  BlockType SMALL_DRIPLEAF = BlockTypeImpl.get("small_dripleaf");

  BlockType SMITHING_TABLE = BlockTypeImpl.get("smithing_table");

  BlockType SMOKER = BlockTypeImpl.get("smoker");

  BlockType SMOOTH_BASALT = BlockTypeImpl.get("smooth_basalt");

  BlockType SMOOTH_QUARTZ = BlockTypeImpl.get("smooth_quartz");

  BlockType SMOOTH_QUARTZ_SLAB = BlockTypeImpl.get("smooth_quartz_slab");

  BlockType SMOOTH_QUARTZ_STAIRS = BlockTypeImpl.get("smooth_quartz_stairs");

  BlockType SMOOTH_RED_SANDSTONE = BlockTypeImpl.get("smooth_red_sandstone");

  BlockType SMOOTH_RED_SANDSTONE_SLAB = BlockTypeImpl.get("smooth_red_sandstone_slab");

  BlockType SMOOTH_RED_SANDSTONE_STAIRS = BlockTypeImpl.get("smooth_red_sandstone_stairs");

  BlockType SMOOTH_SANDSTONE = BlockTypeImpl.get("smooth_sandstone");

  BlockType SMOOTH_SANDSTONE_SLAB = BlockTypeImpl.get("smooth_sandstone_slab");

  BlockType SMOOTH_SANDSTONE_STAIRS = BlockTypeImpl.get("smooth_sandstone_stairs");

  BlockType SMOOTH_STONE = BlockTypeImpl.get("smooth_stone");

  BlockType SMOOTH_STONE_SLAB = BlockTypeImpl.get("smooth_stone_slab");

  BlockType SNIFFER_EGG = BlockTypeImpl.get("sniffer_egg");

  BlockType SNOW = BlockTypeImpl.get("snow");

  BlockType SNOW_BLOCK = BlockTypeImpl.get("snow_block");

  BlockType SOUL_CAMPFIRE = BlockTypeImpl.get("soul_campfire");

  BlockType SOUL_FIRE = BlockTypeImpl.get("soul_fire");

  BlockType SOUL_LANTERN = BlockTypeImpl.get("soul_lantern");

  BlockType SOUL_SAND = BlockTypeImpl.get("soul_sand");

  BlockType SOUL_SOIL = BlockTypeImpl.get("soul_soil");

  BlockType SOUL_TORCH = BlockTypeImpl.get("soul_torch");

  BlockType SOUL_WALL_TORCH = BlockTypeImpl.get("soul_wall_torch");

  BlockType SPAWNER = BlockTypeImpl.get("spawner");

  BlockType SPONGE = BlockTypeImpl.get("sponge");

  BlockType SPORE_BLOSSOM = BlockTypeImpl.get("spore_blossom");

  BlockType SPRUCE_BUTTON = BlockTypeImpl.get("spruce_button");

  BlockType SPRUCE_DOOR = BlockTypeImpl.get("spruce_door");

  BlockType SPRUCE_FENCE = BlockTypeImpl.get("spruce_fence");

  BlockType SPRUCE_FENCE_GATE = BlockTypeImpl.get("spruce_fence_gate");

  BlockType SPRUCE_HANGING_SIGN = BlockTypeImpl.get("spruce_hanging_sign");

  BlockType SPRUCE_LEAVES = BlockTypeImpl.get("spruce_leaves");

  BlockType SPRUCE_LOG = BlockTypeImpl.get("spruce_log");

  BlockType SPRUCE_PLANKS = BlockTypeImpl.get("spruce_planks");

  BlockType SPRUCE_PRESSURE_PLATE = BlockTypeImpl.get("spruce_pressure_plate");

  BlockType SPRUCE_SAPLING = BlockTypeImpl.get("spruce_sapling");

  BlockType SPRUCE_SIGN = BlockTypeImpl.get("spruce_sign");

  BlockType SPRUCE_SLAB = BlockTypeImpl.get("spruce_slab");

  BlockType SPRUCE_STAIRS = BlockTypeImpl.get("spruce_stairs");

  BlockType SPRUCE_TRAPDOOR = BlockTypeImpl.get("spruce_trapdoor");

  BlockType SPRUCE_WALL_HANGING_SIGN = BlockTypeImpl.get("spruce_wall_hanging_sign");

  BlockType SPRUCE_WALL_SIGN = BlockTypeImpl.get("spruce_wall_sign");

  BlockType SPRUCE_WOOD = BlockTypeImpl.get("spruce_wood");

  BlockType STICKY_PISTON = BlockTypeImpl.get("sticky_piston");

  BlockType STONE = BlockTypeImpl.get("stone");

  BlockType STONE_BRICK_SLAB = BlockTypeImpl.get("stone_brick_slab");

  BlockType STONE_BRICK_STAIRS = BlockTypeImpl.get("stone_brick_stairs");

  BlockType STONE_BRICK_WALL = BlockTypeImpl.get("stone_brick_wall");

  BlockType STONE_BRICKS = BlockTypeImpl.get("stone_bricks");

  BlockType STONE_BUTTON = BlockTypeImpl.get("stone_button");

  BlockType STONE_PRESSURE_PLATE = BlockTypeImpl.get("stone_pressure_plate");

  BlockType STONE_SLAB = BlockTypeImpl.get("stone_slab");

  BlockType STONE_STAIRS = BlockTypeImpl.get("stone_stairs");

  BlockType STONECUTTER = BlockTypeImpl.get("stonecutter");

  BlockType STRIPPED_ACACIA_LOG = BlockTypeImpl.get("stripped_acacia_log");

  BlockType STRIPPED_ACACIA_WOOD = BlockTypeImpl.get("stripped_acacia_wood");

  BlockType STRIPPED_BAMBOO_BLOCK = BlockTypeImpl.get("stripped_bamboo_block");

  BlockType STRIPPED_BIRCH_LOG = BlockTypeImpl.get("stripped_birch_log");

  BlockType STRIPPED_BIRCH_WOOD = BlockTypeImpl.get("stripped_birch_wood");

  BlockType STRIPPED_CHERRY_LOG = BlockTypeImpl.get("stripped_cherry_log");

  BlockType STRIPPED_CHERRY_WOOD = BlockTypeImpl.get("stripped_cherry_wood");

  BlockType STRIPPED_CRIMSON_HYPHAE = BlockTypeImpl.get("stripped_crimson_hyphae");

  BlockType STRIPPED_CRIMSON_STEM = BlockTypeImpl.get("stripped_crimson_stem");

  BlockType STRIPPED_DARK_OAK_LOG = BlockTypeImpl.get("stripped_dark_oak_log");

  BlockType STRIPPED_DARK_OAK_WOOD = BlockTypeImpl.get("stripped_dark_oak_wood");

  BlockType STRIPPED_JUNGLE_LOG = BlockTypeImpl.get("stripped_jungle_log");

  BlockType STRIPPED_JUNGLE_WOOD = BlockTypeImpl.get("stripped_jungle_wood");

  BlockType STRIPPED_MANGROVE_LOG = BlockTypeImpl.get("stripped_mangrove_log");

  BlockType STRIPPED_MANGROVE_WOOD = BlockTypeImpl.get("stripped_mangrove_wood");

  BlockType STRIPPED_OAK_LOG = BlockTypeImpl.get("stripped_oak_log");

  BlockType STRIPPED_OAK_WOOD = BlockTypeImpl.get("stripped_oak_wood");

  BlockType STRIPPED_PALE_OAK_LOG = BlockTypeImpl.get("stripped_pale_oak_log");

  BlockType STRIPPED_PALE_OAK_WOOD = BlockTypeImpl.get("stripped_pale_oak_wood");

  BlockType STRIPPED_SPRUCE_LOG = BlockTypeImpl.get("stripped_spruce_log");

  BlockType STRIPPED_SPRUCE_WOOD = BlockTypeImpl.get("stripped_spruce_wood");

  BlockType STRIPPED_WARPED_HYPHAE = BlockTypeImpl.get("stripped_warped_hyphae");

  BlockType STRIPPED_WARPED_STEM = BlockTypeImpl.get("stripped_warped_stem");

  BlockType STRUCTURE_BLOCK = BlockTypeImpl.get("structure_block");

  BlockType STRUCTURE_VOID = BlockTypeImpl.get("structure_void");

  BlockType SUGAR_CANE = BlockTypeImpl.get("sugar_cane");

  BlockType SUNFLOWER = BlockTypeImpl.get("sunflower");

  BlockType SUSPICIOUS_GRAVEL = BlockTypeImpl.get("suspicious_gravel");

  BlockType SUSPICIOUS_SAND = BlockTypeImpl.get("suspicious_sand");

  BlockType SWEET_BERRY_BUSH = BlockTypeImpl.get("sweet_berry_bush");

  BlockType TALL_DRY_GRASS = BlockTypeImpl.get("tall_dry_grass");

  BlockType TALL_GRASS = BlockTypeImpl.get("tall_grass");

  BlockType TALL_SEAGRASS = BlockTypeImpl.get("tall_seagrass");

  BlockType TARGET = BlockTypeImpl.get("target");

  BlockType TERRACOTTA = BlockTypeImpl.get("terracotta");

  BlockType TEST_BLOCK = BlockTypeImpl.get("test_block");

  BlockType TEST_INSTANCE_BLOCK = BlockTypeImpl.get("test_instance_block");

  BlockType TINTED_GLASS = BlockTypeImpl.get("tinted_glass");

  BlockType TNT = BlockTypeImpl.get("tnt");

  BlockType TORCH = BlockTypeImpl.get("torch");

  BlockType TORCHFLOWER = BlockTypeImpl.get("torchflower");

  BlockType TORCHFLOWER_CROP = BlockTypeImpl.get("torchflower_crop");

  BlockType TRAPPED_CHEST = BlockTypeImpl.get("trapped_chest");

  BlockType TRIAL_SPAWNER = BlockTypeImpl.get("trial_spawner");

  BlockType TRIPWIRE = BlockTypeImpl.get("tripwire");

  BlockType TRIPWIRE_HOOK = BlockTypeImpl.get("tripwire_hook");

  BlockType TUBE_CORAL = BlockTypeImpl.get("tube_coral");

  BlockType TUBE_CORAL_BLOCK = BlockTypeImpl.get("tube_coral_block");

  BlockType TUBE_CORAL_FAN = BlockTypeImpl.get("tube_coral_fan");

  BlockType TUBE_CORAL_WALL_FAN = BlockTypeImpl.get("tube_coral_wall_fan");

  BlockType TUFF = BlockTypeImpl.get("tuff");

  BlockType TUFF_BRICK_SLAB = BlockTypeImpl.get("tuff_brick_slab");

  BlockType TUFF_BRICK_STAIRS = BlockTypeImpl.get("tuff_brick_stairs");

  BlockType TUFF_BRICK_WALL = BlockTypeImpl.get("tuff_brick_wall");

  BlockType TUFF_BRICKS = BlockTypeImpl.get("tuff_bricks");

  BlockType TUFF_SLAB = BlockTypeImpl.get("tuff_slab");

  BlockType TUFF_STAIRS = BlockTypeImpl.get("tuff_stairs");

  BlockType TUFF_WALL = BlockTypeImpl.get("tuff_wall");

  BlockType TURTLE_EGG = BlockTypeImpl.get("turtle_egg");

  BlockType TWISTING_VINES = BlockTypeImpl.get("twisting_vines");

  BlockType TWISTING_VINES_PLANT = BlockTypeImpl.get("twisting_vines_plant");

  BlockType VAULT = BlockTypeImpl.get("vault");

  BlockType VERDANT_FROGLIGHT = BlockTypeImpl.get("verdant_froglight");

  BlockType VINE = BlockTypeImpl.get("vine");

  BlockType VOID_AIR = BlockTypeImpl.get("void_air");

  BlockType WALL_TORCH = BlockTypeImpl.get("wall_torch");

  BlockType WARPED_BUTTON = BlockTypeImpl.get("warped_button");

  BlockType WARPED_DOOR = BlockTypeImpl.get("warped_door");

  BlockType WARPED_FENCE = BlockTypeImpl.get("warped_fence");

  BlockType WARPED_FENCE_GATE = BlockTypeImpl.get("warped_fence_gate");

  BlockType WARPED_FUNGUS = BlockTypeImpl.get("warped_fungus");

  BlockType WARPED_HANGING_SIGN = BlockTypeImpl.get("warped_hanging_sign");

  BlockType WARPED_HYPHAE = BlockTypeImpl.get("warped_hyphae");

  BlockType WARPED_NYLIUM = BlockTypeImpl.get("warped_nylium");

  BlockType WARPED_PLANKS = BlockTypeImpl.get("warped_planks");

  BlockType WARPED_PRESSURE_PLATE = BlockTypeImpl.get("warped_pressure_plate");

  BlockType WARPED_ROOTS = BlockTypeImpl.get("warped_roots");

  BlockType WARPED_SIGN = BlockTypeImpl.get("warped_sign");

  BlockType WARPED_SLAB = BlockTypeImpl.get("warped_slab");

  BlockType WARPED_STAIRS = BlockTypeImpl.get("warped_stairs");

  BlockType WARPED_STEM = BlockTypeImpl.get("warped_stem");

  BlockType WARPED_TRAPDOOR = BlockTypeImpl.get("warped_trapdoor");

  BlockType WARPED_WALL_HANGING_SIGN = BlockTypeImpl.get("warped_wall_hanging_sign");

  BlockType WARPED_WALL_SIGN = BlockTypeImpl.get("warped_wall_sign");

  BlockType WARPED_WART_BLOCK = BlockTypeImpl.get("warped_wart_block");

  BlockType WATER = BlockTypeImpl.get("water");

  BlockType WATER_CAULDRON = BlockTypeImpl.get("water_cauldron");

  BlockType WAXED_CHISELED_COPPER = BlockTypeImpl.get("waxed_chiseled_copper");

  BlockType WAXED_COPPER_BLOCK = BlockTypeImpl.get("waxed_copper_block");

  BlockType WAXED_COPPER_BULB = BlockTypeImpl.get("waxed_copper_bulb");

  BlockType WAXED_COPPER_DOOR = BlockTypeImpl.get("waxed_copper_door");

  BlockType WAXED_COPPER_GRATE = BlockTypeImpl.get("waxed_copper_grate");

  BlockType WAXED_COPPER_TRAPDOOR = BlockTypeImpl.get("waxed_copper_trapdoor");

  BlockType WAXED_CUT_COPPER = BlockTypeImpl.get("waxed_cut_copper");

  BlockType WAXED_CUT_COPPER_SLAB = BlockTypeImpl.get("waxed_cut_copper_slab");

  BlockType WAXED_CUT_COPPER_STAIRS = BlockTypeImpl.get("waxed_cut_copper_stairs");

  BlockType WAXED_EXPOSED_CHISELED_COPPER = BlockTypeImpl.get("waxed_exposed_chiseled_copper");

  BlockType WAXED_EXPOSED_COPPER = BlockTypeImpl.get("waxed_exposed_copper");

  BlockType WAXED_EXPOSED_COPPER_BULB = BlockTypeImpl.get("waxed_exposed_copper_bulb");

  BlockType WAXED_EXPOSED_COPPER_DOOR = BlockTypeImpl.get("waxed_exposed_copper_door");

  BlockType WAXED_EXPOSED_COPPER_GRATE = BlockTypeImpl.get("waxed_exposed_copper_grate");

  BlockType WAXED_EXPOSED_COPPER_TRAPDOOR = BlockTypeImpl.get("waxed_exposed_copper_trapdoor");

  BlockType WAXED_EXPOSED_CUT_COPPER = BlockTypeImpl.get("waxed_exposed_cut_copper");

  BlockType WAXED_EXPOSED_CUT_COPPER_SLAB = BlockTypeImpl.get("waxed_exposed_cut_copper_slab");

  BlockType WAXED_EXPOSED_CUT_COPPER_STAIRS = BlockTypeImpl.get("waxed_exposed_cut_copper_stairs");

  BlockType WAXED_OXIDIZED_CHISELED_COPPER = BlockTypeImpl.get("waxed_oxidized_chiseled_copper");

  BlockType WAXED_OXIDIZED_COPPER = BlockTypeImpl.get("waxed_oxidized_copper");

  BlockType WAXED_OXIDIZED_COPPER_BULB = BlockTypeImpl.get("waxed_oxidized_copper_bulb");

  BlockType WAXED_OXIDIZED_COPPER_DOOR = BlockTypeImpl.get("waxed_oxidized_copper_door");

  BlockType WAXED_OXIDIZED_COPPER_GRATE = BlockTypeImpl.get("waxed_oxidized_copper_grate");

  BlockType WAXED_OXIDIZED_COPPER_TRAPDOOR = BlockTypeImpl.get("waxed_oxidized_copper_trapdoor");

  BlockType WAXED_OXIDIZED_CUT_COPPER = BlockTypeImpl.get("waxed_oxidized_cut_copper");

  BlockType WAXED_OXIDIZED_CUT_COPPER_SLAB = BlockTypeImpl.get("waxed_oxidized_cut_copper_slab");

  BlockType WAXED_OXIDIZED_CUT_COPPER_STAIRS = BlockTypeImpl.get("waxed_oxidized_cut_copper_stairs");

  BlockType WAXED_WEATHERED_CHISELED_COPPER = BlockTypeImpl.get("waxed_weathered_chiseled_copper");

  BlockType WAXED_WEATHERED_COPPER = BlockTypeImpl.get("waxed_weathered_copper");

  BlockType WAXED_WEATHERED_COPPER_BULB = BlockTypeImpl.get("waxed_weathered_copper_bulb");

  BlockType WAXED_WEATHERED_COPPER_DOOR = BlockTypeImpl.get("waxed_weathered_copper_door");

  BlockType WAXED_WEATHERED_COPPER_GRATE = BlockTypeImpl.get("waxed_weathered_copper_grate");

  BlockType WAXED_WEATHERED_COPPER_TRAPDOOR = BlockTypeImpl.get("waxed_weathered_copper_trapdoor");

  BlockType WAXED_WEATHERED_CUT_COPPER = BlockTypeImpl.get("waxed_weathered_cut_copper");

  BlockType WAXED_WEATHERED_CUT_COPPER_SLAB = BlockTypeImpl.get("waxed_weathered_cut_copper_slab");

  BlockType WAXED_WEATHERED_CUT_COPPER_STAIRS = BlockTypeImpl.get("waxed_weathered_cut_copper_stairs");

  BlockType WEATHERED_CHISELED_COPPER = BlockTypeImpl.get("weathered_chiseled_copper");

  BlockType WEATHERED_COPPER = BlockTypeImpl.get("weathered_copper");

  BlockType WEATHERED_COPPER_BULB = BlockTypeImpl.get("weathered_copper_bulb");

  BlockType WEATHERED_COPPER_DOOR = BlockTypeImpl.get("weathered_copper_door");

  BlockType WEATHERED_COPPER_GRATE = BlockTypeImpl.get("weathered_copper_grate");

  BlockType WEATHERED_COPPER_TRAPDOOR = BlockTypeImpl.get("weathered_copper_trapdoor");

  BlockType WEATHERED_CUT_COPPER = BlockTypeImpl.get("weathered_cut_copper");

  BlockType WEATHERED_CUT_COPPER_SLAB = BlockTypeImpl.get("weathered_cut_copper_slab");

  BlockType WEATHERED_CUT_COPPER_STAIRS = BlockTypeImpl.get("weathered_cut_copper_stairs");

  BlockType WEEPING_VINES = BlockTypeImpl.get("weeping_vines");

  BlockType WEEPING_VINES_PLANT = BlockTypeImpl.get("weeping_vines_plant");

  BlockType WET_SPONGE = BlockTypeImpl.get("wet_sponge");

  BlockType WHEAT = BlockTypeImpl.get("wheat");

  BlockType WHITE_BANNER = BlockTypeImpl.get("white_banner");

  BlockType WHITE_BED = BlockTypeImpl.get("white_bed");

  BlockType WHITE_CANDLE = BlockTypeImpl.get("white_candle");

  BlockType WHITE_CANDLE_CAKE = BlockTypeImpl.get("white_candle_cake");

  BlockType WHITE_CARPET = BlockTypeImpl.get("white_carpet");

  BlockType WHITE_CONCRETE = BlockTypeImpl.get("white_concrete");

  BlockType WHITE_CONCRETE_POWDER = BlockTypeImpl.get("white_concrete_powder");

  BlockType WHITE_GLAZED_TERRACOTTA = BlockTypeImpl.get("white_glazed_terracotta");

  BlockType WHITE_SHULKER_BOX = BlockTypeImpl.get("white_shulker_box");

  BlockType WHITE_STAINED_GLASS = BlockTypeImpl.get("white_stained_glass");

  BlockType WHITE_STAINED_GLASS_PANE = BlockTypeImpl.get("white_stained_glass_pane");

  BlockType WHITE_TERRACOTTA = BlockTypeImpl.get("white_terracotta");

  BlockType WHITE_TULIP = BlockTypeImpl.get("white_tulip");

  BlockType WHITE_WALL_BANNER = BlockTypeImpl.get("white_wall_banner");

  BlockType WHITE_WOOL = BlockTypeImpl.get("white_wool");

  BlockType WILDFLOWERS = BlockTypeImpl.get("wildflowers");

  BlockType WITHER_ROSE = BlockTypeImpl.get("wither_rose");

  BlockType WITHER_SKELETON_SKULL = BlockTypeImpl.get("wither_skeleton_skull");

  BlockType WITHER_SKELETON_WALL_SKULL = BlockTypeImpl.get("wither_skeleton_wall_skull");

  BlockType YELLOW_BANNER = BlockTypeImpl.get("yellow_banner");

  BlockType YELLOW_BED = BlockTypeImpl.get("yellow_bed");

  BlockType YELLOW_CANDLE = BlockTypeImpl.get("yellow_candle");

  BlockType YELLOW_CANDLE_CAKE = BlockTypeImpl.get("yellow_candle_cake");

  BlockType YELLOW_CARPET = BlockTypeImpl.get("yellow_carpet");

  BlockType YELLOW_CONCRETE = BlockTypeImpl.get("yellow_concrete");

  BlockType YELLOW_CONCRETE_POWDER = BlockTypeImpl.get("yellow_concrete_powder");

  BlockType YELLOW_GLAZED_TERRACOTTA = BlockTypeImpl.get("yellow_glazed_terracotta");

  BlockType YELLOW_SHULKER_BOX = BlockTypeImpl.get("yellow_shulker_box");

  BlockType YELLOW_STAINED_GLASS = BlockTypeImpl.get("yellow_stained_glass");

  BlockType YELLOW_STAINED_GLASS_PANE = BlockTypeImpl.get("yellow_stained_glass_pane");

  BlockType YELLOW_TERRACOTTA = BlockTypeImpl.get("yellow_terracotta");

  BlockType YELLOW_WALL_BANNER = BlockTypeImpl.get("yellow_wall_banner");

  BlockType YELLOW_WOOL = BlockTypeImpl.get("yellow_wool");

  BlockType ZOMBIE_HEAD = BlockTypeImpl.get("zombie_head");

  BlockType ZOMBIE_WALL_HEAD = BlockTypeImpl.get("zombie_wall_head");
}
