package me.moros.bending.api.platform.block;

/**
 * Code autogenerated, do not edit! v1.19.2
 */
@SuppressWarnings("unused")
interface Tags {
  BlockTag WITHER_IMMUNE = TagImpl.get("wither_immune");

  BlockTag WOOL_CARPETS = TagImpl.get("wool_carpets");

  BlockTag MOSS_REPLACEABLE = TagImpl.get("moss_replaceable");

  BlockTag TALL_FLOWERS = TagImpl.get("tall_flowers");

  BlockTag OCCLUDES_VIBRATION_SIGNALS = TagImpl.get("occludes_vibration_signals");

  BlockTag STAIRS = TagImpl.get("stairs");

  BlockTag NYLIUM = TagImpl.get("nylium");

  BlockTag NETHER_CARVER_REPLACEABLES = TagImpl.get("nether_carver_replaceables");

  BlockTag NEEDS_IRON_TOOL = TagImpl.get("needs_iron_tool");

  BlockTag DARK_OAK_LOGS = TagImpl.get("dark_oak_logs");

  BlockTag SNOW_LAYER_CAN_SURVIVE_ON = TagImpl.get("snow_layer_can_survive_on");

  BlockTag RAILS = TagImpl.get("rails");

  BlockTag MANGROVE_ROOTS_CAN_GROW_THROUGH = TagImpl.get("mangrove_roots_can_grow_through");

  BlockTag SNOW = TagImpl.get("snow");

  BlockTag LUSH_GROUND_REPLACEABLE = TagImpl.get("lush_ground_replaceable");

  BlockTag NEEDS_STONE_TOOL = TagImpl.get("needs_stone_tool");

  BlockTag SMALL_DRIPLEAF_PLACEABLE = TagImpl.get("small_dripleaf_placeable");

  BlockTag CRIMSON_STEMS = TagImpl.get("crimson_stems");

  BlockTag INFINIBURN_OVERWORLD = TagImpl.get("infiniburn_overworld");

  BlockTag PLANKS = TagImpl.get("planks");

  BlockTag ICE = TagImpl.get("ice");

  BlockTag DRAGON_IMMUNE = TagImpl.get("dragon_immune");

  BlockTag AZALEA_ROOT_REPLACEABLE = TagImpl.get("azalea_root_replaceable");

  BlockTag PORTALS = TagImpl.get("portals");

  BlockTag GEODE_INVALID_BLOCKS = TagImpl.get("geode_invalid_blocks");

  BlockTag PREVENT_MOB_SPAWNING_INSIDE = TagImpl.get("prevent_mob_spawning_inside");

  BlockTag SCULK_REPLACEABLE_WORLD_GEN = TagImpl.get("sculk_replaceable_world_gen");

  BlockTag REPLACEABLE_PLANTS = TagImpl.get("replaceable_plants");

  BlockTag PARROTS_SPAWNABLE_ON = TagImpl.get("parrots_spawnable_on");

  BlockTag MOOSHROOMS_SPAWNABLE_ON = TagImpl.get("mooshrooms_spawnable_on");

  BlockTag STONE_PRESSURE_PLATES = TagImpl.get("stone_pressure_plates");

  BlockTag SMALL_FLOWERS = TagImpl.get("small_flowers");

  BlockTag SAPLINGS = TagImpl.get("saplings");

  BlockTag FENCE_GATES = TagImpl.get("fence_gates");

  BlockTag CORAL_PLANTS = TagImpl.get("coral_plants");

  BlockTag WART_BLOCKS = TagImpl.get("wart_blocks");

  BlockTag SAND = TagImpl.get("sand");

  BlockTag SOUL_FIRE_BASE_BLOCKS = TagImpl.get("soul_fire_base_blocks");

  BlockTag ACACIA_LOGS = TagImpl.get("acacia_logs");

  BlockTag DIAMOND_ORES = TagImpl.get("diamond_ores");

  BlockTag INFINIBURN_END = TagImpl.get("infiniburn_end");

  BlockTag WARPED_STEMS = TagImpl.get("warped_stems");

  BlockTag LOGS = TagImpl.get("logs");

  BlockTag STONE_BRICKS = TagImpl.get("stone_bricks");

  BlockTag SLABS = TagImpl.get("slabs");

  BlockTag LAVA_POOL_STONE_CANNOT_REPLACE = TagImpl.get("lava_pool_stone_cannot_replace");

  BlockTag SIGNS = TagImpl.get("signs");

  BlockTag SCULK_REPLACEABLE = TagImpl.get("sculk_replaceable");

  BlockTag WALL_POST_OVERRIDE = TagImpl.get("wall_post_override");

  BlockTag FOXES_SPAWNABLE_ON = TagImpl.get("foxes_spawnable_on");

  BlockTag INFINIBURN_NETHER = TagImpl.get("infiniburn_nether");

  BlockTag STONE_ORE_REPLACEABLES = TagImpl.get("stone_ore_replaceables");

  BlockTag WALL_SIGNS = TagImpl.get("wall_signs");

  BlockTag ANVIL = TagImpl.get("anvil");

  BlockTag GUARDED_BY_PIGLINS = TagImpl.get("guarded_by_piglins");

  BlockTag WOLVES_SPAWNABLE_ON = TagImpl.get("wolves_spawnable_on");

  BlockTag BAMBOO_PLANTABLE_ON = TagImpl.get("bamboo_plantable_on");

  BlockTag BANNERS = TagImpl.get("banners");

  BlockTag GOATS_SPAWNABLE_ON = TagImpl.get("goats_spawnable_on");

  BlockTag MANGROVE_LOGS = TagImpl.get("mangrove_logs");

  BlockTag WALLS = TagImpl.get("walls");

  BlockTag DRAGON_TRANSPARENT = TagImpl.get("dragon_transparent");

  BlockTag DEEPSLATE_ORE_REPLACEABLES = TagImpl.get("deepslate_ore_replaceables");

  BlockTag BEDS = TagImpl.get("beds");

  BlockTag ENDERMAN_HOLDABLE = TagImpl.get("enderman_holdable");

  BlockTag CORALS = TagImpl.get("corals");

  BlockTag SHULKER_BOXES = TagImpl.get("shulker_boxes");

  BlockTag CLIMBABLE = TagImpl.get("climbable");

  BlockTag JUNGLE_LOGS = TagImpl.get("jungle_logs");

  BlockTag GOLD_ORES = TagImpl.get("gold_ores");

  BlockTag CONVERTABLE_TO_MUD = TagImpl.get("convertable_to_mud");

  BlockTag CROPS = TagImpl.get("crops");

  BlockTag POLAR_BEARS_SPAWNABLE_ON_ALTERNATE = TagImpl.get("polar_bears_spawnable_on_alternate");

  BlockTag BEEHIVES = TagImpl.get("beehives");

  BlockTag WOODEN_TRAPDOORS = TagImpl.get("wooden_trapdoors");

  BlockTag TRAPDOORS = TagImpl.get("trapdoors");

  BlockTag LOGS_THAT_BURN = TagImpl.get("logs_that_burn");

  BlockTag CANDLE_CAKES = TagImpl.get("candle_cakes");

  BlockTag CANDLES = TagImpl.get("candles");

  BlockTag BIG_DRIPLEAF_PLACEABLE = TagImpl.get("big_dripleaf_placeable");

  BlockTag CAMPFIRES = TagImpl.get("campfires");

  BlockTag BEE_GROWABLES = TagImpl.get("bee_growables");

  BlockTag OAK_LOGS = TagImpl.get("oak_logs");

  BlockTag CRYSTAL_SOUND_BLOCKS = TagImpl.get("crystal_sound_blocks");

  BlockTag EMERALD_ORES = TagImpl.get("emerald_ores");

  BlockTag AZALEA_GROWS_ON = TagImpl.get("azalea_grows_on");

  BlockTag COMPLETES_FIND_TREE_TUTORIAL = TagImpl.get("completes_find_tree_tutorial");

  BlockTag FROG_PREFER_JUMP_TO = TagImpl.get("frog_prefer_jump_to");

  BlockTag FLOWERS = TagImpl.get("flowers");

  BlockTag CAULDRONS = TagImpl.get("cauldrons");

  BlockTag WOODEN_BUTTONS = TagImpl.get("wooden_buttons");

  BlockTag FIRE = TagImpl.get("fire");

  BlockTag AXOLOTLS_SPAWNABLE_ON = TagImpl.get("axolotls_spawnable_on");

  BlockTag MANGROVE_LOGS_CAN_GROW_THROUGH = TagImpl.get("mangrove_logs_can_grow_through");

  BlockTag FALL_DAMAGE_RESETTING = TagImpl.get("fall_damage_resetting");

  BlockTag ANCIENT_CITY_REPLACEABLE = TagImpl.get("ancient_city_replaceable");

  BlockTag PRESSURE_PLATES = TagImpl.get("pressure_plates");

  BlockTag VALID_SPAWN = TagImpl.get("valid_spawn");

  BlockTag DAMPENS_VIBRATIONS = TagImpl.get("dampens_vibrations");

  BlockTag MINEABLE_PICKAXE = TagImpl.get("mineable/pickaxe");

  BlockTag MINEABLE_HOE = TagImpl.get("mineable/hoe");

  BlockTag MINEABLE_SHOVEL = TagImpl.get("mineable/shovel");

  BlockTag MINEABLE_AXE = TagImpl.get("mineable/axe");

  BlockTag BASE_STONE_OVERWORLD = TagImpl.get("base_stone_overworld");

  BlockTag CORAL_BLOCKS = TagImpl.get("coral_blocks");

  BlockTag UNDERWATER_BONEMEALS = TagImpl.get("underwater_bonemeals");

  BlockTag CAVE_VINES = TagImpl.get("cave_vines");

  BlockTag SOUL_SPEED_BLOCKS = TagImpl.get("soul_speed_blocks");

  BlockTag OVERWORLD_NATURAL_LOGS = TagImpl.get("overworld_natural_logs");

  BlockTag RABBITS_SPAWNABLE_ON = TagImpl.get("rabbits_spawnable_on");

  BlockTag INSIDE_STEP_SOUND_BLOCKS = TagImpl.get("inside_step_sound_blocks");

  BlockTag BASE_STONE_NETHER = TagImpl.get("base_stone_nether");

  BlockTag STANDING_SIGNS = TagImpl.get("standing_signs");

  BlockTag WALL_CORALS = TagImpl.get("wall_corals");

  BlockTag WOODEN_DOORS = TagImpl.get("wooden_doors");

  BlockTag BUTTONS = TagImpl.get("buttons");

  BlockTag UNSTABLE_BOTTOM_CENTER = TagImpl.get("unstable_bottom_center");

  BlockTag IRON_ORES = TagImpl.get("iron_ores");

  BlockTag DIRT = TagImpl.get("dirt");

  BlockTag BEACON_BASE_BLOCKS = TagImpl.get("beacon_base_blocks");

  BlockTag WOOL = TagImpl.get("wool");

  BlockTag DRIPSTONE_REPLACEABLE_BLOCKS = TagImpl.get("dripstone_replaceable_blocks");

  BlockTag WOODEN_FENCES = TagImpl.get("wooden_fences");

  BlockTag WOODEN_PRESSURE_PLATES = TagImpl.get("wooden_pressure_plates");

  BlockTag FROGS_SPAWNABLE_ON = TagImpl.get("frogs_spawnable_on");

  BlockTag PIGLIN_REPELLENTS = TagImpl.get("piglin_repellents");

  BlockTag WOODEN_STAIRS = TagImpl.get("wooden_stairs");

  BlockTag LEAVES = TagImpl.get("leaves");

  BlockTag DOORS = TagImpl.get("doors");

  BlockTag OVERWORLD_CARVER_REPLACEABLES = TagImpl.get("overworld_carver_replaceables");

  BlockTag ANIMALS_SPAWNABLE_ON = TagImpl.get("animals_spawnable_on");

  BlockTag HOGLIN_REPELLENTS = TagImpl.get("hoglin_repellents");

  BlockTag WOODEN_SLABS = TagImpl.get("wooden_slabs");

  BlockTag FENCES = TagImpl.get("fences");

  BlockTag WITHER_SUMMON_BASE_BLOCKS = TagImpl.get("wither_summon_base_blocks");

  BlockTag FLOWER_POTS = TagImpl.get("flower_pots");

  BlockTag REDSTONE_ORES = TagImpl.get("redstone_ores");

  BlockTag STRIDER_WARM_BLOCKS = TagImpl.get("strider_warm_blocks");

  BlockTag SNOW_LAYER_CANNOT_SURVIVE_ON = TagImpl.get("snow_layer_cannot_survive_on");

  BlockTag DEAD_BUSH_MAY_PLACE_ON = TagImpl.get("dead_bush_may_place_on");

  BlockTag FEATURES_CANNOT_REPLACE = TagImpl.get("features_cannot_replace");

  BlockTag MUSHROOM_GROW_BLOCK = TagImpl.get("mushroom_grow_block");

  BlockTag NON_FLAMMABLE_WOOD = TagImpl.get("non_flammable_wood");

  BlockTag LAPIS_ORES = TagImpl.get("lapis_ores");

  BlockTag SNAPS_GOAT_HORN = TagImpl.get("snaps_goat_horn");

  BlockTag TERRACOTTA = TagImpl.get("terracotta");

  BlockTag COAL_ORES = TagImpl.get("coal_ores");

  BlockTag BIRCH_LOGS = TagImpl.get("birch_logs");

  BlockTag COPPER_ORES = TagImpl.get("copper_ores");

  BlockTag NEEDS_DIAMOND_TOOL = TagImpl.get("needs_diamond_tool");

  BlockTag SPRUCE_LOGS = TagImpl.get("spruce_logs");

  BlockTag IMPERMEABLE = TagImpl.get("impermeable");
}
