package me.moros.bending.api.platform.potion;

/**
 * Code autogenerated, do not edit! v1.21.9
 */
@SuppressWarnings("unused")
interface PotionEffects {
  PotionEffect ABSORPTION = PotionEffectImpl.get("absorption");

  PotionEffect BAD_OMEN = PotionEffectImpl.get("bad_omen");

  PotionEffect BLINDNESS = PotionEffectImpl.get("blindness");

  PotionEffect CONDUIT_POWER = PotionEffectImpl.get("conduit_power");

  PotionEffect DARKNESS = PotionEffectImpl.get("darkness");

  PotionEffect DOLPHINS_GRACE = PotionEffectImpl.get("dolphins_grace");

  PotionEffect FIRE_RESISTANCE = PotionEffectImpl.get("fire_resistance");

  PotionEffect GLOWING = PotionEffectImpl.get("glowing");

  PotionEffect HASTE = PotionEffectImpl.get("haste");

  PotionEffect HEALTH_BOOST = PotionEffectImpl.get("health_boost");

  PotionEffect HERO_OF_THE_VILLAGE = PotionEffectImpl.get("hero_of_the_village");

  PotionEffect HUNGER = PotionEffectImpl.get("hunger");

  PotionEffect INFESTED = PotionEffectImpl.get("infested");

  PotionEffect INSTANT_DAMAGE = PotionEffectImpl.get("instant_damage");

  PotionEffect INSTANT_HEALTH = PotionEffectImpl.get("instant_health");

  PotionEffect INVISIBILITY = PotionEffectImpl.get("invisibility");

  PotionEffect JUMP_BOOST = PotionEffectImpl.get("jump_boost");

  PotionEffect LEVITATION = PotionEffectImpl.get("levitation");

  PotionEffect LUCK = PotionEffectImpl.get("luck");

  PotionEffect MINING_FATIGUE = PotionEffectImpl.get("mining_fatigue");

  PotionEffect NAUSEA = PotionEffectImpl.get("nausea");

  PotionEffect NIGHT_VISION = PotionEffectImpl.get("night_vision");

  PotionEffect OOZING = PotionEffectImpl.get("oozing");

  PotionEffect POISON = PotionEffectImpl.get("poison");

  PotionEffect RAID_OMEN = PotionEffectImpl.get("raid_omen");

  PotionEffect REGENERATION = PotionEffectImpl.get("regeneration");

  PotionEffect RESISTANCE = PotionEffectImpl.get("resistance");

  PotionEffect SATURATION = PotionEffectImpl.get("saturation");

  PotionEffect SLOW_FALLING = PotionEffectImpl.get("slow_falling");

  PotionEffect SLOWNESS = PotionEffectImpl.get("slowness");

  PotionEffect SPEED = PotionEffectImpl.get("speed");

  PotionEffect STRENGTH = PotionEffectImpl.get("strength");

  PotionEffect TRIAL_OMEN = PotionEffectImpl.get("trial_omen");

  PotionEffect UNLUCK = PotionEffectImpl.get("unluck");

  PotionEffect WATER_BREATHING = PotionEffectImpl.get("water_breathing");

  PotionEffect WEAKNESS = PotionEffectImpl.get("weakness");

  PotionEffect WEAVING = PotionEffectImpl.get("weaving");

  PotionEffect WIND_CHARGED = PotionEffectImpl.get("wind_charged");

  PotionEffect WITHER = PotionEffectImpl.get("wither");
}
