package me.moros.bending.api.platform.entity;

/**
 * Code autogenerated, do not edit! v1.21.11
 */
@SuppressWarnings("unused")
interface AttributeTypes {
  AttributeType ARMOR = AttributeTypeImpl.get("armor");

  AttributeType ARMOR_TOUGHNESS = AttributeTypeImpl.get("armor_toughness");

  AttributeType ATTACK_DAMAGE = AttributeTypeImpl.get("attack_damage");

  AttributeType ATTACK_KNOCKBACK = AttributeTypeImpl.get("attack_knockback");

  AttributeType ATTACK_SPEED = AttributeTypeImpl.get("attack_speed");

  AttributeType BLOCK_BREAK_SPEED = AttributeTypeImpl.get("block_break_speed");

  AttributeType BLOCK_INTERACTION_RANGE = AttributeTypeImpl.get("block_interaction_range");

  AttributeType BURNING_TIME = AttributeTypeImpl.get("burning_time");

  AttributeType CAMERA_DISTANCE = AttributeTypeImpl.get("camera_distance");

  AttributeType ENTITY_INTERACTION_RANGE = AttributeTypeImpl.get("entity_interaction_range");

  AttributeType EXPLOSION_KNOCKBACK_RESISTANCE = AttributeTypeImpl.get("explosion_knockback_resistance");

  AttributeType FALL_DAMAGE_MULTIPLIER = AttributeTypeImpl.get("fall_damage_multiplier");

  AttributeType FLYING_SPEED = AttributeTypeImpl.get("flying_speed");

  AttributeType FOLLOW_RANGE = AttributeTypeImpl.get("follow_range");

  AttributeType GRAVITY = AttributeTypeImpl.get("gravity");

  AttributeType JUMP_STRENGTH = AttributeTypeImpl.get("jump_strength");

  AttributeType KNOCKBACK_RESISTANCE = AttributeTypeImpl.get("knockback_resistance");

  AttributeType LUCK = AttributeTypeImpl.get("luck");

  AttributeType MAX_ABSORPTION = AttributeTypeImpl.get("max_absorption");

  AttributeType MAX_HEALTH = AttributeTypeImpl.get("max_health");

  AttributeType MINING_EFFICIENCY = AttributeTypeImpl.get("mining_efficiency");

  AttributeType MOVEMENT_EFFICIENCY = AttributeTypeImpl.get("movement_efficiency");

  AttributeType MOVEMENT_SPEED = AttributeTypeImpl.get("movement_speed");

  AttributeType OXYGEN_BONUS = AttributeTypeImpl.get("oxygen_bonus");

  AttributeType SAFE_FALL_DISTANCE = AttributeTypeImpl.get("safe_fall_distance");

  AttributeType SCALE = AttributeTypeImpl.get("scale");

  AttributeType SNEAKING_SPEED = AttributeTypeImpl.get("sneaking_speed");

  AttributeType SPAWN_REINFORCEMENTS = AttributeTypeImpl.get("spawn_reinforcements");

  AttributeType STEP_HEIGHT = AttributeTypeImpl.get("step_height");

  AttributeType SUBMERGED_MINING_SPEED = AttributeTypeImpl.get("submerged_mining_speed");

  AttributeType SWEEPING_DAMAGE_RATIO = AttributeTypeImpl.get("sweeping_damage_ratio");

  AttributeType TEMPT_RANGE = AttributeTypeImpl.get("tempt_range");

  AttributeType WATER_MOVEMENT_EFFICIENCY = AttributeTypeImpl.get("water_movement_efficiency");

  AttributeType WAYPOINT_RECEIVE_RANGE = AttributeTypeImpl.get("waypoint_receive_range");

  AttributeType WAYPOINT_TRANSMIT_RANGE = AttributeTypeImpl.get("waypoint_transmit_range");
}
