package me.moros.bending.api.platform.entity;

/**
 * Code autogenerated, do not edit! v1.19.2
 */
@SuppressWarnings("unused")
interface EntityTypes {
  EntityType ALLAY = EntityTypeImpl.get("allay");

  EntityType AREA_EFFECT_CLOUD = EntityTypeImpl.get("area_effect_cloud");

  EntityType ARMOR_STAND = EntityTypeImpl.get("armor_stand");

  EntityType ARROW = EntityTypeImpl.get("arrow");

  EntityType AXOLOTL = EntityTypeImpl.get("axolotl");

  EntityType BAT = EntityTypeImpl.get("bat");

  EntityType BEE = EntityTypeImpl.get("bee");

  EntityType BLAZE = EntityTypeImpl.get("blaze");

  EntityType BOAT = EntityTypeImpl.get("boat");

  EntityType CHEST_BOAT = EntityTypeImpl.get("chest_boat");

  EntityType CAT = EntityTypeImpl.get("cat");

  EntityType CAVE_SPIDER = EntityTypeImpl.get("cave_spider");

  EntityType CHICKEN = EntityTypeImpl.get("chicken");

  EntityType COD = EntityTypeImpl.get("cod");

  EntityType COW = EntityTypeImpl.get("cow");

  EntityType CREEPER = EntityTypeImpl.get("creeper");

  EntityType DOLPHIN = EntityTypeImpl.get("dolphin");

  EntityType DONKEY = EntityTypeImpl.get("donkey");

  EntityType DRAGON_FIREBALL = EntityTypeImpl.get("dragon_fireball");

  EntityType DROWNED = EntityTypeImpl.get("drowned");

  EntityType ELDER_GUARDIAN = EntityTypeImpl.get("elder_guardian");

  EntityType END_CRYSTAL = EntityTypeImpl.get("end_crystal");

  EntityType ENDER_DRAGON = EntityTypeImpl.get("ender_dragon");

  EntityType ENDERMAN = EntityTypeImpl.get("enderman");

  EntityType ENDERMITE = EntityTypeImpl.get("endermite");

  EntityType EVOKER = EntityTypeImpl.get("evoker");

  EntityType EVOKER_FANGS = EntityTypeImpl.get("evoker_fangs");

  EntityType EXPERIENCE_ORB = EntityTypeImpl.get("experience_orb");

  EntityType EYE_OF_ENDER = EntityTypeImpl.get("eye_of_ender");

  EntityType FALLING_BLOCK = EntityTypeImpl.get("falling_block");

  EntityType FIREWORK_ROCKET = EntityTypeImpl.get("firework_rocket");

  EntityType FOX = EntityTypeImpl.get("fox");

  EntityType FROG = EntityTypeImpl.get("frog");

  EntityType GHAST = EntityTypeImpl.get("ghast");

  EntityType GIANT = EntityTypeImpl.get("giant");

  EntityType GLOW_ITEM_FRAME = EntityTypeImpl.get("glow_item_frame");

  EntityType GLOW_SQUID = EntityTypeImpl.get("glow_squid");

  EntityType GOAT = EntityTypeImpl.get("goat");

  EntityType GUARDIAN = EntityTypeImpl.get("guardian");

  EntityType HOGLIN = EntityTypeImpl.get("hoglin");

  EntityType HORSE = EntityTypeImpl.get("horse");

  EntityType HUSK = EntityTypeImpl.get("husk");

  EntityType ILLUSIONER = EntityTypeImpl.get("illusioner");

  EntityType IRON_GOLEM = EntityTypeImpl.get("iron_golem");

  EntityType ITEM = EntityTypeImpl.get("item");

  EntityType ITEM_FRAME = EntityTypeImpl.get("item_frame");

  EntityType FIREBALL = EntityTypeImpl.get("fireball");

  EntityType LEASH_KNOT = EntityTypeImpl.get("leash_knot");

  EntityType LIGHTNING_BOLT = EntityTypeImpl.get("lightning_bolt");

  EntityType LLAMA = EntityTypeImpl.get("llama");

  EntityType LLAMA_SPIT = EntityTypeImpl.get("llama_spit");

  EntityType MAGMA_CUBE = EntityTypeImpl.get("magma_cube");

  EntityType MARKER = EntityTypeImpl.get("marker");

  EntityType MINECART = EntityTypeImpl.get("minecart");

  EntityType CHEST_MINECART = EntityTypeImpl.get("chest_minecart");

  EntityType COMMAND_BLOCK_MINECART = EntityTypeImpl.get("command_block_minecart");

  EntityType FURNACE_MINECART = EntityTypeImpl.get("furnace_minecart");

  EntityType HOPPER_MINECART = EntityTypeImpl.get("hopper_minecart");

  EntityType SPAWNER_MINECART = EntityTypeImpl.get("spawner_minecart");

  EntityType TNT_MINECART = EntityTypeImpl.get("tnt_minecart");

  EntityType MULE = EntityTypeImpl.get("mule");

  EntityType MOOSHROOM = EntityTypeImpl.get("mooshroom");

  EntityType OCELOT = EntityTypeImpl.get("ocelot");

  EntityType PAINTING = EntityTypeImpl.get("painting");

  EntityType PANDA = EntityTypeImpl.get("panda");

  EntityType PARROT = EntityTypeImpl.get("parrot");

  EntityType PHANTOM = EntityTypeImpl.get("phantom");

  EntityType PIG = EntityTypeImpl.get("pig");

  EntityType PIGLIN = EntityTypeImpl.get("piglin");

  EntityType PIGLIN_BRUTE = EntityTypeImpl.get("piglin_brute");

  EntityType PILLAGER = EntityTypeImpl.get("pillager");

  EntityType POLAR_BEAR = EntityTypeImpl.get("polar_bear");

  EntityType TNT = EntityTypeImpl.get("tnt");

  EntityType PUFFERFISH = EntityTypeImpl.get("pufferfish");

  EntityType RABBIT = EntityTypeImpl.get("rabbit");

  EntityType RAVAGER = EntityTypeImpl.get("ravager");

  EntityType SALMON = EntityTypeImpl.get("salmon");

  EntityType SHEEP = EntityTypeImpl.get("sheep");

  EntityType SHULKER = EntityTypeImpl.get("shulker");

  EntityType SHULKER_BULLET = EntityTypeImpl.get("shulker_bullet");

  EntityType SILVERFISH = EntityTypeImpl.get("silverfish");

  EntityType SKELETON = EntityTypeImpl.get("skeleton");

  EntityType SKELETON_HORSE = EntityTypeImpl.get("skeleton_horse");

  EntityType SLIME = EntityTypeImpl.get("slime");

  EntityType SMALL_FIREBALL = EntityTypeImpl.get("small_fireball");

  EntityType SNOW_GOLEM = EntityTypeImpl.get("snow_golem");

  EntityType SNOWBALL = EntityTypeImpl.get("snowball");

  EntityType SPECTRAL_ARROW = EntityTypeImpl.get("spectral_arrow");

  EntityType SPIDER = EntityTypeImpl.get("spider");

  EntityType SQUID = EntityTypeImpl.get("squid");

  EntityType STRAY = EntityTypeImpl.get("stray");

  EntityType STRIDER = EntityTypeImpl.get("strider");

  EntityType TADPOLE = EntityTypeImpl.get("tadpole");

  EntityType EGG = EntityTypeImpl.get("egg");

  EntityType ENDER_PEARL = EntityTypeImpl.get("ender_pearl");

  EntityType EXPERIENCE_BOTTLE = EntityTypeImpl.get("experience_bottle");

  EntityType POTION = EntityTypeImpl.get("potion");

  EntityType TRIDENT = EntityTypeImpl.get("trident");

  EntityType TRADER_LLAMA = EntityTypeImpl.get("trader_llama");

  EntityType TROPICAL_FISH = EntityTypeImpl.get("tropical_fish");

  EntityType TURTLE = EntityTypeImpl.get("turtle");

  EntityType VEX = EntityTypeImpl.get("vex");

  EntityType VILLAGER = EntityTypeImpl.get("villager");

  EntityType VINDICATOR = EntityTypeImpl.get("vindicator");

  EntityType WANDERING_TRADER = EntityTypeImpl.get("wandering_trader");

  EntityType WARDEN = EntityTypeImpl.get("warden");

  EntityType WITCH = EntityTypeImpl.get("witch");

  EntityType WITHER = EntityTypeImpl.get("wither");

  EntityType WITHER_SKELETON = EntityTypeImpl.get("wither_skeleton");

  EntityType WITHER_SKULL = EntityTypeImpl.get("wither_skull");

  EntityType WOLF = EntityTypeImpl.get("wolf");

  EntityType ZOGLIN = EntityTypeImpl.get("zoglin");

  EntityType ZOMBIE = EntityTypeImpl.get("zombie");

  EntityType ZOMBIE_HORSE = EntityTypeImpl.get("zombie_horse");

  EntityType ZOMBIE_VILLAGER = EntityTypeImpl.get("zombie_villager");

  EntityType ZOMBIFIED_PIGLIN = EntityTypeImpl.get("zombified_piglin");

  EntityType PLAYER = EntityTypeImpl.get("player");

  EntityType FISHING_BOBBER = EntityTypeImpl.get("fishing_bobber");
}
