package me.moros.bending.api.platform.entity;

/**
 * Code autogenerated, do not edit! v1.21.8
 */
@SuppressWarnings("unused")
interface Tags {
  EntityTypeTag AQUATIC = TagImpl.get("aquatic");

  EntityTypeTag ARROWS = TagImpl.get("arrows");

  EntityTypeTag ARTHROPOD = TagImpl.get("arthropod");

  EntityTypeTag AXOLOTL_ALWAYS_HOSTILES = TagImpl.get("axolotl_always_hostiles");

  EntityTypeTag AXOLOTL_HUNT_TARGETS = TagImpl.get("axolotl_hunt_targets");

  EntityTypeTag BEEHIVE_INHABITORS = TagImpl.get("beehive_inhabitors");

  EntityTypeTag BOAT = TagImpl.get("boat");

  EntityTypeTag CAN_BREATHE_UNDER_WATER = TagImpl.get("can_breathe_under_water");

  EntityTypeTag CAN_EQUIP_HARNESS = TagImpl.get("can_equip_harness");

  EntityTypeTag CAN_EQUIP_SADDLE = TagImpl.get("can_equip_saddle");

  EntityTypeTag CAN_TURN_IN_BOATS = TagImpl.get("can_turn_in_boats");

  EntityTypeTag CAN_WEAR_HORSE_ARMOR = TagImpl.get("can_wear_horse_armor");

  EntityTypeTag DEFLECTS_PROJECTILES = TagImpl.get("deflects_projectiles");

  EntityTypeTag DISMOUNTS_UNDERWATER = TagImpl.get("dismounts_underwater");

  EntityTypeTag FALL_DAMAGE_IMMUNE = TagImpl.get("fall_damage_immune");

  EntityTypeTag FOLLOWABLE_FRIENDLY_MOBS = TagImpl.get("followable_friendly_mobs");

  EntityTypeTag FREEZE_HURTS_EXTRA_TYPES = TagImpl.get("freeze_hurts_extra_types");

  EntityTypeTag FREEZE_IMMUNE_ENTITY_TYPES = TagImpl.get("freeze_immune_entity_types");

  EntityTypeTag FROG_FOOD = TagImpl.get("frog_food");

  EntityTypeTag IGNORES_POISON_AND_REGEN = TagImpl.get("ignores_poison_and_regen");

  EntityTypeTag ILLAGER = TagImpl.get("illager");

  EntityTypeTag ILLAGER_FRIENDS = TagImpl.get("illager_friends");

  EntityTypeTag IMMUNE_TO_INFESTED = TagImpl.get("immune_to_infested");

  EntityTypeTag IMMUNE_TO_OOZING = TagImpl.get("immune_to_oozing");

  EntityTypeTag IMPACT_PROJECTILES = TagImpl.get("impact_projectiles");

  EntityTypeTag INVERTED_HEALING_AND_HARM = TagImpl.get("inverted_healing_and_harm");

  EntityTypeTag NO_ANGER_FROM_WIND_CHARGE = TagImpl.get("no_anger_from_wind_charge");

  EntityTypeTag NON_CONTROLLING_RIDER = TagImpl.get("non_controlling_rider");

  EntityTypeTag NOT_SCARY_FOR_PUFFERFISH = TagImpl.get("not_scary_for_pufferfish");

  EntityTypeTag POWDER_SNOW_WALKABLE_MOBS = TagImpl.get("powder_snow_walkable_mobs");

  EntityTypeTag RAIDERS = TagImpl.get("raiders");

  EntityTypeTag REDIRECTABLE_PROJECTILE = TagImpl.get("redirectable_projectile");

  EntityTypeTag SENSITIVE_TO_BANE_OF_ARTHROPODS = TagImpl.get("sensitive_to_bane_of_arthropods");

  EntityTypeTag SENSITIVE_TO_IMPALING = TagImpl.get("sensitive_to_impaling");

  EntityTypeTag SENSITIVE_TO_SMITE = TagImpl.get("sensitive_to_smite");

  EntityTypeTag SKELETONS = TagImpl.get("skeletons");

  EntityTypeTag UNDEAD = TagImpl.get("undead");

  EntityTypeTag WITHER_FRIENDS = TagImpl.get("wither_friends");

  EntityTypeTag ZOMBIES = TagImpl.get("zombies");
}
