package me.moros.bending.api.platform.particle;

/**
 * Code autogenerated, do not edit! v1.19.4
 */
@SuppressWarnings("unused")
interface Particles {
  Particle AMBIENT_ENTITY_EFFECT = ParticleImpl.get("ambient_entity_effect");

  Particle ANGRY_VILLAGER = ParticleImpl.get("angry_villager");

  Particle ASH = ParticleImpl.get("ash");

  Particle BLOCK = ParticleImpl.get("block");

  Particle BLOCK_MARKER = ParticleImpl.get("block_marker");

  Particle BUBBLE = ParticleImpl.get("bubble");

  Particle BUBBLE_COLUMN_UP = ParticleImpl.get("bubble_column_up");

  Particle BUBBLE_POP = ParticleImpl.get("bubble_pop");

  Particle CAMPFIRE_COSY_SMOKE = ParticleImpl.get("campfire_cosy_smoke");

  Particle CAMPFIRE_SIGNAL_SMOKE = ParticleImpl.get("campfire_signal_smoke");

  Particle CLOUD = ParticleImpl.get("cloud");

  Particle COMPOSTER = ParticleImpl.get("composter");

  Particle CRIMSON_SPORE = ParticleImpl.get("crimson_spore");

  Particle CRIT = ParticleImpl.get("crit");

  Particle CURRENT_DOWN = ParticleImpl.get("current_down");

  Particle DAMAGE_INDICATOR = ParticleImpl.get("damage_indicator");

  Particle DOLPHIN = ParticleImpl.get("dolphin");

  Particle DRAGON_BREATH = ParticleImpl.get("dragon_breath");

  Particle DRIPPING_CHERRY_LEAVES = ParticleImpl.get("dripping_cherry_leaves");

  Particle DRIPPING_DRIPSTONE_LAVA = ParticleImpl.get("dripping_dripstone_lava");

  Particle DRIPPING_DRIPSTONE_WATER = ParticleImpl.get("dripping_dripstone_water");

  Particle DRIPPING_HONEY = ParticleImpl.get("dripping_honey");

  Particle DRIPPING_LAVA = ParticleImpl.get("dripping_lava");

  Particle DRIPPING_OBSIDIAN_TEAR = ParticleImpl.get("dripping_obsidian_tear");

  Particle DRIPPING_WATER = ParticleImpl.get("dripping_water");

  Particle DUST = ParticleImpl.get("dust");

  Particle DUST_COLOR_TRANSITION = ParticleImpl.get("dust_color_transition");

  Particle EFFECT = ParticleImpl.get("effect");

  Particle ELDER_GUARDIAN = ParticleImpl.get("elder_guardian");

  Particle ELECTRIC_SPARK = ParticleImpl.get("electric_spark");

  Particle ENCHANT = ParticleImpl.get("enchant");

  Particle ENCHANTED_HIT = ParticleImpl.get("enchanted_hit");

  Particle END_ROD = ParticleImpl.get("end_rod");

  Particle ENTITY_EFFECT = ParticleImpl.get("entity_effect");

  Particle EXPLOSION = ParticleImpl.get("explosion");

  Particle EXPLOSION_EMITTER = ParticleImpl.get("explosion_emitter");

  Particle FALLING_CHERRY_LEAVES = ParticleImpl.get("falling_cherry_leaves");

  Particle FALLING_DRIPSTONE_LAVA = ParticleImpl.get("falling_dripstone_lava");

  Particle FALLING_DRIPSTONE_WATER = ParticleImpl.get("falling_dripstone_water");

  Particle FALLING_DUST = ParticleImpl.get("falling_dust");

  Particle FALLING_HONEY = ParticleImpl.get("falling_honey");

  Particle FALLING_LAVA = ParticleImpl.get("falling_lava");

  Particle FALLING_NECTAR = ParticleImpl.get("falling_nectar");

  Particle FALLING_OBSIDIAN_TEAR = ParticleImpl.get("falling_obsidian_tear");

  Particle FALLING_SPORE_BLOSSOM = ParticleImpl.get("falling_spore_blossom");

  Particle FALLING_WATER = ParticleImpl.get("falling_water");

  Particle FIREWORK = ParticleImpl.get("firework");

  Particle FISHING = ParticleImpl.get("fishing");

  Particle FLAME = ParticleImpl.get("flame");

  Particle FLASH = ParticleImpl.get("flash");

  Particle GLOW = ParticleImpl.get("glow");

  Particle GLOW_SQUID_INK = ParticleImpl.get("glow_squid_ink");

  Particle HAPPY_VILLAGER = ParticleImpl.get("happy_villager");

  Particle HEART = ParticleImpl.get("heart");

  Particle INSTANT_EFFECT = ParticleImpl.get("instant_effect");

  Particle ITEM = ParticleImpl.get("item");

  Particle ITEM_SLIME = ParticleImpl.get("item_slime");

  Particle ITEM_SNOWBALL = ParticleImpl.get("item_snowball");

  Particle LANDING_CHERRY_LEAVES = ParticleImpl.get("landing_cherry_leaves");

  Particle LANDING_HONEY = ParticleImpl.get("landing_honey");

  Particle LANDING_LAVA = ParticleImpl.get("landing_lava");

  Particle LANDING_OBSIDIAN_TEAR = ParticleImpl.get("landing_obsidian_tear");

  Particle LARGE_SMOKE = ParticleImpl.get("large_smoke");

  Particle LAVA = ParticleImpl.get("lava");

  Particle MYCELIUM = ParticleImpl.get("mycelium");

  Particle NAUTILUS = ParticleImpl.get("nautilus");

  Particle NOTE = ParticleImpl.get("note");

  Particle POOF = ParticleImpl.get("poof");

  Particle PORTAL = ParticleImpl.get("portal");

  Particle RAIN = ParticleImpl.get("rain");

  Particle REVERSE_PORTAL = ParticleImpl.get("reverse_portal");

  Particle SCRAPE = ParticleImpl.get("scrape");

  Particle SCULK_CHARGE = ParticleImpl.get("sculk_charge");

  Particle SCULK_CHARGE_POP = ParticleImpl.get("sculk_charge_pop");

  Particle SCULK_SOUL = ParticleImpl.get("sculk_soul");

  Particle SHRIEK = ParticleImpl.get("shriek");

  Particle SMALL_FLAME = ParticleImpl.get("small_flame");

  Particle SMOKE = ParticleImpl.get("smoke");

  Particle SNEEZE = ParticleImpl.get("sneeze");

  Particle SNOWFLAKE = ParticleImpl.get("snowflake");

  Particle SONIC_BOOM = ParticleImpl.get("sonic_boom");

  Particle SOUL = ParticleImpl.get("soul");

  Particle SOUL_FIRE_FLAME = ParticleImpl.get("soul_fire_flame");

  Particle SPIT = ParticleImpl.get("spit");

  Particle SPLASH = ParticleImpl.get("splash");

  Particle SPORE_BLOSSOM_AIR = ParticleImpl.get("spore_blossom_air");

  Particle SQUID_INK = ParticleImpl.get("squid_ink");

  Particle SWEEP_ATTACK = ParticleImpl.get("sweep_attack");

  Particle TOTEM_OF_UNDYING = ParticleImpl.get("totem_of_undying");

  Particle UNDERWATER = ParticleImpl.get("underwater");

  Particle VIBRATION = ParticleImpl.get("vibration");

  Particle WARPED_SPORE = ParticleImpl.get("warped_spore");

  Particle WAX_OFF = ParticleImpl.get("wax_off");

  Particle WAX_ON = ParticleImpl.get("wax_on");

  Particle WHITE_ASH = ParticleImpl.get("white_ash");

  Particle WITCH = ParticleImpl.get("witch");
}
