package me.moros.bending.api.platform.item;

/**
 * Code autogenerated, do not edit! v1.21.9
 */
@SuppressWarnings("unused")
interface Items {
  Item ACACIA_BOAT = ItemImpl.get("acacia_boat");

  Item ACACIA_BUTTON = ItemImpl.get("acacia_button");

  Item ACACIA_CHEST_BOAT = ItemImpl.get("acacia_chest_boat");

  Item ACACIA_DOOR = ItemImpl.get("acacia_door");

  Item ACACIA_FENCE = ItemImpl.get("acacia_fence");

  Item ACACIA_FENCE_GATE = ItemImpl.get("acacia_fence_gate");

  Item ACACIA_HANGING_SIGN = ItemImpl.get("acacia_hanging_sign");

  Item ACACIA_LEAVES = ItemImpl.get("acacia_leaves");

  Item ACACIA_LOG = ItemImpl.get("acacia_log");

  Item ACACIA_PLANKS = ItemImpl.get("acacia_planks");

  Item ACACIA_PRESSURE_PLATE = ItemImpl.get("acacia_pressure_plate");

  Item ACACIA_SAPLING = ItemImpl.get("acacia_sapling");

  Item ACACIA_SHELF = ItemImpl.get("acacia_shelf");

  Item ACACIA_SIGN = ItemImpl.get("acacia_sign");

  Item ACACIA_SLAB = ItemImpl.get("acacia_slab");

  Item ACACIA_STAIRS = ItemImpl.get("acacia_stairs");

  Item ACACIA_TRAPDOOR = ItemImpl.get("acacia_trapdoor");

  Item ACACIA_WOOD = ItemImpl.get("acacia_wood");

  Item ACTIVATOR_RAIL = ItemImpl.get("activator_rail");

  Item AIR = ItemImpl.get("air");

  Item ALLAY_SPAWN_EGG = ItemImpl.get("allay_spawn_egg");

  Item ALLIUM = ItemImpl.get("allium");

  Item AMETHYST_BLOCK = ItemImpl.get("amethyst_block");

  Item AMETHYST_CLUSTER = ItemImpl.get("amethyst_cluster");

  Item AMETHYST_SHARD = ItemImpl.get("amethyst_shard");

  Item ANCIENT_DEBRIS = ItemImpl.get("ancient_debris");

  Item ANDESITE = ItemImpl.get("andesite");

  Item ANDESITE_SLAB = ItemImpl.get("andesite_slab");

  Item ANDESITE_STAIRS = ItemImpl.get("andesite_stairs");

  Item ANDESITE_WALL = ItemImpl.get("andesite_wall");

  Item ANGLER_POTTERY_SHERD = ItemImpl.get("angler_pottery_sherd");

  Item ANVIL = ItemImpl.get("anvil");

  Item APPLE = ItemImpl.get("apple");

  Item ARCHER_POTTERY_SHERD = ItemImpl.get("archer_pottery_sherd");

  Item ARMADILLO_SCUTE = ItemImpl.get("armadillo_scute");

  Item ARMADILLO_SPAWN_EGG = ItemImpl.get("armadillo_spawn_egg");

  Item ARMOR_STAND = ItemImpl.get("armor_stand");

  Item ARMS_UP_POTTERY_SHERD = ItemImpl.get("arms_up_pottery_sherd");

  Item ARROW = ItemImpl.get("arrow");

  Item AXOLOTL_BUCKET = ItemImpl.get("axolotl_bucket");

  Item AXOLOTL_SPAWN_EGG = ItemImpl.get("axolotl_spawn_egg");

  Item AZALEA = ItemImpl.get("azalea");

  Item AZALEA_LEAVES = ItemImpl.get("azalea_leaves");

  Item AZURE_BLUET = ItemImpl.get("azure_bluet");

  Item BAKED_POTATO = ItemImpl.get("baked_potato");

  Item BAMBOO = ItemImpl.get("bamboo");

  Item BAMBOO_BLOCK = ItemImpl.get("bamboo_block");

  Item BAMBOO_BUTTON = ItemImpl.get("bamboo_button");

  Item BAMBOO_CHEST_RAFT = ItemImpl.get("bamboo_chest_raft");

  Item BAMBOO_DOOR = ItemImpl.get("bamboo_door");

  Item BAMBOO_FENCE = ItemImpl.get("bamboo_fence");

  Item BAMBOO_FENCE_GATE = ItemImpl.get("bamboo_fence_gate");

  Item BAMBOO_HANGING_SIGN = ItemImpl.get("bamboo_hanging_sign");

  Item BAMBOO_MOSAIC = ItemImpl.get("bamboo_mosaic");

  Item BAMBOO_MOSAIC_SLAB = ItemImpl.get("bamboo_mosaic_slab");

  Item BAMBOO_MOSAIC_STAIRS = ItemImpl.get("bamboo_mosaic_stairs");

  Item BAMBOO_PLANKS = ItemImpl.get("bamboo_planks");

  Item BAMBOO_PRESSURE_PLATE = ItemImpl.get("bamboo_pressure_plate");

  Item BAMBOO_RAFT = ItemImpl.get("bamboo_raft");

  Item BAMBOO_SHELF = ItemImpl.get("bamboo_shelf");

  Item BAMBOO_SIGN = ItemImpl.get("bamboo_sign");

  Item BAMBOO_SLAB = ItemImpl.get("bamboo_slab");

  Item BAMBOO_STAIRS = ItemImpl.get("bamboo_stairs");

  Item BAMBOO_TRAPDOOR = ItemImpl.get("bamboo_trapdoor");

  Item BARREL = ItemImpl.get("barrel");

  Item BARRIER = ItemImpl.get("barrier");

  Item BASALT = ItemImpl.get("basalt");

  Item BAT_SPAWN_EGG = ItemImpl.get("bat_spawn_egg");

  Item BEACON = ItemImpl.get("beacon");

  Item BEDROCK = ItemImpl.get("bedrock");

  Item BEE_NEST = ItemImpl.get("bee_nest");

  Item BEE_SPAWN_EGG = ItemImpl.get("bee_spawn_egg");

  Item BEEF = ItemImpl.get("beef");

  Item BEEHIVE = ItemImpl.get("beehive");

  Item BEETROOT = ItemImpl.get("beetroot");

  Item BEETROOT_SEEDS = ItemImpl.get("beetroot_seeds");

  Item BEETROOT_SOUP = ItemImpl.get("beetroot_soup");

  Item BELL = ItemImpl.get("bell");

  Item BIG_DRIPLEAF = ItemImpl.get("big_dripleaf");

  Item BIRCH_BOAT = ItemImpl.get("birch_boat");

  Item BIRCH_BUTTON = ItemImpl.get("birch_button");

  Item BIRCH_CHEST_BOAT = ItemImpl.get("birch_chest_boat");

  Item BIRCH_DOOR = ItemImpl.get("birch_door");

  Item BIRCH_FENCE = ItemImpl.get("birch_fence");

  Item BIRCH_FENCE_GATE = ItemImpl.get("birch_fence_gate");

  Item BIRCH_HANGING_SIGN = ItemImpl.get("birch_hanging_sign");

  Item BIRCH_LEAVES = ItemImpl.get("birch_leaves");

  Item BIRCH_LOG = ItemImpl.get("birch_log");

  Item BIRCH_PLANKS = ItemImpl.get("birch_planks");

  Item BIRCH_PRESSURE_PLATE = ItemImpl.get("birch_pressure_plate");

  Item BIRCH_SAPLING = ItemImpl.get("birch_sapling");

  Item BIRCH_SHELF = ItemImpl.get("birch_shelf");

  Item BIRCH_SIGN = ItemImpl.get("birch_sign");

  Item BIRCH_SLAB = ItemImpl.get("birch_slab");

  Item BIRCH_STAIRS = ItemImpl.get("birch_stairs");

  Item BIRCH_TRAPDOOR = ItemImpl.get("birch_trapdoor");

  Item BIRCH_WOOD = ItemImpl.get("birch_wood");

  Item BLACK_BANNER = ItemImpl.get("black_banner");

  Item BLACK_BED = ItemImpl.get("black_bed");

  Item BLACK_BUNDLE = ItemImpl.get("black_bundle");

  Item BLACK_CANDLE = ItemImpl.get("black_candle");

  Item BLACK_CARPET = ItemImpl.get("black_carpet");

  Item BLACK_CONCRETE = ItemImpl.get("black_concrete");

  Item BLACK_CONCRETE_POWDER = ItemImpl.get("black_concrete_powder");

  Item BLACK_DYE = ItemImpl.get("black_dye");

  Item BLACK_GLAZED_TERRACOTTA = ItemImpl.get("black_glazed_terracotta");

  Item BLACK_HARNESS = ItemImpl.get("black_harness");

  Item BLACK_SHULKER_BOX = ItemImpl.get("black_shulker_box");

  Item BLACK_STAINED_GLASS = ItemImpl.get("black_stained_glass");

  Item BLACK_STAINED_GLASS_PANE = ItemImpl.get("black_stained_glass_pane");

  Item BLACK_TERRACOTTA = ItemImpl.get("black_terracotta");

  Item BLACK_WOOL = ItemImpl.get("black_wool");

  Item BLACKSTONE = ItemImpl.get("blackstone");

  Item BLACKSTONE_SLAB = ItemImpl.get("blackstone_slab");

  Item BLACKSTONE_STAIRS = ItemImpl.get("blackstone_stairs");

  Item BLACKSTONE_WALL = ItemImpl.get("blackstone_wall");

  Item BLADE_POTTERY_SHERD = ItemImpl.get("blade_pottery_sherd");

  Item BLAST_FURNACE = ItemImpl.get("blast_furnace");

  Item BLAZE_POWDER = ItemImpl.get("blaze_powder");

  Item BLAZE_ROD = ItemImpl.get("blaze_rod");

  Item BLAZE_SPAWN_EGG = ItemImpl.get("blaze_spawn_egg");

  Item BLUE_BANNER = ItemImpl.get("blue_banner");

  Item BLUE_BED = ItemImpl.get("blue_bed");

  Item BLUE_BUNDLE = ItemImpl.get("blue_bundle");

  Item BLUE_CANDLE = ItemImpl.get("blue_candle");

  Item BLUE_CARPET = ItemImpl.get("blue_carpet");

  Item BLUE_CONCRETE = ItemImpl.get("blue_concrete");

  Item BLUE_CONCRETE_POWDER = ItemImpl.get("blue_concrete_powder");

  Item BLUE_DYE = ItemImpl.get("blue_dye");

  Item BLUE_EGG = ItemImpl.get("blue_egg");

  Item BLUE_GLAZED_TERRACOTTA = ItemImpl.get("blue_glazed_terracotta");

  Item BLUE_HARNESS = ItemImpl.get("blue_harness");

  Item BLUE_ICE = ItemImpl.get("blue_ice");

  Item BLUE_ORCHID = ItemImpl.get("blue_orchid");

  Item BLUE_SHULKER_BOX = ItemImpl.get("blue_shulker_box");

  Item BLUE_STAINED_GLASS = ItemImpl.get("blue_stained_glass");

  Item BLUE_STAINED_GLASS_PANE = ItemImpl.get("blue_stained_glass_pane");

  Item BLUE_TERRACOTTA = ItemImpl.get("blue_terracotta");

  Item BLUE_WOOL = ItemImpl.get("blue_wool");

  Item BOGGED_SPAWN_EGG = ItemImpl.get("bogged_spawn_egg");

  Item BOLT_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("bolt_armor_trim_smithing_template");

  Item BONE = ItemImpl.get("bone");

  Item BONE_BLOCK = ItemImpl.get("bone_block");

  Item BONE_MEAL = ItemImpl.get("bone_meal");

  Item BOOK = ItemImpl.get("book");

  Item BOOKSHELF = ItemImpl.get("bookshelf");

  Item BORDURE_INDENTED_BANNER_PATTERN = ItemImpl.get("bordure_indented_banner_pattern");

  Item BOW = ItemImpl.get("bow");

  Item BOWL = ItemImpl.get("bowl");

  Item BRAIN_CORAL = ItemImpl.get("brain_coral");

  Item BRAIN_CORAL_BLOCK = ItemImpl.get("brain_coral_block");

  Item BRAIN_CORAL_FAN = ItemImpl.get("brain_coral_fan");

  Item BREAD = ItemImpl.get("bread");

  Item BREEZE_ROD = ItemImpl.get("breeze_rod");

  Item BREEZE_SPAWN_EGG = ItemImpl.get("breeze_spawn_egg");

  Item BREWER_POTTERY_SHERD = ItemImpl.get("brewer_pottery_sherd");

  Item BREWING_STAND = ItemImpl.get("brewing_stand");

  Item BRICK = ItemImpl.get("brick");

  Item BRICK_SLAB = ItemImpl.get("brick_slab");

  Item BRICK_STAIRS = ItemImpl.get("brick_stairs");

  Item BRICK_WALL = ItemImpl.get("brick_wall");

  Item BRICKS = ItemImpl.get("bricks");

  Item BROWN_BANNER = ItemImpl.get("brown_banner");

  Item BROWN_BED = ItemImpl.get("brown_bed");

  Item BROWN_BUNDLE = ItemImpl.get("brown_bundle");

  Item BROWN_CANDLE = ItemImpl.get("brown_candle");

  Item BROWN_CARPET = ItemImpl.get("brown_carpet");

  Item BROWN_CONCRETE = ItemImpl.get("brown_concrete");

  Item BROWN_CONCRETE_POWDER = ItemImpl.get("brown_concrete_powder");

  Item BROWN_DYE = ItemImpl.get("brown_dye");

  Item BROWN_EGG = ItemImpl.get("brown_egg");

  Item BROWN_GLAZED_TERRACOTTA = ItemImpl.get("brown_glazed_terracotta");

  Item BROWN_HARNESS = ItemImpl.get("brown_harness");

  Item BROWN_MUSHROOM = ItemImpl.get("brown_mushroom");

  Item BROWN_MUSHROOM_BLOCK = ItemImpl.get("brown_mushroom_block");

  Item BROWN_SHULKER_BOX = ItemImpl.get("brown_shulker_box");

  Item BROWN_STAINED_GLASS = ItemImpl.get("brown_stained_glass");

  Item BROWN_STAINED_GLASS_PANE = ItemImpl.get("brown_stained_glass_pane");

  Item BROWN_TERRACOTTA = ItemImpl.get("brown_terracotta");

  Item BROWN_WOOL = ItemImpl.get("brown_wool");

  Item BRUSH = ItemImpl.get("brush");

  Item BUBBLE_CORAL = ItemImpl.get("bubble_coral");

  Item BUBBLE_CORAL_BLOCK = ItemImpl.get("bubble_coral_block");

  Item BUBBLE_CORAL_FAN = ItemImpl.get("bubble_coral_fan");

  Item BUCKET = ItemImpl.get("bucket");

  Item BUDDING_AMETHYST = ItemImpl.get("budding_amethyst");

  Item BUNDLE = ItemImpl.get("bundle");

  Item BURN_POTTERY_SHERD = ItemImpl.get("burn_pottery_sherd");

  Item BUSH = ItemImpl.get("bush");

  Item CACTUS = ItemImpl.get("cactus");

  Item CACTUS_FLOWER = ItemImpl.get("cactus_flower");

  Item CAKE = ItemImpl.get("cake");

  Item CALCITE = ItemImpl.get("calcite");

  Item CALIBRATED_SCULK_SENSOR = ItemImpl.get("calibrated_sculk_sensor");

  Item CAMEL_SPAWN_EGG = ItemImpl.get("camel_spawn_egg");

  Item CAMPFIRE = ItemImpl.get("campfire");

  Item CANDLE = ItemImpl.get("candle");

  Item CARROT = ItemImpl.get("carrot");

  Item CARROT_ON_A_STICK = ItemImpl.get("carrot_on_a_stick");

  Item CARTOGRAPHY_TABLE = ItemImpl.get("cartography_table");

  Item CARVED_PUMPKIN = ItemImpl.get("carved_pumpkin");

  Item CAT_SPAWN_EGG = ItemImpl.get("cat_spawn_egg");

  Item CAULDRON = ItemImpl.get("cauldron");

  Item CAVE_SPIDER_SPAWN_EGG = ItemImpl.get("cave_spider_spawn_egg");

  Item CHAIN_COMMAND_BLOCK = ItemImpl.get("chain_command_block");

  Item CHAINMAIL_BOOTS = ItemImpl.get("chainmail_boots");

  Item CHAINMAIL_CHESTPLATE = ItemImpl.get("chainmail_chestplate");

  Item CHAINMAIL_HELMET = ItemImpl.get("chainmail_helmet");

  Item CHAINMAIL_LEGGINGS = ItemImpl.get("chainmail_leggings");

  Item CHARCOAL = ItemImpl.get("charcoal");

  Item CHERRY_BOAT = ItemImpl.get("cherry_boat");

  Item CHERRY_BUTTON = ItemImpl.get("cherry_button");

  Item CHERRY_CHEST_BOAT = ItemImpl.get("cherry_chest_boat");

  Item CHERRY_DOOR = ItemImpl.get("cherry_door");

  Item CHERRY_FENCE = ItemImpl.get("cherry_fence");

  Item CHERRY_FENCE_GATE = ItemImpl.get("cherry_fence_gate");

  Item CHERRY_HANGING_SIGN = ItemImpl.get("cherry_hanging_sign");

  Item CHERRY_LEAVES = ItemImpl.get("cherry_leaves");

  Item CHERRY_LOG = ItemImpl.get("cherry_log");

  Item CHERRY_PLANKS = ItemImpl.get("cherry_planks");

  Item CHERRY_PRESSURE_PLATE = ItemImpl.get("cherry_pressure_plate");

  Item CHERRY_SAPLING = ItemImpl.get("cherry_sapling");

  Item CHERRY_SHELF = ItemImpl.get("cherry_shelf");

  Item CHERRY_SIGN = ItemImpl.get("cherry_sign");

  Item CHERRY_SLAB = ItemImpl.get("cherry_slab");

  Item CHERRY_STAIRS = ItemImpl.get("cherry_stairs");

  Item CHERRY_TRAPDOOR = ItemImpl.get("cherry_trapdoor");

  Item CHERRY_WOOD = ItemImpl.get("cherry_wood");

  Item CHEST = ItemImpl.get("chest");

  Item CHEST_MINECART = ItemImpl.get("chest_minecart");

  Item CHICKEN = ItemImpl.get("chicken");

  Item CHICKEN_SPAWN_EGG = ItemImpl.get("chicken_spawn_egg");

  Item CHIPPED_ANVIL = ItemImpl.get("chipped_anvil");

  Item CHISELED_BOOKSHELF = ItemImpl.get("chiseled_bookshelf");

  Item CHISELED_COPPER = ItemImpl.get("chiseled_copper");

  Item CHISELED_DEEPSLATE = ItemImpl.get("chiseled_deepslate");

  Item CHISELED_NETHER_BRICKS = ItemImpl.get("chiseled_nether_bricks");

  Item CHISELED_POLISHED_BLACKSTONE = ItemImpl.get("chiseled_polished_blackstone");

  Item CHISELED_QUARTZ_BLOCK = ItemImpl.get("chiseled_quartz_block");

  Item CHISELED_RED_SANDSTONE = ItemImpl.get("chiseled_red_sandstone");

  Item CHISELED_RESIN_BRICKS = ItemImpl.get("chiseled_resin_bricks");

  Item CHISELED_SANDSTONE = ItemImpl.get("chiseled_sandstone");

  Item CHISELED_STONE_BRICKS = ItemImpl.get("chiseled_stone_bricks");

  Item CHISELED_TUFF = ItemImpl.get("chiseled_tuff");

  Item CHISELED_TUFF_BRICKS = ItemImpl.get("chiseled_tuff_bricks");

  Item CHORUS_FLOWER = ItemImpl.get("chorus_flower");

  Item CHORUS_FRUIT = ItemImpl.get("chorus_fruit");

  Item CHORUS_PLANT = ItemImpl.get("chorus_plant");

  Item CLAY = ItemImpl.get("clay");

  Item CLAY_BALL = ItemImpl.get("clay_ball");

  Item CLOCK = ItemImpl.get("clock");

  Item CLOSED_EYEBLOSSOM = ItemImpl.get("closed_eyeblossom");

  Item COAL = ItemImpl.get("coal");

  Item COAL_BLOCK = ItemImpl.get("coal_block");

  Item COAL_ORE = ItemImpl.get("coal_ore");

  Item COARSE_DIRT = ItemImpl.get("coarse_dirt");

  Item COAST_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("coast_armor_trim_smithing_template");

  Item COBBLED_DEEPSLATE = ItemImpl.get("cobbled_deepslate");

  Item COBBLED_DEEPSLATE_SLAB = ItemImpl.get("cobbled_deepslate_slab");

  Item COBBLED_DEEPSLATE_STAIRS = ItemImpl.get("cobbled_deepslate_stairs");

  Item COBBLED_DEEPSLATE_WALL = ItemImpl.get("cobbled_deepslate_wall");

  Item COBBLESTONE = ItemImpl.get("cobblestone");

  Item COBBLESTONE_SLAB = ItemImpl.get("cobblestone_slab");

  Item COBBLESTONE_STAIRS = ItemImpl.get("cobblestone_stairs");

  Item COBBLESTONE_WALL = ItemImpl.get("cobblestone_wall");

  Item COBWEB = ItemImpl.get("cobweb");

  Item COCOA_BEANS = ItemImpl.get("cocoa_beans");

  Item COD = ItemImpl.get("cod");

  Item COD_BUCKET = ItemImpl.get("cod_bucket");

  Item COD_SPAWN_EGG = ItemImpl.get("cod_spawn_egg");

  Item COMMAND_BLOCK = ItemImpl.get("command_block");

  Item COMMAND_BLOCK_MINECART = ItemImpl.get("command_block_minecart");

  Item COMPARATOR = ItemImpl.get("comparator");

  Item COMPASS = ItemImpl.get("compass");

  Item COMPOSTER = ItemImpl.get("composter");

  Item CONDUIT = ItemImpl.get("conduit");

  Item COOKED_BEEF = ItemImpl.get("cooked_beef");

  Item COOKED_CHICKEN = ItemImpl.get("cooked_chicken");

  Item COOKED_COD = ItemImpl.get("cooked_cod");

  Item COOKED_MUTTON = ItemImpl.get("cooked_mutton");

  Item COOKED_PORKCHOP = ItemImpl.get("cooked_porkchop");

  Item COOKED_RABBIT = ItemImpl.get("cooked_rabbit");

  Item COOKED_SALMON = ItemImpl.get("cooked_salmon");

  Item COOKIE = ItemImpl.get("cookie");

  Item COPPER_AXE = ItemImpl.get("copper_axe");

  Item COPPER_BARS = ItemImpl.get("copper_bars");

  Item COPPER_BLOCK = ItemImpl.get("copper_block");

  Item COPPER_BOOTS = ItemImpl.get("copper_boots");

  Item COPPER_BULB = ItemImpl.get("copper_bulb");

  Item COPPER_CHAIN = ItemImpl.get("copper_chain");

  Item COPPER_CHEST = ItemImpl.get("copper_chest");

  Item COPPER_CHESTPLATE = ItemImpl.get("copper_chestplate");

  Item COPPER_DOOR = ItemImpl.get("copper_door");

  Item COPPER_GOLEM_SPAWN_EGG = ItemImpl.get("copper_golem_spawn_egg");

  Item COPPER_GOLEM_STATUE = ItemImpl.get("copper_golem_statue");

  Item COPPER_GRATE = ItemImpl.get("copper_grate");

  Item COPPER_HELMET = ItemImpl.get("copper_helmet");

  Item COPPER_HOE = ItemImpl.get("copper_hoe");

  Item COPPER_HORSE_ARMOR = ItemImpl.get("copper_horse_armor");

  Item COPPER_INGOT = ItemImpl.get("copper_ingot");

  Item COPPER_LANTERN = ItemImpl.get("copper_lantern");

  Item COPPER_LEGGINGS = ItemImpl.get("copper_leggings");

  Item COPPER_NUGGET = ItemImpl.get("copper_nugget");

  Item COPPER_ORE = ItemImpl.get("copper_ore");

  Item COPPER_PICKAXE = ItemImpl.get("copper_pickaxe");

  Item COPPER_SHOVEL = ItemImpl.get("copper_shovel");

  Item COPPER_SWORD = ItemImpl.get("copper_sword");

  Item COPPER_TORCH = ItemImpl.get("copper_torch");

  Item COPPER_TRAPDOOR = ItemImpl.get("copper_trapdoor");

  Item CORNFLOWER = ItemImpl.get("cornflower");

  Item COW_SPAWN_EGG = ItemImpl.get("cow_spawn_egg");

  Item CRACKED_DEEPSLATE_BRICKS = ItemImpl.get("cracked_deepslate_bricks");

  Item CRACKED_DEEPSLATE_TILES = ItemImpl.get("cracked_deepslate_tiles");

  Item CRACKED_NETHER_BRICKS = ItemImpl.get("cracked_nether_bricks");

  Item CRACKED_POLISHED_BLACKSTONE_BRICKS = ItemImpl.get("cracked_polished_blackstone_bricks");

  Item CRACKED_STONE_BRICKS = ItemImpl.get("cracked_stone_bricks");

  Item CRAFTER = ItemImpl.get("crafter");

  Item CRAFTING_TABLE = ItemImpl.get("crafting_table");

  Item CREAKING_HEART = ItemImpl.get("creaking_heart");

  Item CREAKING_SPAWN_EGG = ItemImpl.get("creaking_spawn_egg");

  Item CREEPER_BANNER_PATTERN = ItemImpl.get("creeper_banner_pattern");

  Item CREEPER_HEAD = ItemImpl.get("creeper_head");

  Item CREEPER_SPAWN_EGG = ItemImpl.get("creeper_spawn_egg");

  Item CRIMSON_BUTTON = ItemImpl.get("crimson_button");

  Item CRIMSON_DOOR = ItemImpl.get("crimson_door");

  Item CRIMSON_FENCE = ItemImpl.get("crimson_fence");

  Item CRIMSON_FENCE_GATE = ItemImpl.get("crimson_fence_gate");

  Item CRIMSON_FUNGUS = ItemImpl.get("crimson_fungus");

  Item CRIMSON_HANGING_SIGN = ItemImpl.get("crimson_hanging_sign");

  Item CRIMSON_HYPHAE = ItemImpl.get("crimson_hyphae");

  Item CRIMSON_NYLIUM = ItemImpl.get("crimson_nylium");

  Item CRIMSON_PLANKS = ItemImpl.get("crimson_planks");

  Item CRIMSON_PRESSURE_PLATE = ItemImpl.get("crimson_pressure_plate");

  Item CRIMSON_ROOTS = ItemImpl.get("crimson_roots");

  Item CRIMSON_SHELF = ItemImpl.get("crimson_shelf");

  Item CRIMSON_SIGN = ItemImpl.get("crimson_sign");

  Item CRIMSON_SLAB = ItemImpl.get("crimson_slab");

  Item CRIMSON_STAIRS = ItemImpl.get("crimson_stairs");

  Item CRIMSON_STEM = ItemImpl.get("crimson_stem");

  Item CRIMSON_TRAPDOOR = ItemImpl.get("crimson_trapdoor");

  Item CROSSBOW = ItemImpl.get("crossbow");

  Item CRYING_OBSIDIAN = ItemImpl.get("crying_obsidian");

  Item CUT_COPPER = ItemImpl.get("cut_copper");

  Item CUT_COPPER_SLAB = ItemImpl.get("cut_copper_slab");

  Item CUT_COPPER_STAIRS = ItemImpl.get("cut_copper_stairs");

  Item CUT_RED_SANDSTONE = ItemImpl.get("cut_red_sandstone");

  Item CUT_RED_SANDSTONE_SLAB = ItemImpl.get("cut_red_sandstone_slab");

  Item CUT_SANDSTONE = ItemImpl.get("cut_sandstone");

  Item CUT_SANDSTONE_SLAB = ItemImpl.get("cut_sandstone_slab");

  Item CYAN_BANNER = ItemImpl.get("cyan_banner");

  Item CYAN_BED = ItemImpl.get("cyan_bed");

  Item CYAN_BUNDLE = ItemImpl.get("cyan_bundle");

  Item CYAN_CANDLE = ItemImpl.get("cyan_candle");

  Item CYAN_CARPET = ItemImpl.get("cyan_carpet");

  Item CYAN_CONCRETE = ItemImpl.get("cyan_concrete");

  Item CYAN_CONCRETE_POWDER = ItemImpl.get("cyan_concrete_powder");

  Item CYAN_DYE = ItemImpl.get("cyan_dye");

  Item CYAN_GLAZED_TERRACOTTA = ItemImpl.get("cyan_glazed_terracotta");

  Item CYAN_HARNESS = ItemImpl.get("cyan_harness");

  Item CYAN_SHULKER_BOX = ItemImpl.get("cyan_shulker_box");

  Item CYAN_STAINED_GLASS = ItemImpl.get("cyan_stained_glass");

  Item CYAN_STAINED_GLASS_PANE = ItemImpl.get("cyan_stained_glass_pane");

  Item CYAN_TERRACOTTA = ItemImpl.get("cyan_terracotta");

  Item CYAN_WOOL = ItemImpl.get("cyan_wool");

  Item DAMAGED_ANVIL = ItemImpl.get("damaged_anvil");

  Item DANDELION = ItemImpl.get("dandelion");

  Item DANGER_POTTERY_SHERD = ItemImpl.get("danger_pottery_sherd");

  Item DARK_OAK_BOAT = ItemImpl.get("dark_oak_boat");

  Item DARK_OAK_BUTTON = ItemImpl.get("dark_oak_button");

  Item DARK_OAK_CHEST_BOAT = ItemImpl.get("dark_oak_chest_boat");

  Item DARK_OAK_DOOR = ItemImpl.get("dark_oak_door");

  Item DARK_OAK_FENCE = ItemImpl.get("dark_oak_fence");

  Item DARK_OAK_FENCE_GATE = ItemImpl.get("dark_oak_fence_gate");

  Item DARK_OAK_HANGING_SIGN = ItemImpl.get("dark_oak_hanging_sign");

  Item DARK_OAK_LEAVES = ItemImpl.get("dark_oak_leaves");

  Item DARK_OAK_LOG = ItemImpl.get("dark_oak_log");

  Item DARK_OAK_PLANKS = ItemImpl.get("dark_oak_planks");

  Item DARK_OAK_PRESSURE_PLATE = ItemImpl.get("dark_oak_pressure_plate");

  Item DARK_OAK_SAPLING = ItemImpl.get("dark_oak_sapling");

  Item DARK_OAK_SHELF = ItemImpl.get("dark_oak_shelf");

  Item DARK_OAK_SIGN = ItemImpl.get("dark_oak_sign");

  Item DARK_OAK_SLAB = ItemImpl.get("dark_oak_slab");

  Item DARK_OAK_STAIRS = ItemImpl.get("dark_oak_stairs");

  Item DARK_OAK_TRAPDOOR = ItemImpl.get("dark_oak_trapdoor");

  Item DARK_OAK_WOOD = ItemImpl.get("dark_oak_wood");

  Item DARK_PRISMARINE = ItemImpl.get("dark_prismarine");

  Item DARK_PRISMARINE_SLAB = ItemImpl.get("dark_prismarine_slab");

  Item DARK_PRISMARINE_STAIRS = ItemImpl.get("dark_prismarine_stairs");

  Item DAYLIGHT_DETECTOR = ItemImpl.get("daylight_detector");

  Item DEAD_BRAIN_CORAL = ItemImpl.get("dead_brain_coral");

  Item DEAD_BRAIN_CORAL_BLOCK = ItemImpl.get("dead_brain_coral_block");

  Item DEAD_BRAIN_CORAL_FAN = ItemImpl.get("dead_brain_coral_fan");

  Item DEAD_BUBBLE_CORAL = ItemImpl.get("dead_bubble_coral");

  Item DEAD_BUBBLE_CORAL_BLOCK = ItemImpl.get("dead_bubble_coral_block");

  Item DEAD_BUBBLE_CORAL_FAN = ItemImpl.get("dead_bubble_coral_fan");

  Item DEAD_BUSH = ItemImpl.get("dead_bush");

  Item DEAD_FIRE_CORAL = ItemImpl.get("dead_fire_coral");

  Item DEAD_FIRE_CORAL_BLOCK = ItemImpl.get("dead_fire_coral_block");

  Item DEAD_FIRE_CORAL_FAN = ItemImpl.get("dead_fire_coral_fan");

  Item DEAD_HORN_CORAL = ItemImpl.get("dead_horn_coral");

  Item DEAD_HORN_CORAL_BLOCK = ItemImpl.get("dead_horn_coral_block");

  Item DEAD_HORN_CORAL_FAN = ItemImpl.get("dead_horn_coral_fan");

  Item DEAD_TUBE_CORAL = ItemImpl.get("dead_tube_coral");

  Item DEAD_TUBE_CORAL_BLOCK = ItemImpl.get("dead_tube_coral_block");

  Item DEAD_TUBE_CORAL_FAN = ItemImpl.get("dead_tube_coral_fan");

  Item DEBUG_STICK = ItemImpl.get("debug_stick");

  Item DECORATED_POT = ItemImpl.get("decorated_pot");

  Item DEEPSLATE = ItemImpl.get("deepslate");

  Item DEEPSLATE_BRICK_SLAB = ItemImpl.get("deepslate_brick_slab");

  Item DEEPSLATE_BRICK_STAIRS = ItemImpl.get("deepslate_brick_stairs");

  Item DEEPSLATE_BRICK_WALL = ItemImpl.get("deepslate_brick_wall");

  Item DEEPSLATE_BRICKS = ItemImpl.get("deepslate_bricks");

  Item DEEPSLATE_COAL_ORE = ItemImpl.get("deepslate_coal_ore");

  Item DEEPSLATE_COPPER_ORE = ItemImpl.get("deepslate_copper_ore");

  Item DEEPSLATE_DIAMOND_ORE = ItemImpl.get("deepslate_diamond_ore");

  Item DEEPSLATE_EMERALD_ORE = ItemImpl.get("deepslate_emerald_ore");

  Item DEEPSLATE_GOLD_ORE = ItemImpl.get("deepslate_gold_ore");

  Item DEEPSLATE_IRON_ORE = ItemImpl.get("deepslate_iron_ore");

  Item DEEPSLATE_LAPIS_ORE = ItemImpl.get("deepslate_lapis_ore");

  Item DEEPSLATE_REDSTONE_ORE = ItemImpl.get("deepslate_redstone_ore");

  Item DEEPSLATE_TILE_SLAB = ItemImpl.get("deepslate_tile_slab");

  Item DEEPSLATE_TILE_STAIRS = ItemImpl.get("deepslate_tile_stairs");

  Item DEEPSLATE_TILE_WALL = ItemImpl.get("deepslate_tile_wall");

  Item DEEPSLATE_TILES = ItemImpl.get("deepslate_tiles");

  Item DETECTOR_RAIL = ItemImpl.get("detector_rail");

  Item DIAMOND = ItemImpl.get("diamond");

  Item DIAMOND_AXE = ItemImpl.get("diamond_axe");

  Item DIAMOND_BLOCK = ItemImpl.get("diamond_block");

  Item DIAMOND_BOOTS = ItemImpl.get("diamond_boots");

  Item DIAMOND_CHESTPLATE = ItemImpl.get("diamond_chestplate");

  Item DIAMOND_HELMET = ItemImpl.get("diamond_helmet");

  Item DIAMOND_HOE = ItemImpl.get("diamond_hoe");

  Item DIAMOND_HORSE_ARMOR = ItemImpl.get("diamond_horse_armor");

  Item DIAMOND_LEGGINGS = ItemImpl.get("diamond_leggings");

  Item DIAMOND_ORE = ItemImpl.get("diamond_ore");

  Item DIAMOND_PICKAXE = ItemImpl.get("diamond_pickaxe");

  Item DIAMOND_SHOVEL = ItemImpl.get("diamond_shovel");

  Item DIAMOND_SWORD = ItemImpl.get("diamond_sword");

  Item DIORITE = ItemImpl.get("diorite");

  Item DIORITE_SLAB = ItemImpl.get("diorite_slab");

  Item DIORITE_STAIRS = ItemImpl.get("diorite_stairs");

  Item DIORITE_WALL = ItemImpl.get("diorite_wall");

  Item DIRT = ItemImpl.get("dirt");

  Item DIRT_PATH = ItemImpl.get("dirt_path");

  Item DISC_FRAGMENT_5 = ItemImpl.get("disc_fragment_5");

  Item DISPENSER = ItemImpl.get("dispenser");

  Item DOLPHIN_SPAWN_EGG = ItemImpl.get("dolphin_spawn_egg");

  Item DONKEY_SPAWN_EGG = ItemImpl.get("donkey_spawn_egg");

  Item DRAGON_BREATH = ItemImpl.get("dragon_breath");

  Item DRAGON_EGG = ItemImpl.get("dragon_egg");

  Item DRAGON_HEAD = ItemImpl.get("dragon_head");

  Item DRIED_GHAST = ItemImpl.get("dried_ghast");

  Item DRIED_KELP = ItemImpl.get("dried_kelp");

  Item DRIED_KELP_BLOCK = ItemImpl.get("dried_kelp_block");

  Item DRIPSTONE_BLOCK = ItemImpl.get("dripstone_block");

  Item DROPPER = ItemImpl.get("dropper");

  Item DROWNED_SPAWN_EGG = ItemImpl.get("drowned_spawn_egg");

  Item DUNE_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("dune_armor_trim_smithing_template");

  Item ECHO_SHARD = ItemImpl.get("echo_shard");

  Item EGG = ItemImpl.get("egg");

  Item ELDER_GUARDIAN_SPAWN_EGG = ItemImpl.get("elder_guardian_spawn_egg");

  Item ELYTRA = ItemImpl.get("elytra");

  Item EMERALD = ItemImpl.get("emerald");

  Item EMERALD_BLOCK = ItemImpl.get("emerald_block");

  Item EMERALD_ORE = ItemImpl.get("emerald_ore");

  Item ENCHANTED_BOOK = ItemImpl.get("enchanted_book");

  Item ENCHANTED_GOLDEN_APPLE = ItemImpl.get("enchanted_golden_apple");

  Item ENCHANTING_TABLE = ItemImpl.get("enchanting_table");

  Item END_CRYSTAL = ItemImpl.get("end_crystal");

  Item END_PORTAL_FRAME = ItemImpl.get("end_portal_frame");

  Item END_ROD = ItemImpl.get("end_rod");

  Item END_STONE = ItemImpl.get("end_stone");

  Item END_STONE_BRICK_SLAB = ItemImpl.get("end_stone_brick_slab");

  Item END_STONE_BRICK_STAIRS = ItemImpl.get("end_stone_brick_stairs");

  Item END_STONE_BRICK_WALL = ItemImpl.get("end_stone_brick_wall");

  Item END_STONE_BRICKS = ItemImpl.get("end_stone_bricks");

  Item ENDER_CHEST = ItemImpl.get("ender_chest");

  Item ENDER_DRAGON_SPAWN_EGG = ItemImpl.get("ender_dragon_spawn_egg");

  Item ENDER_EYE = ItemImpl.get("ender_eye");

  Item ENDER_PEARL = ItemImpl.get("ender_pearl");

  Item ENDERMAN_SPAWN_EGG = ItemImpl.get("enderman_spawn_egg");

  Item ENDERMITE_SPAWN_EGG = ItemImpl.get("endermite_spawn_egg");

  Item EVOKER_SPAWN_EGG = ItemImpl.get("evoker_spawn_egg");

  Item EXPERIENCE_BOTTLE = ItemImpl.get("experience_bottle");

  Item EXPLORER_POTTERY_SHERD = ItemImpl.get("explorer_pottery_sherd");

  Item EXPOSED_CHISELED_COPPER = ItemImpl.get("exposed_chiseled_copper");

  Item EXPOSED_COPPER = ItemImpl.get("exposed_copper");

  Item EXPOSED_COPPER_BARS = ItemImpl.get("exposed_copper_bars");

  Item EXPOSED_COPPER_BULB = ItemImpl.get("exposed_copper_bulb");

  Item EXPOSED_COPPER_CHAIN = ItemImpl.get("exposed_copper_chain");

  Item EXPOSED_COPPER_CHEST = ItemImpl.get("exposed_copper_chest");

  Item EXPOSED_COPPER_DOOR = ItemImpl.get("exposed_copper_door");

  Item EXPOSED_COPPER_GOLEM_STATUE = ItemImpl.get("exposed_copper_golem_statue");

  Item EXPOSED_COPPER_GRATE = ItemImpl.get("exposed_copper_grate");

  Item EXPOSED_COPPER_LANTERN = ItemImpl.get("exposed_copper_lantern");

  Item EXPOSED_COPPER_TRAPDOOR = ItemImpl.get("exposed_copper_trapdoor");

  Item EXPOSED_CUT_COPPER = ItemImpl.get("exposed_cut_copper");

  Item EXPOSED_CUT_COPPER_SLAB = ItemImpl.get("exposed_cut_copper_slab");

  Item EXPOSED_CUT_COPPER_STAIRS = ItemImpl.get("exposed_cut_copper_stairs");

  Item EXPOSED_LIGHTNING_ROD = ItemImpl.get("exposed_lightning_rod");

  Item EYE_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("eye_armor_trim_smithing_template");

  Item FARMLAND = ItemImpl.get("farmland");

  Item FEATHER = ItemImpl.get("feather");

  Item FERMENTED_SPIDER_EYE = ItemImpl.get("fermented_spider_eye");

  Item FERN = ItemImpl.get("fern");

  Item FIELD_MASONED_BANNER_PATTERN = ItemImpl.get("field_masoned_banner_pattern");

  Item FILLED_MAP = ItemImpl.get("filled_map");

  Item FIRE_CHARGE = ItemImpl.get("fire_charge");

  Item FIRE_CORAL = ItemImpl.get("fire_coral");

  Item FIRE_CORAL_BLOCK = ItemImpl.get("fire_coral_block");

  Item FIRE_CORAL_FAN = ItemImpl.get("fire_coral_fan");

  Item FIREFLY_BUSH = ItemImpl.get("firefly_bush");

  Item FIREWORK_ROCKET = ItemImpl.get("firework_rocket");

  Item FIREWORK_STAR = ItemImpl.get("firework_star");

  Item FISHING_ROD = ItemImpl.get("fishing_rod");

  Item FLETCHING_TABLE = ItemImpl.get("fletching_table");

  Item FLINT = ItemImpl.get("flint");

  Item FLINT_AND_STEEL = ItemImpl.get("flint_and_steel");

  Item FLOW_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("flow_armor_trim_smithing_template");

  Item FLOW_BANNER_PATTERN = ItemImpl.get("flow_banner_pattern");

  Item FLOW_POTTERY_SHERD = ItemImpl.get("flow_pottery_sherd");

  Item FLOWER_BANNER_PATTERN = ItemImpl.get("flower_banner_pattern");

  Item FLOWER_POT = ItemImpl.get("flower_pot");

  Item FLOWERING_AZALEA = ItemImpl.get("flowering_azalea");

  Item FLOWERING_AZALEA_LEAVES = ItemImpl.get("flowering_azalea_leaves");

  Item FOX_SPAWN_EGG = ItemImpl.get("fox_spawn_egg");

  Item FRIEND_POTTERY_SHERD = ItemImpl.get("friend_pottery_sherd");

  Item FROG_SPAWN_EGG = ItemImpl.get("frog_spawn_egg");

  Item FROGSPAWN = ItemImpl.get("frogspawn");

  Item FURNACE = ItemImpl.get("furnace");

  Item FURNACE_MINECART = ItemImpl.get("furnace_minecart");

  Item GHAST_SPAWN_EGG = ItemImpl.get("ghast_spawn_egg");

  Item GHAST_TEAR = ItemImpl.get("ghast_tear");

  Item GILDED_BLACKSTONE = ItemImpl.get("gilded_blackstone");

  Item GLASS = ItemImpl.get("glass");

  Item GLASS_BOTTLE = ItemImpl.get("glass_bottle");

  Item GLASS_PANE = ItemImpl.get("glass_pane");

  Item GLISTERING_MELON_SLICE = ItemImpl.get("glistering_melon_slice");

  Item GLOBE_BANNER_PATTERN = ItemImpl.get("globe_banner_pattern");

  Item GLOW_BERRIES = ItemImpl.get("glow_berries");

  Item GLOW_INK_SAC = ItemImpl.get("glow_ink_sac");

  Item GLOW_ITEM_FRAME = ItemImpl.get("glow_item_frame");

  Item GLOW_LICHEN = ItemImpl.get("glow_lichen");

  Item GLOW_SQUID_SPAWN_EGG = ItemImpl.get("glow_squid_spawn_egg");

  Item GLOWSTONE = ItemImpl.get("glowstone");

  Item GLOWSTONE_DUST = ItemImpl.get("glowstone_dust");

  Item GOAT_HORN = ItemImpl.get("goat_horn");

  Item GOAT_SPAWN_EGG = ItemImpl.get("goat_spawn_egg");

  Item GOLD_BLOCK = ItemImpl.get("gold_block");

  Item GOLD_INGOT = ItemImpl.get("gold_ingot");

  Item GOLD_NUGGET = ItemImpl.get("gold_nugget");

  Item GOLD_ORE = ItemImpl.get("gold_ore");

  Item GOLDEN_APPLE = ItemImpl.get("golden_apple");

  Item GOLDEN_AXE = ItemImpl.get("golden_axe");

  Item GOLDEN_BOOTS = ItemImpl.get("golden_boots");

  Item GOLDEN_CARROT = ItemImpl.get("golden_carrot");

  Item GOLDEN_CHESTPLATE = ItemImpl.get("golden_chestplate");

  Item GOLDEN_HELMET = ItemImpl.get("golden_helmet");

  Item GOLDEN_HOE = ItemImpl.get("golden_hoe");

  Item GOLDEN_HORSE_ARMOR = ItemImpl.get("golden_horse_armor");

  Item GOLDEN_LEGGINGS = ItemImpl.get("golden_leggings");

  Item GOLDEN_PICKAXE = ItemImpl.get("golden_pickaxe");

  Item GOLDEN_SHOVEL = ItemImpl.get("golden_shovel");

  Item GOLDEN_SWORD = ItemImpl.get("golden_sword");

  Item GRANITE = ItemImpl.get("granite");

  Item GRANITE_SLAB = ItemImpl.get("granite_slab");

  Item GRANITE_STAIRS = ItemImpl.get("granite_stairs");

  Item GRANITE_WALL = ItemImpl.get("granite_wall");

  Item GRASS_BLOCK = ItemImpl.get("grass_block");

  Item GRAVEL = ItemImpl.get("gravel");

  Item GRAY_BANNER = ItemImpl.get("gray_banner");

  Item GRAY_BED = ItemImpl.get("gray_bed");

  Item GRAY_BUNDLE = ItemImpl.get("gray_bundle");

  Item GRAY_CANDLE = ItemImpl.get("gray_candle");

  Item GRAY_CARPET = ItemImpl.get("gray_carpet");

  Item GRAY_CONCRETE = ItemImpl.get("gray_concrete");

  Item GRAY_CONCRETE_POWDER = ItemImpl.get("gray_concrete_powder");

  Item GRAY_DYE = ItemImpl.get("gray_dye");

  Item GRAY_GLAZED_TERRACOTTA = ItemImpl.get("gray_glazed_terracotta");

  Item GRAY_HARNESS = ItemImpl.get("gray_harness");

  Item GRAY_SHULKER_BOX = ItemImpl.get("gray_shulker_box");

  Item GRAY_STAINED_GLASS = ItemImpl.get("gray_stained_glass");

  Item GRAY_STAINED_GLASS_PANE = ItemImpl.get("gray_stained_glass_pane");

  Item GRAY_TERRACOTTA = ItemImpl.get("gray_terracotta");

  Item GRAY_WOOL = ItemImpl.get("gray_wool");

  Item GREEN_BANNER = ItemImpl.get("green_banner");

  Item GREEN_BED = ItemImpl.get("green_bed");

  Item GREEN_BUNDLE = ItemImpl.get("green_bundle");

  Item GREEN_CANDLE = ItemImpl.get("green_candle");

  Item GREEN_CARPET = ItemImpl.get("green_carpet");

  Item GREEN_CONCRETE = ItemImpl.get("green_concrete");

  Item GREEN_CONCRETE_POWDER = ItemImpl.get("green_concrete_powder");

  Item GREEN_DYE = ItemImpl.get("green_dye");

  Item GREEN_GLAZED_TERRACOTTA = ItemImpl.get("green_glazed_terracotta");

  Item GREEN_HARNESS = ItemImpl.get("green_harness");

  Item GREEN_SHULKER_BOX = ItemImpl.get("green_shulker_box");

  Item GREEN_STAINED_GLASS = ItemImpl.get("green_stained_glass");

  Item GREEN_STAINED_GLASS_PANE = ItemImpl.get("green_stained_glass_pane");

  Item GREEN_TERRACOTTA = ItemImpl.get("green_terracotta");

  Item GREEN_WOOL = ItemImpl.get("green_wool");

  Item GRINDSTONE = ItemImpl.get("grindstone");

  Item GUARDIAN_SPAWN_EGG = ItemImpl.get("guardian_spawn_egg");

  Item GUNPOWDER = ItemImpl.get("gunpowder");

  Item GUSTER_BANNER_PATTERN = ItemImpl.get("guster_banner_pattern");

  Item GUSTER_POTTERY_SHERD = ItemImpl.get("guster_pottery_sherd");

  Item HANGING_ROOTS = ItemImpl.get("hanging_roots");

  Item HAPPY_GHAST_SPAWN_EGG = ItemImpl.get("happy_ghast_spawn_egg");

  Item HAY_BLOCK = ItemImpl.get("hay_block");

  Item HEART_OF_THE_SEA = ItemImpl.get("heart_of_the_sea");

  Item HEART_POTTERY_SHERD = ItemImpl.get("heart_pottery_sherd");

  Item HEARTBREAK_POTTERY_SHERD = ItemImpl.get("heartbreak_pottery_sherd");

  Item HEAVY_CORE = ItemImpl.get("heavy_core");

  Item HEAVY_WEIGHTED_PRESSURE_PLATE = ItemImpl.get("heavy_weighted_pressure_plate");

  Item HOGLIN_SPAWN_EGG = ItemImpl.get("hoglin_spawn_egg");

  Item HONEY_BLOCK = ItemImpl.get("honey_block");

  Item HONEY_BOTTLE = ItemImpl.get("honey_bottle");

  Item HONEYCOMB = ItemImpl.get("honeycomb");

  Item HONEYCOMB_BLOCK = ItemImpl.get("honeycomb_block");

  Item HOPPER = ItemImpl.get("hopper");

  Item HOPPER_MINECART = ItemImpl.get("hopper_minecart");

  Item HORN_CORAL = ItemImpl.get("horn_coral");

  Item HORN_CORAL_BLOCK = ItemImpl.get("horn_coral_block");

  Item HORN_CORAL_FAN = ItemImpl.get("horn_coral_fan");

  Item HORSE_SPAWN_EGG = ItemImpl.get("horse_spawn_egg");

  Item HOST_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("host_armor_trim_smithing_template");

  Item HOWL_POTTERY_SHERD = ItemImpl.get("howl_pottery_sherd");

  Item HUSK_SPAWN_EGG = ItemImpl.get("husk_spawn_egg");

  Item ICE = ItemImpl.get("ice");

  Item INFESTED_CHISELED_STONE_BRICKS = ItemImpl.get("infested_chiseled_stone_bricks");

  Item INFESTED_COBBLESTONE = ItemImpl.get("infested_cobblestone");

  Item INFESTED_CRACKED_STONE_BRICKS = ItemImpl.get("infested_cracked_stone_bricks");

  Item INFESTED_DEEPSLATE = ItemImpl.get("infested_deepslate");

  Item INFESTED_MOSSY_STONE_BRICKS = ItemImpl.get("infested_mossy_stone_bricks");

  Item INFESTED_STONE = ItemImpl.get("infested_stone");

  Item INFESTED_STONE_BRICKS = ItemImpl.get("infested_stone_bricks");

  Item INK_SAC = ItemImpl.get("ink_sac");

  Item IRON_AXE = ItemImpl.get("iron_axe");

  Item IRON_BARS = ItemImpl.get("iron_bars");

  Item IRON_BLOCK = ItemImpl.get("iron_block");

  Item IRON_BOOTS = ItemImpl.get("iron_boots");

  Item IRON_CHAIN = ItemImpl.get("iron_chain");

  Item IRON_CHESTPLATE = ItemImpl.get("iron_chestplate");

  Item IRON_DOOR = ItemImpl.get("iron_door");

  Item IRON_GOLEM_SPAWN_EGG = ItemImpl.get("iron_golem_spawn_egg");

  Item IRON_HELMET = ItemImpl.get("iron_helmet");

  Item IRON_HOE = ItemImpl.get("iron_hoe");

  Item IRON_HORSE_ARMOR = ItemImpl.get("iron_horse_armor");

  Item IRON_INGOT = ItemImpl.get("iron_ingot");

  Item IRON_LEGGINGS = ItemImpl.get("iron_leggings");

  Item IRON_NUGGET = ItemImpl.get("iron_nugget");

  Item IRON_ORE = ItemImpl.get("iron_ore");

  Item IRON_PICKAXE = ItemImpl.get("iron_pickaxe");

  Item IRON_SHOVEL = ItemImpl.get("iron_shovel");

  Item IRON_SWORD = ItemImpl.get("iron_sword");

  Item IRON_TRAPDOOR = ItemImpl.get("iron_trapdoor");

  Item ITEM_FRAME = ItemImpl.get("item_frame");

  Item JACK_O_LANTERN = ItemImpl.get("jack_o_lantern");

  Item JIGSAW = ItemImpl.get("jigsaw");

  Item JUKEBOX = ItemImpl.get("jukebox");

  Item JUNGLE_BOAT = ItemImpl.get("jungle_boat");

  Item JUNGLE_BUTTON = ItemImpl.get("jungle_button");

  Item JUNGLE_CHEST_BOAT = ItemImpl.get("jungle_chest_boat");

  Item JUNGLE_DOOR = ItemImpl.get("jungle_door");

  Item JUNGLE_FENCE = ItemImpl.get("jungle_fence");

  Item JUNGLE_FENCE_GATE = ItemImpl.get("jungle_fence_gate");

  Item JUNGLE_HANGING_SIGN = ItemImpl.get("jungle_hanging_sign");

  Item JUNGLE_LEAVES = ItemImpl.get("jungle_leaves");

  Item JUNGLE_LOG = ItemImpl.get("jungle_log");

  Item JUNGLE_PLANKS = ItemImpl.get("jungle_planks");

  Item JUNGLE_PRESSURE_PLATE = ItemImpl.get("jungle_pressure_plate");

  Item JUNGLE_SAPLING = ItemImpl.get("jungle_sapling");

  Item JUNGLE_SHELF = ItemImpl.get("jungle_shelf");

  Item JUNGLE_SIGN = ItemImpl.get("jungle_sign");

  Item JUNGLE_SLAB = ItemImpl.get("jungle_slab");

  Item JUNGLE_STAIRS = ItemImpl.get("jungle_stairs");

  Item JUNGLE_TRAPDOOR = ItemImpl.get("jungle_trapdoor");

  Item JUNGLE_WOOD = ItemImpl.get("jungle_wood");

  Item KELP = ItemImpl.get("kelp");

  Item KNOWLEDGE_BOOK = ItemImpl.get("knowledge_book");

  Item LADDER = ItemImpl.get("ladder");

  Item LANTERN = ItemImpl.get("lantern");

  Item LAPIS_BLOCK = ItemImpl.get("lapis_block");

  Item LAPIS_LAZULI = ItemImpl.get("lapis_lazuli");

  Item LAPIS_ORE = ItemImpl.get("lapis_ore");

  Item LARGE_AMETHYST_BUD = ItemImpl.get("large_amethyst_bud");

  Item LARGE_FERN = ItemImpl.get("large_fern");

  Item LAVA_BUCKET = ItemImpl.get("lava_bucket");

  Item LEAD = ItemImpl.get("lead");

  Item LEAF_LITTER = ItemImpl.get("leaf_litter");

  Item LEATHER = ItemImpl.get("leather");

  Item LEATHER_BOOTS = ItemImpl.get("leather_boots");

  Item LEATHER_CHESTPLATE = ItemImpl.get("leather_chestplate");

  Item LEATHER_HELMET = ItemImpl.get("leather_helmet");

  Item LEATHER_HORSE_ARMOR = ItemImpl.get("leather_horse_armor");

  Item LEATHER_LEGGINGS = ItemImpl.get("leather_leggings");

  Item LECTERN = ItemImpl.get("lectern");

  Item LEVER = ItemImpl.get("lever");

  Item LIGHT = ItemImpl.get("light");

  Item LIGHT_BLUE_BANNER = ItemImpl.get("light_blue_banner");

  Item LIGHT_BLUE_BED = ItemImpl.get("light_blue_bed");

  Item LIGHT_BLUE_BUNDLE = ItemImpl.get("light_blue_bundle");

  Item LIGHT_BLUE_CANDLE = ItemImpl.get("light_blue_candle");

  Item LIGHT_BLUE_CARPET = ItemImpl.get("light_blue_carpet");

  Item LIGHT_BLUE_CONCRETE = ItemImpl.get("light_blue_concrete");

  Item LIGHT_BLUE_CONCRETE_POWDER = ItemImpl.get("light_blue_concrete_powder");

  Item LIGHT_BLUE_DYE = ItemImpl.get("light_blue_dye");

  Item LIGHT_BLUE_GLAZED_TERRACOTTA = ItemImpl.get("light_blue_glazed_terracotta");

  Item LIGHT_BLUE_HARNESS = ItemImpl.get("light_blue_harness");

  Item LIGHT_BLUE_SHULKER_BOX = ItemImpl.get("light_blue_shulker_box");

  Item LIGHT_BLUE_STAINED_GLASS = ItemImpl.get("light_blue_stained_glass");

  Item LIGHT_BLUE_STAINED_GLASS_PANE = ItemImpl.get("light_blue_stained_glass_pane");

  Item LIGHT_BLUE_TERRACOTTA = ItemImpl.get("light_blue_terracotta");

  Item LIGHT_BLUE_WOOL = ItemImpl.get("light_blue_wool");

  Item LIGHT_GRAY_BANNER = ItemImpl.get("light_gray_banner");

  Item LIGHT_GRAY_BED = ItemImpl.get("light_gray_bed");

  Item LIGHT_GRAY_BUNDLE = ItemImpl.get("light_gray_bundle");

  Item LIGHT_GRAY_CANDLE = ItemImpl.get("light_gray_candle");

  Item LIGHT_GRAY_CARPET = ItemImpl.get("light_gray_carpet");

  Item LIGHT_GRAY_CONCRETE = ItemImpl.get("light_gray_concrete");

  Item LIGHT_GRAY_CONCRETE_POWDER = ItemImpl.get("light_gray_concrete_powder");

  Item LIGHT_GRAY_DYE = ItemImpl.get("light_gray_dye");

  Item LIGHT_GRAY_GLAZED_TERRACOTTA = ItemImpl.get("light_gray_glazed_terracotta");

  Item LIGHT_GRAY_HARNESS = ItemImpl.get("light_gray_harness");

  Item LIGHT_GRAY_SHULKER_BOX = ItemImpl.get("light_gray_shulker_box");

  Item LIGHT_GRAY_STAINED_GLASS = ItemImpl.get("light_gray_stained_glass");

  Item LIGHT_GRAY_STAINED_GLASS_PANE = ItemImpl.get("light_gray_stained_glass_pane");

  Item LIGHT_GRAY_TERRACOTTA = ItemImpl.get("light_gray_terracotta");

  Item LIGHT_GRAY_WOOL = ItemImpl.get("light_gray_wool");

  Item LIGHT_WEIGHTED_PRESSURE_PLATE = ItemImpl.get("light_weighted_pressure_plate");

  Item LIGHTNING_ROD = ItemImpl.get("lightning_rod");

  Item LILAC = ItemImpl.get("lilac");

  Item LILY_OF_THE_VALLEY = ItemImpl.get("lily_of_the_valley");

  Item LILY_PAD = ItemImpl.get("lily_pad");

  Item LIME_BANNER = ItemImpl.get("lime_banner");

  Item LIME_BED = ItemImpl.get("lime_bed");

  Item LIME_BUNDLE = ItemImpl.get("lime_bundle");

  Item LIME_CANDLE = ItemImpl.get("lime_candle");

  Item LIME_CARPET = ItemImpl.get("lime_carpet");

  Item LIME_CONCRETE = ItemImpl.get("lime_concrete");

  Item LIME_CONCRETE_POWDER = ItemImpl.get("lime_concrete_powder");

  Item LIME_DYE = ItemImpl.get("lime_dye");

  Item LIME_GLAZED_TERRACOTTA = ItemImpl.get("lime_glazed_terracotta");

  Item LIME_HARNESS = ItemImpl.get("lime_harness");

  Item LIME_SHULKER_BOX = ItemImpl.get("lime_shulker_box");

  Item LIME_STAINED_GLASS = ItemImpl.get("lime_stained_glass");

  Item LIME_STAINED_GLASS_PANE = ItemImpl.get("lime_stained_glass_pane");

  Item LIME_TERRACOTTA = ItemImpl.get("lime_terracotta");

  Item LIME_WOOL = ItemImpl.get("lime_wool");

  Item LINGERING_POTION = ItemImpl.get("lingering_potion");

  Item LLAMA_SPAWN_EGG = ItemImpl.get("llama_spawn_egg");

  Item LODESTONE = ItemImpl.get("lodestone");

  Item LOOM = ItemImpl.get("loom");

  Item MACE = ItemImpl.get("mace");

  Item MAGENTA_BANNER = ItemImpl.get("magenta_banner");

  Item MAGENTA_BED = ItemImpl.get("magenta_bed");

  Item MAGENTA_BUNDLE = ItemImpl.get("magenta_bundle");

  Item MAGENTA_CANDLE = ItemImpl.get("magenta_candle");

  Item MAGENTA_CARPET = ItemImpl.get("magenta_carpet");

  Item MAGENTA_CONCRETE = ItemImpl.get("magenta_concrete");

  Item MAGENTA_CONCRETE_POWDER = ItemImpl.get("magenta_concrete_powder");

  Item MAGENTA_DYE = ItemImpl.get("magenta_dye");

  Item MAGENTA_GLAZED_TERRACOTTA = ItemImpl.get("magenta_glazed_terracotta");

  Item MAGENTA_HARNESS = ItemImpl.get("magenta_harness");

  Item MAGENTA_SHULKER_BOX = ItemImpl.get("magenta_shulker_box");

  Item MAGENTA_STAINED_GLASS = ItemImpl.get("magenta_stained_glass");

  Item MAGENTA_STAINED_GLASS_PANE = ItemImpl.get("magenta_stained_glass_pane");

  Item MAGENTA_TERRACOTTA = ItemImpl.get("magenta_terracotta");

  Item MAGENTA_WOOL = ItemImpl.get("magenta_wool");

  Item MAGMA_BLOCK = ItemImpl.get("magma_block");

  Item MAGMA_CREAM = ItemImpl.get("magma_cream");

  Item MAGMA_CUBE_SPAWN_EGG = ItemImpl.get("magma_cube_spawn_egg");

  Item MANGROVE_BOAT = ItemImpl.get("mangrove_boat");

  Item MANGROVE_BUTTON = ItemImpl.get("mangrove_button");

  Item MANGROVE_CHEST_BOAT = ItemImpl.get("mangrove_chest_boat");

  Item MANGROVE_DOOR = ItemImpl.get("mangrove_door");

  Item MANGROVE_FENCE = ItemImpl.get("mangrove_fence");

  Item MANGROVE_FENCE_GATE = ItemImpl.get("mangrove_fence_gate");

  Item MANGROVE_HANGING_SIGN = ItemImpl.get("mangrove_hanging_sign");

  Item MANGROVE_LEAVES = ItemImpl.get("mangrove_leaves");

  Item MANGROVE_LOG = ItemImpl.get("mangrove_log");

  Item MANGROVE_PLANKS = ItemImpl.get("mangrove_planks");

  Item MANGROVE_PRESSURE_PLATE = ItemImpl.get("mangrove_pressure_plate");

  Item MANGROVE_PROPAGULE = ItemImpl.get("mangrove_propagule");

  Item MANGROVE_ROOTS = ItemImpl.get("mangrove_roots");

  Item MANGROVE_SHELF = ItemImpl.get("mangrove_shelf");

  Item MANGROVE_SIGN = ItemImpl.get("mangrove_sign");

  Item MANGROVE_SLAB = ItemImpl.get("mangrove_slab");

  Item MANGROVE_STAIRS = ItemImpl.get("mangrove_stairs");

  Item MANGROVE_TRAPDOOR = ItemImpl.get("mangrove_trapdoor");

  Item MANGROVE_WOOD = ItemImpl.get("mangrove_wood");

  Item MAP = ItemImpl.get("map");

  Item MEDIUM_AMETHYST_BUD = ItemImpl.get("medium_amethyst_bud");

  Item MELON = ItemImpl.get("melon");

  Item MELON_SEEDS = ItemImpl.get("melon_seeds");

  Item MELON_SLICE = ItemImpl.get("melon_slice");

  Item MILK_BUCKET = ItemImpl.get("milk_bucket");

  Item MINECART = ItemImpl.get("minecart");

  Item MINER_POTTERY_SHERD = ItemImpl.get("miner_pottery_sherd");

  Item MOJANG_BANNER_PATTERN = ItemImpl.get("mojang_banner_pattern");

  Item MOOSHROOM_SPAWN_EGG = ItemImpl.get("mooshroom_spawn_egg");

  Item MOSS_BLOCK = ItemImpl.get("moss_block");

  Item MOSS_CARPET = ItemImpl.get("moss_carpet");

  Item MOSSY_COBBLESTONE = ItemImpl.get("mossy_cobblestone");

  Item MOSSY_COBBLESTONE_SLAB = ItemImpl.get("mossy_cobblestone_slab");

  Item MOSSY_COBBLESTONE_STAIRS = ItemImpl.get("mossy_cobblestone_stairs");

  Item MOSSY_COBBLESTONE_WALL = ItemImpl.get("mossy_cobblestone_wall");

  Item MOSSY_STONE_BRICK_SLAB = ItemImpl.get("mossy_stone_brick_slab");

  Item MOSSY_STONE_BRICK_STAIRS = ItemImpl.get("mossy_stone_brick_stairs");

  Item MOSSY_STONE_BRICK_WALL = ItemImpl.get("mossy_stone_brick_wall");

  Item MOSSY_STONE_BRICKS = ItemImpl.get("mossy_stone_bricks");

  Item MOURNER_POTTERY_SHERD = ItemImpl.get("mourner_pottery_sherd");

  Item MUD = ItemImpl.get("mud");

  Item MUD_BRICK_SLAB = ItemImpl.get("mud_brick_slab");

  Item MUD_BRICK_STAIRS = ItemImpl.get("mud_brick_stairs");

  Item MUD_BRICK_WALL = ItemImpl.get("mud_brick_wall");

  Item MUD_BRICKS = ItemImpl.get("mud_bricks");

  Item MUDDY_MANGROVE_ROOTS = ItemImpl.get("muddy_mangrove_roots");

  Item MULE_SPAWN_EGG = ItemImpl.get("mule_spawn_egg");

  Item MUSHROOM_STEM = ItemImpl.get("mushroom_stem");

  Item MUSHROOM_STEW = ItemImpl.get("mushroom_stew");

  Item MUSIC_DISC_11 = ItemImpl.get("music_disc_11");

  Item MUSIC_DISC_13 = ItemImpl.get("music_disc_13");

  Item MUSIC_DISC_5 = ItemImpl.get("music_disc_5");

  Item MUSIC_DISC_BLOCKS = ItemImpl.get("music_disc_blocks");

  Item MUSIC_DISC_CAT = ItemImpl.get("music_disc_cat");

  Item MUSIC_DISC_CHIRP = ItemImpl.get("music_disc_chirp");

  Item MUSIC_DISC_CREATOR = ItemImpl.get("music_disc_creator");

  Item MUSIC_DISC_CREATOR_MUSIC_BOX = ItemImpl.get("music_disc_creator_music_box");

  Item MUSIC_DISC_FAR = ItemImpl.get("music_disc_far");

  Item MUSIC_DISC_LAVA_CHICKEN = ItemImpl.get("music_disc_lava_chicken");

  Item MUSIC_DISC_MALL = ItemImpl.get("music_disc_mall");

  Item MUSIC_DISC_MELLOHI = ItemImpl.get("music_disc_mellohi");

  Item MUSIC_DISC_OTHERSIDE = ItemImpl.get("music_disc_otherside");

  Item MUSIC_DISC_PIGSTEP = ItemImpl.get("music_disc_pigstep");

  Item MUSIC_DISC_PRECIPICE = ItemImpl.get("music_disc_precipice");

  Item MUSIC_DISC_RELIC = ItemImpl.get("music_disc_relic");

  Item MUSIC_DISC_STAL = ItemImpl.get("music_disc_stal");

  Item MUSIC_DISC_STRAD = ItemImpl.get("music_disc_strad");

  Item MUSIC_DISC_TEARS = ItemImpl.get("music_disc_tears");

  Item MUSIC_DISC_WAIT = ItemImpl.get("music_disc_wait");

  Item MUSIC_DISC_WARD = ItemImpl.get("music_disc_ward");

  Item MUTTON = ItemImpl.get("mutton");

  Item MYCELIUM = ItemImpl.get("mycelium");

  Item NAME_TAG = ItemImpl.get("name_tag");

  Item NAUTILUS_SHELL = ItemImpl.get("nautilus_shell");

  Item NETHER_BRICK = ItemImpl.get("nether_brick");

  Item NETHER_BRICK_FENCE = ItemImpl.get("nether_brick_fence");

  Item NETHER_BRICK_SLAB = ItemImpl.get("nether_brick_slab");

  Item NETHER_BRICK_STAIRS = ItemImpl.get("nether_brick_stairs");

  Item NETHER_BRICK_WALL = ItemImpl.get("nether_brick_wall");

  Item NETHER_BRICKS = ItemImpl.get("nether_bricks");

  Item NETHER_GOLD_ORE = ItemImpl.get("nether_gold_ore");

  Item NETHER_QUARTZ_ORE = ItemImpl.get("nether_quartz_ore");

  Item NETHER_SPROUTS = ItemImpl.get("nether_sprouts");

  Item NETHER_STAR = ItemImpl.get("nether_star");

  Item NETHER_WART = ItemImpl.get("nether_wart");

  Item NETHER_WART_BLOCK = ItemImpl.get("nether_wart_block");

  Item NETHERITE_AXE = ItemImpl.get("netherite_axe");

  Item NETHERITE_BLOCK = ItemImpl.get("netherite_block");

  Item NETHERITE_BOOTS = ItemImpl.get("netherite_boots");

  Item NETHERITE_CHESTPLATE = ItemImpl.get("netherite_chestplate");

  Item NETHERITE_HELMET = ItemImpl.get("netherite_helmet");

  Item NETHERITE_HOE = ItemImpl.get("netherite_hoe");

  Item NETHERITE_INGOT = ItemImpl.get("netherite_ingot");

  Item NETHERITE_LEGGINGS = ItemImpl.get("netherite_leggings");

  Item NETHERITE_PICKAXE = ItemImpl.get("netherite_pickaxe");

  Item NETHERITE_SCRAP = ItemImpl.get("netherite_scrap");

  Item NETHERITE_SHOVEL = ItemImpl.get("netherite_shovel");

  Item NETHERITE_SWORD = ItemImpl.get("netherite_sword");

  Item NETHERITE_UPGRADE_SMITHING_TEMPLATE = ItemImpl.get("netherite_upgrade_smithing_template");

  Item NETHERRACK = ItemImpl.get("netherrack");

  Item NOTE_BLOCK = ItemImpl.get("note_block");

  Item OAK_BOAT = ItemImpl.get("oak_boat");

  Item OAK_BUTTON = ItemImpl.get("oak_button");

  Item OAK_CHEST_BOAT = ItemImpl.get("oak_chest_boat");

  Item OAK_DOOR = ItemImpl.get("oak_door");

  Item OAK_FENCE = ItemImpl.get("oak_fence");

  Item OAK_FENCE_GATE = ItemImpl.get("oak_fence_gate");

  Item OAK_HANGING_SIGN = ItemImpl.get("oak_hanging_sign");

  Item OAK_LEAVES = ItemImpl.get("oak_leaves");

  Item OAK_LOG = ItemImpl.get("oak_log");

  Item OAK_PLANKS = ItemImpl.get("oak_planks");

  Item OAK_PRESSURE_PLATE = ItemImpl.get("oak_pressure_plate");

  Item OAK_SAPLING = ItemImpl.get("oak_sapling");

  Item OAK_SHELF = ItemImpl.get("oak_shelf");

  Item OAK_SIGN = ItemImpl.get("oak_sign");

  Item OAK_SLAB = ItemImpl.get("oak_slab");

  Item OAK_STAIRS = ItemImpl.get("oak_stairs");

  Item OAK_TRAPDOOR = ItemImpl.get("oak_trapdoor");

  Item OAK_WOOD = ItemImpl.get("oak_wood");

  Item OBSERVER = ItemImpl.get("observer");

  Item OBSIDIAN = ItemImpl.get("obsidian");

  Item OCELOT_SPAWN_EGG = ItemImpl.get("ocelot_spawn_egg");

  Item OCHRE_FROGLIGHT = ItemImpl.get("ochre_froglight");

  Item OMINOUS_BOTTLE = ItemImpl.get("ominous_bottle");

  Item OMINOUS_TRIAL_KEY = ItemImpl.get("ominous_trial_key");

  Item OPEN_EYEBLOSSOM = ItemImpl.get("open_eyeblossom");

  Item ORANGE_BANNER = ItemImpl.get("orange_banner");

  Item ORANGE_BED = ItemImpl.get("orange_bed");

  Item ORANGE_BUNDLE = ItemImpl.get("orange_bundle");

  Item ORANGE_CANDLE = ItemImpl.get("orange_candle");

  Item ORANGE_CARPET = ItemImpl.get("orange_carpet");

  Item ORANGE_CONCRETE = ItemImpl.get("orange_concrete");

  Item ORANGE_CONCRETE_POWDER = ItemImpl.get("orange_concrete_powder");

  Item ORANGE_DYE = ItemImpl.get("orange_dye");

  Item ORANGE_GLAZED_TERRACOTTA = ItemImpl.get("orange_glazed_terracotta");

  Item ORANGE_HARNESS = ItemImpl.get("orange_harness");

  Item ORANGE_SHULKER_BOX = ItemImpl.get("orange_shulker_box");

  Item ORANGE_STAINED_GLASS = ItemImpl.get("orange_stained_glass");

  Item ORANGE_STAINED_GLASS_PANE = ItemImpl.get("orange_stained_glass_pane");

  Item ORANGE_TERRACOTTA = ItemImpl.get("orange_terracotta");

  Item ORANGE_TULIP = ItemImpl.get("orange_tulip");

  Item ORANGE_WOOL = ItemImpl.get("orange_wool");

  Item OXEYE_DAISY = ItemImpl.get("oxeye_daisy");

  Item OXIDIZED_CHISELED_COPPER = ItemImpl.get("oxidized_chiseled_copper");

  Item OXIDIZED_COPPER = ItemImpl.get("oxidized_copper");

  Item OXIDIZED_COPPER_BARS = ItemImpl.get("oxidized_copper_bars");

  Item OXIDIZED_COPPER_BULB = ItemImpl.get("oxidized_copper_bulb");

  Item OXIDIZED_COPPER_CHAIN = ItemImpl.get("oxidized_copper_chain");

  Item OXIDIZED_COPPER_CHEST = ItemImpl.get("oxidized_copper_chest");

  Item OXIDIZED_COPPER_DOOR = ItemImpl.get("oxidized_copper_door");

  Item OXIDIZED_COPPER_GOLEM_STATUE = ItemImpl.get("oxidized_copper_golem_statue");

  Item OXIDIZED_COPPER_GRATE = ItemImpl.get("oxidized_copper_grate");

  Item OXIDIZED_COPPER_LANTERN = ItemImpl.get("oxidized_copper_lantern");

  Item OXIDIZED_COPPER_TRAPDOOR = ItemImpl.get("oxidized_copper_trapdoor");

  Item OXIDIZED_CUT_COPPER = ItemImpl.get("oxidized_cut_copper");

  Item OXIDIZED_CUT_COPPER_SLAB = ItemImpl.get("oxidized_cut_copper_slab");

  Item OXIDIZED_CUT_COPPER_STAIRS = ItemImpl.get("oxidized_cut_copper_stairs");

  Item OXIDIZED_LIGHTNING_ROD = ItemImpl.get("oxidized_lightning_rod");

  Item PACKED_ICE = ItemImpl.get("packed_ice");

  Item PACKED_MUD = ItemImpl.get("packed_mud");

  Item PAINTING = ItemImpl.get("painting");

  Item PALE_HANGING_MOSS = ItemImpl.get("pale_hanging_moss");

  Item PALE_MOSS_BLOCK = ItemImpl.get("pale_moss_block");

  Item PALE_MOSS_CARPET = ItemImpl.get("pale_moss_carpet");

  Item PALE_OAK_BOAT = ItemImpl.get("pale_oak_boat");

  Item PALE_OAK_BUTTON = ItemImpl.get("pale_oak_button");

  Item PALE_OAK_CHEST_BOAT = ItemImpl.get("pale_oak_chest_boat");

  Item PALE_OAK_DOOR = ItemImpl.get("pale_oak_door");

  Item PALE_OAK_FENCE = ItemImpl.get("pale_oak_fence");

  Item PALE_OAK_FENCE_GATE = ItemImpl.get("pale_oak_fence_gate");

  Item PALE_OAK_HANGING_SIGN = ItemImpl.get("pale_oak_hanging_sign");

  Item PALE_OAK_LEAVES = ItemImpl.get("pale_oak_leaves");

  Item PALE_OAK_LOG = ItemImpl.get("pale_oak_log");

  Item PALE_OAK_PLANKS = ItemImpl.get("pale_oak_planks");

  Item PALE_OAK_PRESSURE_PLATE = ItemImpl.get("pale_oak_pressure_plate");

  Item PALE_OAK_SAPLING = ItemImpl.get("pale_oak_sapling");

  Item PALE_OAK_SHELF = ItemImpl.get("pale_oak_shelf");

  Item PALE_OAK_SIGN = ItemImpl.get("pale_oak_sign");

  Item PALE_OAK_SLAB = ItemImpl.get("pale_oak_slab");

  Item PALE_OAK_STAIRS = ItemImpl.get("pale_oak_stairs");

  Item PALE_OAK_TRAPDOOR = ItemImpl.get("pale_oak_trapdoor");

  Item PALE_OAK_WOOD = ItemImpl.get("pale_oak_wood");

  Item PANDA_SPAWN_EGG = ItemImpl.get("panda_spawn_egg");

  Item PAPER = ItemImpl.get("paper");

  Item PARROT_SPAWN_EGG = ItemImpl.get("parrot_spawn_egg");

  Item PEARLESCENT_FROGLIGHT = ItemImpl.get("pearlescent_froglight");

  Item PEONY = ItemImpl.get("peony");

  Item PETRIFIED_OAK_SLAB = ItemImpl.get("petrified_oak_slab");

  Item PHANTOM_MEMBRANE = ItemImpl.get("phantom_membrane");

  Item PHANTOM_SPAWN_EGG = ItemImpl.get("phantom_spawn_egg");

  Item PIG_SPAWN_EGG = ItemImpl.get("pig_spawn_egg");

  Item PIGLIN_BANNER_PATTERN = ItemImpl.get("piglin_banner_pattern");

  Item PIGLIN_BRUTE_SPAWN_EGG = ItemImpl.get("piglin_brute_spawn_egg");

  Item PIGLIN_HEAD = ItemImpl.get("piglin_head");

  Item PIGLIN_SPAWN_EGG = ItemImpl.get("piglin_spawn_egg");

  Item PILLAGER_SPAWN_EGG = ItemImpl.get("pillager_spawn_egg");

  Item PINK_BANNER = ItemImpl.get("pink_banner");

  Item PINK_BED = ItemImpl.get("pink_bed");

  Item PINK_BUNDLE = ItemImpl.get("pink_bundle");

  Item PINK_CANDLE = ItemImpl.get("pink_candle");

  Item PINK_CARPET = ItemImpl.get("pink_carpet");

  Item PINK_CONCRETE = ItemImpl.get("pink_concrete");

  Item PINK_CONCRETE_POWDER = ItemImpl.get("pink_concrete_powder");

  Item PINK_DYE = ItemImpl.get("pink_dye");

  Item PINK_GLAZED_TERRACOTTA = ItemImpl.get("pink_glazed_terracotta");

  Item PINK_HARNESS = ItemImpl.get("pink_harness");

  Item PINK_PETALS = ItemImpl.get("pink_petals");

  Item PINK_SHULKER_BOX = ItemImpl.get("pink_shulker_box");

  Item PINK_STAINED_GLASS = ItemImpl.get("pink_stained_glass");

  Item PINK_STAINED_GLASS_PANE = ItemImpl.get("pink_stained_glass_pane");

  Item PINK_TERRACOTTA = ItemImpl.get("pink_terracotta");

  Item PINK_TULIP = ItemImpl.get("pink_tulip");

  Item PINK_WOOL = ItemImpl.get("pink_wool");

  Item PISTON = ItemImpl.get("piston");

  Item PITCHER_PLANT = ItemImpl.get("pitcher_plant");

  Item PITCHER_POD = ItemImpl.get("pitcher_pod");

  Item PLAYER_HEAD = ItemImpl.get("player_head");

  Item PLENTY_POTTERY_SHERD = ItemImpl.get("plenty_pottery_sherd");

  Item PODZOL = ItemImpl.get("podzol");

  Item POINTED_DRIPSTONE = ItemImpl.get("pointed_dripstone");

  Item POISONOUS_POTATO = ItemImpl.get("poisonous_potato");

  Item POLAR_BEAR_SPAWN_EGG = ItemImpl.get("polar_bear_spawn_egg");

  Item POLISHED_ANDESITE = ItemImpl.get("polished_andesite");

  Item POLISHED_ANDESITE_SLAB = ItemImpl.get("polished_andesite_slab");

  Item POLISHED_ANDESITE_STAIRS = ItemImpl.get("polished_andesite_stairs");

  Item POLISHED_BASALT = ItemImpl.get("polished_basalt");

  Item POLISHED_BLACKSTONE = ItemImpl.get("polished_blackstone");

  Item POLISHED_BLACKSTONE_BRICK_SLAB = ItemImpl.get("polished_blackstone_brick_slab");

  Item POLISHED_BLACKSTONE_BRICK_STAIRS = ItemImpl.get("polished_blackstone_brick_stairs");

  Item POLISHED_BLACKSTONE_BRICK_WALL = ItemImpl.get("polished_blackstone_brick_wall");

  Item POLISHED_BLACKSTONE_BRICKS = ItemImpl.get("polished_blackstone_bricks");

  Item POLISHED_BLACKSTONE_BUTTON = ItemImpl.get("polished_blackstone_button");

  Item POLISHED_BLACKSTONE_PRESSURE_PLATE = ItemImpl.get("polished_blackstone_pressure_plate");

  Item POLISHED_BLACKSTONE_SLAB = ItemImpl.get("polished_blackstone_slab");

  Item POLISHED_BLACKSTONE_STAIRS = ItemImpl.get("polished_blackstone_stairs");

  Item POLISHED_BLACKSTONE_WALL = ItemImpl.get("polished_blackstone_wall");

  Item POLISHED_DEEPSLATE = ItemImpl.get("polished_deepslate");

  Item POLISHED_DEEPSLATE_SLAB = ItemImpl.get("polished_deepslate_slab");

  Item POLISHED_DEEPSLATE_STAIRS = ItemImpl.get("polished_deepslate_stairs");

  Item POLISHED_DEEPSLATE_WALL = ItemImpl.get("polished_deepslate_wall");

  Item POLISHED_DIORITE = ItemImpl.get("polished_diorite");

  Item POLISHED_DIORITE_SLAB = ItemImpl.get("polished_diorite_slab");

  Item POLISHED_DIORITE_STAIRS = ItemImpl.get("polished_diorite_stairs");

  Item POLISHED_GRANITE = ItemImpl.get("polished_granite");

  Item POLISHED_GRANITE_SLAB = ItemImpl.get("polished_granite_slab");

  Item POLISHED_GRANITE_STAIRS = ItemImpl.get("polished_granite_stairs");

  Item POLISHED_TUFF = ItemImpl.get("polished_tuff");

  Item POLISHED_TUFF_SLAB = ItemImpl.get("polished_tuff_slab");

  Item POLISHED_TUFF_STAIRS = ItemImpl.get("polished_tuff_stairs");

  Item POLISHED_TUFF_WALL = ItemImpl.get("polished_tuff_wall");

  Item POPPED_CHORUS_FRUIT = ItemImpl.get("popped_chorus_fruit");

  Item POPPY = ItemImpl.get("poppy");

  Item PORKCHOP = ItemImpl.get("porkchop");

  Item POTATO = ItemImpl.get("potato");

  Item POTION = ItemImpl.get("potion");

  Item POWDER_SNOW_BUCKET = ItemImpl.get("powder_snow_bucket");

  Item POWERED_RAIL = ItemImpl.get("powered_rail");

  Item PRISMARINE = ItemImpl.get("prismarine");

  Item PRISMARINE_BRICK_SLAB = ItemImpl.get("prismarine_brick_slab");

  Item PRISMARINE_BRICK_STAIRS = ItemImpl.get("prismarine_brick_stairs");

  Item PRISMARINE_BRICKS = ItemImpl.get("prismarine_bricks");

  Item PRISMARINE_CRYSTALS = ItemImpl.get("prismarine_crystals");

  Item PRISMARINE_SHARD = ItemImpl.get("prismarine_shard");

  Item PRISMARINE_SLAB = ItemImpl.get("prismarine_slab");

  Item PRISMARINE_STAIRS = ItemImpl.get("prismarine_stairs");

  Item PRISMARINE_WALL = ItemImpl.get("prismarine_wall");

  Item PRIZE_POTTERY_SHERD = ItemImpl.get("prize_pottery_sherd");

  Item PUFFERFISH = ItemImpl.get("pufferfish");

  Item PUFFERFISH_BUCKET = ItemImpl.get("pufferfish_bucket");

  Item PUFFERFISH_SPAWN_EGG = ItemImpl.get("pufferfish_spawn_egg");

  Item PUMPKIN = ItemImpl.get("pumpkin");

  Item PUMPKIN_PIE = ItemImpl.get("pumpkin_pie");

  Item PUMPKIN_SEEDS = ItemImpl.get("pumpkin_seeds");

  Item PURPLE_BANNER = ItemImpl.get("purple_banner");

  Item PURPLE_BED = ItemImpl.get("purple_bed");

  Item PURPLE_BUNDLE = ItemImpl.get("purple_bundle");

  Item PURPLE_CANDLE = ItemImpl.get("purple_candle");

  Item PURPLE_CARPET = ItemImpl.get("purple_carpet");

  Item PURPLE_CONCRETE = ItemImpl.get("purple_concrete");

  Item PURPLE_CONCRETE_POWDER = ItemImpl.get("purple_concrete_powder");

  Item PURPLE_DYE = ItemImpl.get("purple_dye");

  Item PURPLE_GLAZED_TERRACOTTA = ItemImpl.get("purple_glazed_terracotta");

  Item PURPLE_HARNESS = ItemImpl.get("purple_harness");

  Item PURPLE_SHULKER_BOX = ItemImpl.get("purple_shulker_box");

  Item PURPLE_STAINED_GLASS = ItemImpl.get("purple_stained_glass");

  Item PURPLE_STAINED_GLASS_PANE = ItemImpl.get("purple_stained_glass_pane");

  Item PURPLE_TERRACOTTA = ItemImpl.get("purple_terracotta");

  Item PURPLE_WOOL = ItemImpl.get("purple_wool");

  Item PURPUR_BLOCK = ItemImpl.get("purpur_block");

  Item PURPUR_PILLAR = ItemImpl.get("purpur_pillar");

  Item PURPUR_SLAB = ItemImpl.get("purpur_slab");

  Item PURPUR_STAIRS = ItemImpl.get("purpur_stairs");

  Item QUARTZ = ItemImpl.get("quartz");

  Item QUARTZ_BLOCK = ItemImpl.get("quartz_block");

  Item QUARTZ_BRICKS = ItemImpl.get("quartz_bricks");

  Item QUARTZ_PILLAR = ItemImpl.get("quartz_pillar");

  Item QUARTZ_SLAB = ItemImpl.get("quartz_slab");

  Item QUARTZ_STAIRS = ItemImpl.get("quartz_stairs");

  Item RABBIT = ItemImpl.get("rabbit");

  Item RABBIT_FOOT = ItemImpl.get("rabbit_foot");

  Item RABBIT_HIDE = ItemImpl.get("rabbit_hide");

  Item RABBIT_SPAWN_EGG = ItemImpl.get("rabbit_spawn_egg");

  Item RABBIT_STEW = ItemImpl.get("rabbit_stew");

  Item RAIL = ItemImpl.get("rail");

  Item RAISER_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("raiser_armor_trim_smithing_template");

  Item RAVAGER_SPAWN_EGG = ItemImpl.get("ravager_spawn_egg");

  Item RAW_COPPER = ItemImpl.get("raw_copper");

  Item RAW_COPPER_BLOCK = ItemImpl.get("raw_copper_block");

  Item RAW_GOLD = ItemImpl.get("raw_gold");

  Item RAW_GOLD_BLOCK = ItemImpl.get("raw_gold_block");

  Item RAW_IRON = ItemImpl.get("raw_iron");

  Item RAW_IRON_BLOCK = ItemImpl.get("raw_iron_block");

  Item RECOVERY_COMPASS = ItemImpl.get("recovery_compass");

  Item RED_BANNER = ItemImpl.get("red_banner");

  Item RED_BED = ItemImpl.get("red_bed");

  Item RED_BUNDLE = ItemImpl.get("red_bundle");

  Item RED_CANDLE = ItemImpl.get("red_candle");

  Item RED_CARPET = ItemImpl.get("red_carpet");

  Item RED_CONCRETE = ItemImpl.get("red_concrete");

  Item RED_CONCRETE_POWDER = ItemImpl.get("red_concrete_powder");

  Item RED_DYE = ItemImpl.get("red_dye");

  Item RED_GLAZED_TERRACOTTA = ItemImpl.get("red_glazed_terracotta");

  Item RED_HARNESS = ItemImpl.get("red_harness");

  Item RED_MUSHROOM = ItemImpl.get("red_mushroom");

  Item RED_MUSHROOM_BLOCK = ItemImpl.get("red_mushroom_block");

  Item RED_NETHER_BRICK_SLAB = ItemImpl.get("red_nether_brick_slab");

  Item RED_NETHER_BRICK_STAIRS = ItemImpl.get("red_nether_brick_stairs");

  Item RED_NETHER_BRICK_WALL = ItemImpl.get("red_nether_brick_wall");

  Item RED_NETHER_BRICKS = ItemImpl.get("red_nether_bricks");

  Item RED_SAND = ItemImpl.get("red_sand");

  Item RED_SANDSTONE = ItemImpl.get("red_sandstone");

  Item RED_SANDSTONE_SLAB = ItemImpl.get("red_sandstone_slab");

  Item RED_SANDSTONE_STAIRS = ItemImpl.get("red_sandstone_stairs");

  Item RED_SANDSTONE_WALL = ItemImpl.get("red_sandstone_wall");

  Item RED_SHULKER_BOX = ItemImpl.get("red_shulker_box");

  Item RED_STAINED_GLASS = ItemImpl.get("red_stained_glass");

  Item RED_STAINED_GLASS_PANE = ItemImpl.get("red_stained_glass_pane");

  Item RED_TERRACOTTA = ItemImpl.get("red_terracotta");

  Item RED_TULIP = ItemImpl.get("red_tulip");

  Item RED_WOOL = ItemImpl.get("red_wool");

  Item REDSTONE = ItemImpl.get("redstone");

  Item REDSTONE_BLOCK = ItemImpl.get("redstone_block");

  Item REDSTONE_LAMP = ItemImpl.get("redstone_lamp");

  Item REDSTONE_ORE = ItemImpl.get("redstone_ore");

  Item REDSTONE_TORCH = ItemImpl.get("redstone_torch");

  Item REINFORCED_DEEPSLATE = ItemImpl.get("reinforced_deepslate");

  Item REPEATER = ItemImpl.get("repeater");

  Item REPEATING_COMMAND_BLOCK = ItemImpl.get("repeating_command_block");

  Item RESIN_BLOCK = ItemImpl.get("resin_block");

  Item RESIN_BRICK = ItemImpl.get("resin_brick");

  Item RESIN_BRICK_SLAB = ItemImpl.get("resin_brick_slab");

  Item RESIN_BRICK_STAIRS = ItemImpl.get("resin_brick_stairs");

  Item RESIN_BRICK_WALL = ItemImpl.get("resin_brick_wall");

  Item RESIN_BRICKS = ItemImpl.get("resin_bricks");

  Item RESIN_CLUMP = ItemImpl.get("resin_clump");

  Item RESPAWN_ANCHOR = ItemImpl.get("respawn_anchor");

  Item RIB_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("rib_armor_trim_smithing_template");

  Item ROOTED_DIRT = ItemImpl.get("rooted_dirt");

  Item ROSE_BUSH = ItemImpl.get("rose_bush");

  Item ROTTEN_FLESH = ItemImpl.get("rotten_flesh");

  Item SADDLE = ItemImpl.get("saddle");

  Item SALMON = ItemImpl.get("salmon");

  Item SALMON_BUCKET = ItemImpl.get("salmon_bucket");

  Item SALMON_SPAWN_EGG = ItemImpl.get("salmon_spawn_egg");

  Item SAND = ItemImpl.get("sand");

  Item SANDSTONE = ItemImpl.get("sandstone");

  Item SANDSTONE_SLAB = ItemImpl.get("sandstone_slab");

  Item SANDSTONE_STAIRS = ItemImpl.get("sandstone_stairs");

  Item SANDSTONE_WALL = ItemImpl.get("sandstone_wall");

  Item SCAFFOLDING = ItemImpl.get("scaffolding");

  Item SCRAPE_POTTERY_SHERD = ItemImpl.get("scrape_pottery_sherd");

  Item SCULK = ItemImpl.get("sculk");

  Item SCULK_CATALYST = ItemImpl.get("sculk_catalyst");

  Item SCULK_SENSOR = ItemImpl.get("sculk_sensor");

  Item SCULK_SHRIEKER = ItemImpl.get("sculk_shrieker");

  Item SCULK_VEIN = ItemImpl.get("sculk_vein");

  Item SEA_LANTERN = ItemImpl.get("sea_lantern");

  Item SEA_PICKLE = ItemImpl.get("sea_pickle");

  Item SEAGRASS = ItemImpl.get("seagrass");

  Item SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("sentry_armor_trim_smithing_template");

  Item SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("shaper_armor_trim_smithing_template");

  Item SHEAF_POTTERY_SHERD = ItemImpl.get("sheaf_pottery_sherd");

  Item SHEARS = ItemImpl.get("shears");

  Item SHEEP_SPAWN_EGG = ItemImpl.get("sheep_spawn_egg");

  Item SHELTER_POTTERY_SHERD = ItemImpl.get("shelter_pottery_sherd");

  Item SHIELD = ItemImpl.get("shield");

  Item SHORT_DRY_GRASS = ItemImpl.get("short_dry_grass");

  Item SHORT_GRASS = ItemImpl.get("short_grass");

  Item SHROOMLIGHT = ItemImpl.get("shroomlight");

  Item SHULKER_BOX = ItemImpl.get("shulker_box");

  Item SHULKER_SHELL = ItemImpl.get("shulker_shell");

  Item SHULKER_SPAWN_EGG = ItemImpl.get("shulker_spawn_egg");

  Item SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("silence_armor_trim_smithing_template");

  Item SILVERFISH_SPAWN_EGG = ItemImpl.get("silverfish_spawn_egg");

  Item SKELETON_HORSE_SPAWN_EGG = ItemImpl.get("skeleton_horse_spawn_egg");

  Item SKELETON_SKULL = ItemImpl.get("skeleton_skull");

  Item SKELETON_SPAWN_EGG = ItemImpl.get("skeleton_spawn_egg");

  Item SKULL_BANNER_PATTERN = ItemImpl.get("skull_banner_pattern");

  Item SKULL_POTTERY_SHERD = ItemImpl.get("skull_pottery_sherd");

  Item SLIME_BALL = ItemImpl.get("slime_ball");

  Item SLIME_BLOCK = ItemImpl.get("slime_block");

  Item SLIME_SPAWN_EGG = ItemImpl.get("slime_spawn_egg");

  Item SMALL_AMETHYST_BUD = ItemImpl.get("small_amethyst_bud");

  Item SMALL_DRIPLEAF = ItemImpl.get("small_dripleaf");

  Item SMITHING_TABLE = ItemImpl.get("smithing_table");

  Item SMOKER = ItemImpl.get("smoker");

  Item SMOOTH_BASALT = ItemImpl.get("smooth_basalt");

  Item SMOOTH_QUARTZ = ItemImpl.get("smooth_quartz");

  Item SMOOTH_QUARTZ_SLAB = ItemImpl.get("smooth_quartz_slab");

  Item SMOOTH_QUARTZ_STAIRS = ItemImpl.get("smooth_quartz_stairs");

  Item SMOOTH_RED_SANDSTONE = ItemImpl.get("smooth_red_sandstone");

  Item SMOOTH_RED_SANDSTONE_SLAB = ItemImpl.get("smooth_red_sandstone_slab");

  Item SMOOTH_RED_SANDSTONE_STAIRS = ItemImpl.get("smooth_red_sandstone_stairs");

  Item SMOOTH_SANDSTONE = ItemImpl.get("smooth_sandstone");

  Item SMOOTH_SANDSTONE_SLAB = ItemImpl.get("smooth_sandstone_slab");

  Item SMOOTH_SANDSTONE_STAIRS = ItemImpl.get("smooth_sandstone_stairs");

  Item SMOOTH_STONE = ItemImpl.get("smooth_stone");

  Item SMOOTH_STONE_SLAB = ItemImpl.get("smooth_stone_slab");

  Item SNIFFER_EGG = ItemImpl.get("sniffer_egg");

  Item SNIFFER_SPAWN_EGG = ItemImpl.get("sniffer_spawn_egg");

  Item SNORT_POTTERY_SHERD = ItemImpl.get("snort_pottery_sherd");

  Item SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("snout_armor_trim_smithing_template");

  Item SNOW = ItemImpl.get("snow");

  Item SNOW_BLOCK = ItemImpl.get("snow_block");

  Item SNOW_GOLEM_SPAWN_EGG = ItemImpl.get("snow_golem_spawn_egg");

  Item SNOWBALL = ItemImpl.get("snowball");

  Item SOUL_CAMPFIRE = ItemImpl.get("soul_campfire");

  Item SOUL_LANTERN = ItemImpl.get("soul_lantern");

  Item SOUL_SAND = ItemImpl.get("soul_sand");

  Item SOUL_SOIL = ItemImpl.get("soul_soil");

  Item SOUL_TORCH = ItemImpl.get("soul_torch");

  Item SPAWNER = ItemImpl.get("spawner");

  Item SPECTRAL_ARROW = ItemImpl.get("spectral_arrow");

  Item SPIDER_EYE = ItemImpl.get("spider_eye");

  Item SPIDER_SPAWN_EGG = ItemImpl.get("spider_spawn_egg");

  Item SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("spire_armor_trim_smithing_template");

  Item SPLASH_POTION = ItemImpl.get("splash_potion");

  Item SPONGE = ItemImpl.get("sponge");

  Item SPORE_BLOSSOM = ItemImpl.get("spore_blossom");

  Item SPRUCE_BOAT = ItemImpl.get("spruce_boat");

  Item SPRUCE_BUTTON = ItemImpl.get("spruce_button");

  Item SPRUCE_CHEST_BOAT = ItemImpl.get("spruce_chest_boat");

  Item SPRUCE_DOOR = ItemImpl.get("spruce_door");

  Item SPRUCE_FENCE = ItemImpl.get("spruce_fence");

  Item SPRUCE_FENCE_GATE = ItemImpl.get("spruce_fence_gate");

  Item SPRUCE_HANGING_SIGN = ItemImpl.get("spruce_hanging_sign");

  Item SPRUCE_LEAVES = ItemImpl.get("spruce_leaves");

  Item SPRUCE_LOG = ItemImpl.get("spruce_log");

  Item SPRUCE_PLANKS = ItemImpl.get("spruce_planks");

  Item SPRUCE_PRESSURE_PLATE = ItemImpl.get("spruce_pressure_plate");

  Item SPRUCE_SAPLING = ItemImpl.get("spruce_sapling");

  Item SPRUCE_SHELF = ItemImpl.get("spruce_shelf");

  Item SPRUCE_SIGN = ItemImpl.get("spruce_sign");

  Item SPRUCE_SLAB = ItemImpl.get("spruce_slab");

  Item SPRUCE_STAIRS = ItemImpl.get("spruce_stairs");

  Item SPRUCE_TRAPDOOR = ItemImpl.get("spruce_trapdoor");

  Item SPRUCE_WOOD = ItemImpl.get("spruce_wood");

  Item SPYGLASS = ItemImpl.get("spyglass");

  Item SQUID_SPAWN_EGG = ItemImpl.get("squid_spawn_egg");

  Item STICK = ItemImpl.get("stick");

  Item STICKY_PISTON = ItemImpl.get("sticky_piston");

  Item STONE = ItemImpl.get("stone");

  Item STONE_AXE = ItemImpl.get("stone_axe");

  Item STONE_BRICK_SLAB = ItemImpl.get("stone_brick_slab");

  Item STONE_BRICK_STAIRS = ItemImpl.get("stone_brick_stairs");

  Item STONE_BRICK_WALL = ItemImpl.get("stone_brick_wall");

  Item STONE_BRICKS = ItemImpl.get("stone_bricks");

  Item STONE_BUTTON = ItemImpl.get("stone_button");

  Item STONE_HOE = ItemImpl.get("stone_hoe");

  Item STONE_PICKAXE = ItemImpl.get("stone_pickaxe");

  Item STONE_PRESSURE_PLATE = ItemImpl.get("stone_pressure_plate");

  Item STONE_SHOVEL = ItemImpl.get("stone_shovel");

  Item STONE_SLAB = ItemImpl.get("stone_slab");

  Item STONE_STAIRS = ItemImpl.get("stone_stairs");

  Item STONE_SWORD = ItemImpl.get("stone_sword");

  Item STONECUTTER = ItemImpl.get("stonecutter");

  Item STRAY_SPAWN_EGG = ItemImpl.get("stray_spawn_egg");

  Item STRIDER_SPAWN_EGG = ItemImpl.get("strider_spawn_egg");

  Item STRING = ItemImpl.get("string");

  Item STRIPPED_ACACIA_LOG = ItemImpl.get("stripped_acacia_log");

  Item STRIPPED_ACACIA_WOOD = ItemImpl.get("stripped_acacia_wood");

  Item STRIPPED_BAMBOO_BLOCK = ItemImpl.get("stripped_bamboo_block");

  Item STRIPPED_BIRCH_LOG = ItemImpl.get("stripped_birch_log");

  Item STRIPPED_BIRCH_WOOD = ItemImpl.get("stripped_birch_wood");

  Item STRIPPED_CHERRY_LOG = ItemImpl.get("stripped_cherry_log");

  Item STRIPPED_CHERRY_WOOD = ItemImpl.get("stripped_cherry_wood");

  Item STRIPPED_CRIMSON_HYPHAE = ItemImpl.get("stripped_crimson_hyphae");

  Item STRIPPED_CRIMSON_STEM = ItemImpl.get("stripped_crimson_stem");

  Item STRIPPED_DARK_OAK_LOG = ItemImpl.get("stripped_dark_oak_log");

  Item STRIPPED_DARK_OAK_WOOD = ItemImpl.get("stripped_dark_oak_wood");

  Item STRIPPED_JUNGLE_LOG = ItemImpl.get("stripped_jungle_log");

  Item STRIPPED_JUNGLE_WOOD = ItemImpl.get("stripped_jungle_wood");

  Item STRIPPED_MANGROVE_LOG = ItemImpl.get("stripped_mangrove_log");

  Item STRIPPED_MANGROVE_WOOD = ItemImpl.get("stripped_mangrove_wood");

  Item STRIPPED_OAK_LOG = ItemImpl.get("stripped_oak_log");

  Item STRIPPED_OAK_WOOD = ItemImpl.get("stripped_oak_wood");

  Item STRIPPED_PALE_OAK_LOG = ItemImpl.get("stripped_pale_oak_log");

  Item STRIPPED_PALE_OAK_WOOD = ItemImpl.get("stripped_pale_oak_wood");

  Item STRIPPED_SPRUCE_LOG = ItemImpl.get("stripped_spruce_log");

  Item STRIPPED_SPRUCE_WOOD = ItemImpl.get("stripped_spruce_wood");

  Item STRIPPED_WARPED_HYPHAE = ItemImpl.get("stripped_warped_hyphae");

  Item STRIPPED_WARPED_STEM = ItemImpl.get("stripped_warped_stem");

  Item STRUCTURE_BLOCK = ItemImpl.get("structure_block");

  Item STRUCTURE_VOID = ItemImpl.get("structure_void");

  Item SUGAR = ItemImpl.get("sugar");

  Item SUGAR_CANE = ItemImpl.get("sugar_cane");

  Item SUNFLOWER = ItemImpl.get("sunflower");

  Item SUSPICIOUS_GRAVEL = ItemImpl.get("suspicious_gravel");

  Item SUSPICIOUS_SAND = ItemImpl.get("suspicious_sand");

  Item SUSPICIOUS_STEW = ItemImpl.get("suspicious_stew");

  Item SWEET_BERRIES = ItemImpl.get("sweet_berries");

  Item TADPOLE_BUCKET = ItemImpl.get("tadpole_bucket");

  Item TADPOLE_SPAWN_EGG = ItemImpl.get("tadpole_spawn_egg");

  Item TALL_DRY_GRASS = ItemImpl.get("tall_dry_grass");

  Item TALL_GRASS = ItemImpl.get("tall_grass");

  Item TARGET = ItemImpl.get("target");

  Item TERRACOTTA = ItemImpl.get("terracotta");

  Item TEST_BLOCK = ItemImpl.get("test_block");

  Item TEST_INSTANCE_BLOCK = ItemImpl.get("test_instance_block");

  Item TIDE_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("tide_armor_trim_smithing_template");

  Item TINTED_GLASS = ItemImpl.get("tinted_glass");

  Item TIPPED_ARROW = ItemImpl.get("tipped_arrow");

  Item TNT = ItemImpl.get("tnt");

  Item TNT_MINECART = ItemImpl.get("tnt_minecart");

  Item TORCH = ItemImpl.get("torch");

  Item TORCHFLOWER = ItemImpl.get("torchflower");

  Item TORCHFLOWER_SEEDS = ItemImpl.get("torchflower_seeds");

  Item TOTEM_OF_UNDYING = ItemImpl.get("totem_of_undying");

  Item TRADER_LLAMA_SPAWN_EGG = ItemImpl.get("trader_llama_spawn_egg");

  Item TRAPPED_CHEST = ItemImpl.get("trapped_chest");

  Item TRIAL_KEY = ItemImpl.get("trial_key");

  Item TRIAL_SPAWNER = ItemImpl.get("trial_spawner");

  Item TRIDENT = ItemImpl.get("trident");

  Item TRIPWIRE_HOOK = ItemImpl.get("tripwire_hook");

  Item TROPICAL_FISH = ItemImpl.get("tropical_fish");

  Item TROPICAL_FISH_BUCKET = ItemImpl.get("tropical_fish_bucket");

  Item TROPICAL_FISH_SPAWN_EGG = ItemImpl.get("tropical_fish_spawn_egg");

  Item TUBE_CORAL = ItemImpl.get("tube_coral");

  Item TUBE_CORAL_BLOCK = ItemImpl.get("tube_coral_block");

  Item TUBE_CORAL_FAN = ItemImpl.get("tube_coral_fan");

  Item TUFF = ItemImpl.get("tuff");

  Item TUFF_BRICK_SLAB = ItemImpl.get("tuff_brick_slab");

  Item TUFF_BRICK_STAIRS = ItemImpl.get("tuff_brick_stairs");

  Item TUFF_BRICK_WALL = ItemImpl.get("tuff_brick_wall");

  Item TUFF_BRICKS = ItemImpl.get("tuff_bricks");

  Item TUFF_SLAB = ItemImpl.get("tuff_slab");

  Item TUFF_STAIRS = ItemImpl.get("tuff_stairs");

  Item TUFF_WALL = ItemImpl.get("tuff_wall");

  Item TURTLE_EGG = ItemImpl.get("turtle_egg");

  Item TURTLE_HELMET = ItemImpl.get("turtle_helmet");

  Item TURTLE_SCUTE = ItemImpl.get("turtle_scute");

  Item TURTLE_SPAWN_EGG = ItemImpl.get("turtle_spawn_egg");

  Item TWISTING_VINES = ItemImpl.get("twisting_vines");

  Item VAULT = ItemImpl.get("vault");

  Item VERDANT_FROGLIGHT = ItemImpl.get("verdant_froglight");

  Item VEX_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("vex_armor_trim_smithing_template");

  Item VEX_SPAWN_EGG = ItemImpl.get("vex_spawn_egg");

  Item VILLAGER_SPAWN_EGG = ItemImpl.get("villager_spawn_egg");

  Item VINDICATOR_SPAWN_EGG = ItemImpl.get("vindicator_spawn_egg");

  Item VINE = ItemImpl.get("vine");

  Item WANDERING_TRADER_SPAWN_EGG = ItemImpl.get("wandering_trader_spawn_egg");

  Item WARD_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("ward_armor_trim_smithing_template");

  Item WARDEN_SPAWN_EGG = ItemImpl.get("warden_spawn_egg");

  Item WARPED_BUTTON = ItemImpl.get("warped_button");

  Item WARPED_DOOR = ItemImpl.get("warped_door");

  Item WARPED_FENCE = ItemImpl.get("warped_fence");

  Item WARPED_FENCE_GATE = ItemImpl.get("warped_fence_gate");

  Item WARPED_FUNGUS = ItemImpl.get("warped_fungus");

  Item WARPED_FUNGUS_ON_A_STICK = ItemImpl.get("warped_fungus_on_a_stick");

  Item WARPED_HANGING_SIGN = ItemImpl.get("warped_hanging_sign");

  Item WARPED_HYPHAE = ItemImpl.get("warped_hyphae");

  Item WARPED_NYLIUM = ItemImpl.get("warped_nylium");

  Item WARPED_PLANKS = ItemImpl.get("warped_planks");

  Item WARPED_PRESSURE_PLATE = ItemImpl.get("warped_pressure_plate");

  Item WARPED_ROOTS = ItemImpl.get("warped_roots");

  Item WARPED_SHELF = ItemImpl.get("warped_shelf");

  Item WARPED_SIGN = ItemImpl.get("warped_sign");

  Item WARPED_SLAB = ItemImpl.get("warped_slab");

  Item WARPED_STAIRS = ItemImpl.get("warped_stairs");

  Item WARPED_STEM = ItemImpl.get("warped_stem");

  Item WARPED_TRAPDOOR = ItemImpl.get("warped_trapdoor");

  Item WARPED_WART_BLOCK = ItemImpl.get("warped_wart_block");

  Item WATER_BUCKET = ItemImpl.get("water_bucket");

  Item WAXED_CHISELED_COPPER = ItemImpl.get("waxed_chiseled_copper");

  Item WAXED_COPPER_BARS = ItemImpl.get("waxed_copper_bars");

  Item WAXED_COPPER_BLOCK = ItemImpl.get("waxed_copper_block");

  Item WAXED_COPPER_BULB = ItemImpl.get("waxed_copper_bulb");

  Item WAXED_COPPER_CHAIN = ItemImpl.get("waxed_copper_chain");

  Item WAXED_COPPER_CHEST = ItemImpl.get("waxed_copper_chest");

  Item WAXED_COPPER_DOOR = ItemImpl.get("waxed_copper_door");

  Item WAXED_COPPER_GOLEM_STATUE = ItemImpl.get("waxed_copper_golem_statue");

  Item WAXED_COPPER_GRATE = ItemImpl.get("waxed_copper_grate");

  Item WAXED_COPPER_LANTERN = ItemImpl.get("waxed_copper_lantern");

  Item WAXED_COPPER_TRAPDOOR = ItemImpl.get("waxed_copper_trapdoor");

  Item WAXED_CUT_COPPER = ItemImpl.get("waxed_cut_copper");

  Item WAXED_CUT_COPPER_SLAB = ItemImpl.get("waxed_cut_copper_slab");

  Item WAXED_CUT_COPPER_STAIRS = ItemImpl.get("waxed_cut_copper_stairs");

  Item WAXED_EXPOSED_CHISELED_COPPER = ItemImpl.get("waxed_exposed_chiseled_copper");

  Item WAXED_EXPOSED_COPPER = ItemImpl.get("waxed_exposed_copper");

  Item WAXED_EXPOSED_COPPER_BARS = ItemImpl.get("waxed_exposed_copper_bars");

  Item WAXED_EXPOSED_COPPER_BULB = ItemImpl.get("waxed_exposed_copper_bulb");

  Item WAXED_EXPOSED_COPPER_CHAIN = ItemImpl.get("waxed_exposed_copper_chain");

  Item WAXED_EXPOSED_COPPER_CHEST = ItemImpl.get("waxed_exposed_copper_chest");

  Item WAXED_EXPOSED_COPPER_DOOR = ItemImpl.get("waxed_exposed_copper_door");

  Item WAXED_EXPOSED_COPPER_GOLEM_STATUE = ItemImpl.get("waxed_exposed_copper_golem_statue");

  Item WAXED_EXPOSED_COPPER_GRATE = ItemImpl.get("waxed_exposed_copper_grate");

  Item WAXED_EXPOSED_COPPER_LANTERN = ItemImpl.get("waxed_exposed_copper_lantern");

  Item WAXED_EXPOSED_COPPER_TRAPDOOR = ItemImpl.get("waxed_exposed_copper_trapdoor");

  Item WAXED_EXPOSED_CUT_COPPER = ItemImpl.get("waxed_exposed_cut_copper");

  Item WAXED_EXPOSED_CUT_COPPER_SLAB = ItemImpl.get("waxed_exposed_cut_copper_slab");

  Item WAXED_EXPOSED_CUT_COPPER_STAIRS = ItemImpl.get("waxed_exposed_cut_copper_stairs");

  Item WAXED_EXPOSED_LIGHTNING_ROD = ItemImpl.get("waxed_exposed_lightning_rod");

  Item WAXED_LIGHTNING_ROD = ItemImpl.get("waxed_lightning_rod");

  Item WAXED_OXIDIZED_CHISELED_COPPER = ItemImpl.get("waxed_oxidized_chiseled_copper");

  Item WAXED_OXIDIZED_COPPER = ItemImpl.get("waxed_oxidized_copper");

  Item WAXED_OXIDIZED_COPPER_BARS = ItemImpl.get("waxed_oxidized_copper_bars");

  Item WAXED_OXIDIZED_COPPER_BULB = ItemImpl.get("waxed_oxidized_copper_bulb");

  Item WAXED_OXIDIZED_COPPER_CHAIN = ItemImpl.get("waxed_oxidized_copper_chain");

  Item WAXED_OXIDIZED_COPPER_CHEST = ItemImpl.get("waxed_oxidized_copper_chest");

  Item WAXED_OXIDIZED_COPPER_DOOR = ItemImpl.get("waxed_oxidized_copper_door");

  Item WAXED_OXIDIZED_COPPER_GOLEM_STATUE = ItemImpl.get("waxed_oxidized_copper_golem_statue");

  Item WAXED_OXIDIZED_COPPER_GRATE = ItemImpl.get("waxed_oxidized_copper_grate");

  Item WAXED_OXIDIZED_COPPER_LANTERN = ItemImpl.get("waxed_oxidized_copper_lantern");

  Item WAXED_OXIDIZED_COPPER_TRAPDOOR = ItemImpl.get("waxed_oxidized_copper_trapdoor");

  Item WAXED_OXIDIZED_CUT_COPPER = ItemImpl.get("waxed_oxidized_cut_copper");

  Item WAXED_OXIDIZED_CUT_COPPER_SLAB = ItemImpl.get("waxed_oxidized_cut_copper_slab");

  Item WAXED_OXIDIZED_CUT_COPPER_STAIRS = ItemImpl.get("waxed_oxidized_cut_copper_stairs");

  Item WAXED_OXIDIZED_LIGHTNING_ROD = ItemImpl.get("waxed_oxidized_lightning_rod");

  Item WAXED_WEATHERED_CHISELED_COPPER = ItemImpl.get("waxed_weathered_chiseled_copper");

  Item WAXED_WEATHERED_COPPER = ItemImpl.get("waxed_weathered_copper");

  Item WAXED_WEATHERED_COPPER_BARS = ItemImpl.get("waxed_weathered_copper_bars");

  Item WAXED_WEATHERED_COPPER_BULB = ItemImpl.get("waxed_weathered_copper_bulb");

  Item WAXED_WEATHERED_COPPER_CHAIN = ItemImpl.get("waxed_weathered_copper_chain");

  Item WAXED_WEATHERED_COPPER_CHEST = ItemImpl.get("waxed_weathered_copper_chest");

  Item WAXED_WEATHERED_COPPER_DOOR = ItemImpl.get("waxed_weathered_copper_door");

  Item WAXED_WEATHERED_COPPER_GOLEM_STATUE = ItemImpl.get("waxed_weathered_copper_golem_statue");

  Item WAXED_WEATHERED_COPPER_GRATE = ItemImpl.get("waxed_weathered_copper_grate");

  Item WAXED_WEATHERED_COPPER_LANTERN = ItemImpl.get("waxed_weathered_copper_lantern");

  Item WAXED_WEATHERED_COPPER_TRAPDOOR = ItemImpl.get("waxed_weathered_copper_trapdoor");

  Item WAXED_WEATHERED_CUT_COPPER = ItemImpl.get("waxed_weathered_cut_copper");

  Item WAXED_WEATHERED_CUT_COPPER_SLAB = ItemImpl.get("waxed_weathered_cut_copper_slab");

  Item WAXED_WEATHERED_CUT_COPPER_STAIRS = ItemImpl.get("waxed_weathered_cut_copper_stairs");

  Item WAXED_WEATHERED_LIGHTNING_ROD = ItemImpl.get("waxed_weathered_lightning_rod");

  Item WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("wayfinder_armor_trim_smithing_template");

  Item WEATHERED_CHISELED_COPPER = ItemImpl.get("weathered_chiseled_copper");

  Item WEATHERED_COPPER = ItemImpl.get("weathered_copper");

  Item WEATHERED_COPPER_BARS = ItemImpl.get("weathered_copper_bars");

  Item WEATHERED_COPPER_BULB = ItemImpl.get("weathered_copper_bulb");

  Item WEATHERED_COPPER_CHAIN = ItemImpl.get("weathered_copper_chain");

  Item WEATHERED_COPPER_CHEST = ItemImpl.get("weathered_copper_chest");

  Item WEATHERED_COPPER_DOOR = ItemImpl.get("weathered_copper_door");

  Item WEATHERED_COPPER_GOLEM_STATUE = ItemImpl.get("weathered_copper_golem_statue");

  Item WEATHERED_COPPER_GRATE = ItemImpl.get("weathered_copper_grate");

  Item WEATHERED_COPPER_LANTERN = ItemImpl.get("weathered_copper_lantern");

  Item WEATHERED_COPPER_TRAPDOOR = ItemImpl.get("weathered_copper_trapdoor");

  Item WEATHERED_CUT_COPPER = ItemImpl.get("weathered_cut_copper");

  Item WEATHERED_CUT_COPPER_SLAB = ItemImpl.get("weathered_cut_copper_slab");

  Item WEATHERED_CUT_COPPER_STAIRS = ItemImpl.get("weathered_cut_copper_stairs");

  Item WEATHERED_LIGHTNING_ROD = ItemImpl.get("weathered_lightning_rod");

  Item WEEPING_VINES = ItemImpl.get("weeping_vines");

  Item WET_SPONGE = ItemImpl.get("wet_sponge");

  Item WHEAT = ItemImpl.get("wheat");

  Item WHEAT_SEEDS = ItemImpl.get("wheat_seeds");

  Item WHITE_BANNER = ItemImpl.get("white_banner");

  Item WHITE_BED = ItemImpl.get("white_bed");

  Item WHITE_BUNDLE = ItemImpl.get("white_bundle");

  Item WHITE_CANDLE = ItemImpl.get("white_candle");

  Item WHITE_CARPET = ItemImpl.get("white_carpet");

  Item WHITE_CONCRETE = ItemImpl.get("white_concrete");

  Item WHITE_CONCRETE_POWDER = ItemImpl.get("white_concrete_powder");

  Item WHITE_DYE = ItemImpl.get("white_dye");

  Item WHITE_GLAZED_TERRACOTTA = ItemImpl.get("white_glazed_terracotta");

  Item WHITE_HARNESS = ItemImpl.get("white_harness");

  Item WHITE_SHULKER_BOX = ItemImpl.get("white_shulker_box");

  Item WHITE_STAINED_GLASS = ItemImpl.get("white_stained_glass");

  Item WHITE_STAINED_GLASS_PANE = ItemImpl.get("white_stained_glass_pane");

  Item WHITE_TERRACOTTA = ItemImpl.get("white_terracotta");

  Item WHITE_TULIP = ItemImpl.get("white_tulip");

  Item WHITE_WOOL = ItemImpl.get("white_wool");

  Item WILD_ARMOR_TRIM_SMITHING_TEMPLATE = ItemImpl.get("wild_armor_trim_smithing_template");

  Item WILDFLOWERS = ItemImpl.get("wildflowers");

  Item WIND_CHARGE = ItemImpl.get("wind_charge");

  Item WITCH_SPAWN_EGG = ItemImpl.get("witch_spawn_egg");

  Item WITHER_ROSE = ItemImpl.get("wither_rose");

  Item WITHER_SKELETON_SKULL = ItemImpl.get("wither_skeleton_skull");

  Item WITHER_SKELETON_SPAWN_EGG = ItemImpl.get("wither_skeleton_spawn_egg");

  Item WITHER_SPAWN_EGG = ItemImpl.get("wither_spawn_egg");

  Item WOLF_ARMOR = ItemImpl.get("wolf_armor");

  Item WOLF_SPAWN_EGG = ItemImpl.get("wolf_spawn_egg");

  Item WOODEN_AXE = ItemImpl.get("wooden_axe");

  Item WOODEN_HOE = ItemImpl.get("wooden_hoe");

  Item WOODEN_PICKAXE = ItemImpl.get("wooden_pickaxe");

  Item WOODEN_SHOVEL = ItemImpl.get("wooden_shovel");

  Item WOODEN_SWORD = ItemImpl.get("wooden_sword");

  Item WRITABLE_BOOK = ItemImpl.get("writable_book");

  Item WRITTEN_BOOK = ItemImpl.get("written_book");

  Item YELLOW_BANNER = ItemImpl.get("yellow_banner");

  Item YELLOW_BED = ItemImpl.get("yellow_bed");

  Item YELLOW_BUNDLE = ItemImpl.get("yellow_bundle");

  Item YELLOW_CANDLE = ItemImpl.get("yellow_candle");

  Item YELLOW_CARPET = ItemImpl.get("yellow_carpet");

  Item YELLOW_CONCRETE = ItemImpl.get("yellow_concrete");

  Item YELLOW_CONCRETE_POWDER = ItemImpl.get("yellow_concrete_powder");

  Item YELLOW_DYE = ItemImpl.get("yellow_dye");

  Item YELLOW_GLAZED_TERRACOTTA = ItemImpl.get("yellow_glazed_terracotta");

  Item YELLOW_HARNESS = ItemImpl.get("yellow_harness");

  Item YELLOW_SHULKER_BOX = ItemImpl.get("yellow_shulker_box");

  Item YELLOW_STAINED_GLASS = ItemImpl.get("yellow_stained_glass");

  Item YELLOW_STAINED_GLASS_PANE = ItemImpl.get("yellow_stained_glass_pane");

  Item YELLOW_TERRACOTTA = ItemImpl.get("yellow_terracotta");

  Item YELLOW_WOOL = ItemImpl.get("yellow_wool");

  Item ZOGLIN_SPAWN_EGG = ItemImpl.get("zoglin_spawn_egg");

  Item ZOMBIE_HEAD = ItemImpl.get("zombie_head");

  Item ZOMBIE_HORSE_SPAWN_EGG = ItemImpl.get("zombie_horse_spawn_egg");

  Item ZOMBIE_SPAWN_EGG = ItemImpl.get("zombie_spawn_egg");

  Item ZOMBIE_VILLAGER_SPAWN_EGG = ItemImpl.get("zombie_villager_spawn_egg");

  Item ZOMBIFIED_PIGLIN_SPAWN_EGG = ItemImpl.get("zombified_piglin_spawn_egg");
}
