package me.moros.bending.api.platform.item;

/**
 * Code autogenerated, do not edit! v1.21.6
 */
@SuppressWarnings("unused")
interface Tags {
  ItemTag ACACIA_LOGS = TagImpl.get("acacia_logs");

  ItemTag ANVIL = TagImpl.get("anvil");

  ItemTag ARMADILLO_FOOD = TagImpl.get("armadillo_food");

  ItemTag ARROWS = TagImpl.get("arrows");

  ItemTag AXES = TagImpl.get("axes");

  ItemTag AXOLOTL_FOOD = TagImpl.get("axolotl_food");

  ItemTag BAMBOO_BLOCKS = TagImpl.get("bamboo_blocks");

  ItemTag BANNERS = TagImpl.get("banners");

  ItemTag BEACON_PAYMENT_ITEMS = TagImpl.get("beacon_payment_items");

  ItemTag BEDS = TagImpl.get("beds");

  ItemTag BEE_FOOD = TagImpl.get("bee_food");

  ItemTag BIRCH_LOGS = TagImpl.get("birch_logs");

  ItemTag BOATS = TagImpl.get("boats");

  ItemTag BOOK_CLONING_TARGET = TagImpl.get("book_cloning_target");

  ItemTag BOOKSHELF_BOOKS = TagImpl.get("bookshelf_books");

  ItemTag BREAKS_DECORATED_POTS = TagImpl.get("breaks_decorated_pots");

  ItemTag BREWING_FUEL = TagImpl.get("brewing_fuel");

  ItemTag BUNDLES = TagImpl.get("bundles");

  ItemTag BUTTONS = TagImpl.get("buttons");

  ItemTag CAMEL_FOOD = TagImpl.get("camel_food");

  ItemTag CANDLES = TagImpl.get("candles");

  ItemTag CAT_FOOD = TagImpl.get("cat_food");

  ItemTag CHERRY_LOGS = TagImpl.get("cherry_logs");

  ItemTag CHEST_ARMOR = TagImpl.get("chest_armor");

  ItemTag CHEST_BOATS = TagImpl.get("chest_boats");

  ItemTag CHICKEN_FOOD = TagImpl.get("chicken_food");

  ItemTag CLUSTER_MAX_HARVESTABLES = TagImpl.get("cluster_max_harvestables");

  ItemTag COAL_ORES = TagImpl.get("coal_ores");

  ItemTag COALS = TagImpl.get("coals");

  ItemTag COMPASSES = TagImpl.get("compasses");

  ItemTag COMPLETES_FIND_TREE_TUTORIAL = TagImpl.get("completes_find_tree_tutorial");

  ItemTag COPPER_ORES = TagImpl.get("copper_ores");

  ItemTag COW_FOOD = TagImpl.get("cow_food");

  ItemTag CREEPER_DROP_MUSIC_DISCS = TagImpl.get("creeper_drop_music_discs");

  ItemTag CREEPER_IGNITERS = TagImpl.get("creeper_igniters");

  ItemTag CRIMSON_STEMS = TagImpl.get("crimson_stems");

  ItemTag DAMPENS_VIBRATIONS = TagImpl.get("dampens_vibrations");

  ItemTag DARK_OAK_LOGS = TagImpl.get("dark_oak_logs");

  ItemTag DECORATED_POT_INGREDIENTS = TagImpl.get("decorated_pot_ingredients");

  ItemTag DECORATED_POT_SHERDS = TagImpl.get("decorated_pot_sherds");

  ItemTag DIAMOND_ORES = TagImpl.get("diamond_ores");

  ItemTag DIAMOND_TOOL_MATERIALS = TagImpl.get("diamond_tool_materials");

  ItemTag DIRT = TagImpl.get("dirt");

  ItemTag DOORS = TagImpl.get("doors");

  ItemTag DROWNED_PREFERRED_WEAPONS = TagImpl.get("drowned_preferred_weapons");

  ItemTag DUPLICATES_ALLAYS = TagImpl.get("duplicates_allays");

  ItemTag DYEABLE = TagImpl.get("dyeable");

  ItemTag EGGS = TagImpl.get("eggs");

  ItemTag EMERALD_ORES = TagImpl.get("emerald_ores");

  ItemTag ENCHANTABLE_ARMOR = TagImpl.get("enchantable/armor");

  ItemTag ENCHANTABLE_BOW = TagImpl.get("enchantable/bow");

  ItemTag ENCHANTABLE_CHEST_ARMOR = TagImpl.get("enchantable/chest_armor");

  ItemTag ENCHANTABLE_CROSSBOW = TagImpl.get("enchantable/crossbow");

  ItemTag ENCHANTABLE_DURABILITY = TagImpl.get("enchantable/durability");

  ItemTag ENCHANTABLE_EQUIPPABLE = TagImpl.get("enchantable/equippable");

  ItemTag ENCHANTABLE_FIRE_ASPECT = TagImpl.get("enchantable/fire_aspect");

  ItemTag ENCHANTABLE_FISHING = TagImpl.get("enchantable/fishing");

  ItemTag ENCHANTABLE_FOOT_ARMOR = TagImpl.get("enchantable/foot_armor");

  ItemTag ENCHANTABLE_HEAD_ARMOR = TagImpl.get("enchantable/head_armor");

  ItemTag ENCHANTABLE_LEG_ARMOR = TagImpl.get("enchantable/leg_armor");

  ItemTag ENCHANTABLE_MACE = TagImpl.get("enchantable/mace");

  ItemTag ENCHANTABLE_MINING = TagImpl.get("enchantable/mining");

  ItemTag ENCHANTABLE_MINING_LOOT = TagImpl.get("enchantable/mining_loot");

  ItemTag ENCHANTABLE_SHARP_WEAPON = TagImpl.get("enchantable/sharp_weapon");

  ItemTag ENCHANTABLE_SWORD = TagImpl.get("enchantable/sword");

  ItemTag ENCHANTABLE_TRIDENT = TagImpl.get("enchantable/trident");

  ItemTag ENCHANTABLE_VANISHING = TagImpl.get("enchantable/vanishing");

  ItemTag ENCHANTABLE_WEAPON = TagImpl.get("enchantable/weapon");

  ItemTag FENCE_GATES = TagImpl.get("fence_gates");

  ItemTag FENCES = TagImpl.get("fences");

  ItemTag FISHES = TagImpl.get("fishes");

  ItemTag FLOWERS = TagImpl.get("flowers");

  ItemTag FOOT_ARMOR = TagImpl.get("foot_armor");

  ItemTag FOX_FOOD = TagImpl.get("fox_food");

  ItemTag FREEZE_IMMUNE_WEARABLES = TagImpl.get("freeze_immune_wearables");

  ItemTag FROG_FOOD = TagImpl.get("frog_food");

  ItemTag FURNACE_MINECART_FUEL = TagImpl.get("furnace_minecart_fuel");

  ItemTag GAZE_DISGUISE_EQUIPMENT = TagImpl.get("gaze_disguise_equipment");

  ItemTag GOAT_FOOD = TagImpl.get("goat_food");

  ItemTag GOLD_ORES = TagImpl.get("gold_ores");

  ItemTag GOLD_TOOL_MATERIALS = TagImpl.get("gold_tool_materials");

  ItemTag HANGING_SIGNS = TagImpl.get("hanging_signs");

  ItemTag HAPPY_GHAST_FOOD = TagImpl.get("happy_ghast_food");

  ItemTag HAPPY_GHAST_TEMPT_ITEMS = TagImpl.get("happy_ghast_tempt_items");

  ItemTag HARNESSES = TagImpl.get("harnesses");

  ItemTag HEAD_ARMOR = TagImpl.get("head_armor");

  ItemTag HOES = TagImpl.get("hoes");

  ItemTag HOGLIN_FOOD = TagImpl.get("hoglin_food");

  ItemTag HORSE_FOOD = TagImpl.get("horse_food");

  ItemTag HORSE_TEMPT_ITEMS = TagImpl.get("horse_tempt_items");

  ItemTag IGNORED_BY_PIGLIN_BABIES = TagImpl.get("ignored_by_piglin_babies");

  ItemTag IRON_ORES = TagImpl.get("iron_ores");

  ItemTag IRON_TOOL_MATERIALS = TagImpl.get("iron_tool_materials");

  ItemTag JUNGLE_LOGS = TagImpl.get("jungle_logs");

  ItemTag LAPIS_ORES = TagImpl.get("lapis_ores");

  ItemTag LEAVES = TagImpl.get("leaves");

  ItemTag LECTERN_BOOKS = TagImpl.get("lectern_books");

  ItemTag LEG_ARMOR = TagImpl.get("leg_armor");

  ItemTag LLAMA_FOOD = TagImpl.get("llama_food");

  ItemTag LLAMA_TEMPT_ITEMS = TagImpl.get("llama_tempt_items");

  ItemTag LOGS = TagImpl.get("logs");

  ItemTag LOGS_THAT_BURN = TagImpl.get("logs_that_burn");

  ItemTag MANGROVE_LOGS = TagImpl.get("mangrove_logs");

  ItemTag MAP_INVISIBILITY_EQUIPMENT = TagImpl.get("map_invisibility_equipment");

  ItemTag MEAT = TagImpl.get("meat");

  ItemTag NETHERITE_TOOL_MATERIALS = TagImpl.get("netherite_tool_materials");

  ItemTag NON_FLAMMABLE_WOOD = TagImpl.get("non_flammable_wood");

  ItemTag NOTEBLOCK_TOP_INSTRUMENTS = TagImpl.get("noteblock_top_instruments");

  ItemTag OAK_LOGS = TagImpl.get("oak_logs");

  ItemTag OCELOT_FOOD = TagImpl.get("ocelot_food");

  ItemTag PALE_OAK_LOGS = TagImpl.get("pale_oak_logs");

  ItemTag PANDA_EATS_FROM_GROUND = TagImpl.get("panda_eats_from_ground");

  ItemTag PANDA_FOOD = TagImpl.get("panda_food");

  ItemTag PARROT_FOOD = TagImpl.get("parrot_food");

  ItemTag PARROT_POISONOUS_FOOD = TagImpl.get("parrot_poisonous_food");

  ItemTag PICKAXES = TagImpl.get("pickaxes");

  ItemTag PIG_FOOD = TagImpl.get("pig_food");

  ItemTag PIGLIN_FOOD = TagImpl.get("piglin_food");

  ItemTag PIGLIN_LOVED = TagImpl.get("piglin_loved");

  ItemTag PIGLIN_PREFERRED_WEAPONS = TagImpl.get("piglin_preferred_weapons");

  ItemTag PIGLIN_REPELLENTS = TagImpl.get("piglin_repellents");

  ItemTag PIGLIN_SAFE_ARMOR = TagImpl.get("piglin_safe_armor");

  ItemTag PILLAGER_PREFERRED_WEAPONS = TagImpl.get("pillager_preferred_weapons");

  ItemTag PLANKS = TagImpl.get("planks");

  ItemTag RABBIT_FOOD = TagImpl.get("rabbit_food");

  ItemTag RAILS = TagImpl.get("rails");

  ItemTag REDSTONE_ORES = TagImpl.get("redstone_ores");

  ItemTag REPAIRS_CHAIN_ARMOR = TagImpl.get("repairs_chain_armor");

  ItemTag REPAIRS_DIAMOND_ARMOR = TagImpl.get("repairs_diamond_armor");

  ItemTag REPAIRS_GOLD_ARMOR = TagImpl.get("repairs_gold_armor");

  ItemTag REPAIRS_IRON_ARMOR = TagImpl.get("repairs_iron_armor");

  ItemTag REPAIRS_LEATHER_ARMOR = TagImpl.get("repairs_leather_armor");

  ItemTag REPAIRS_NETHERITE_ARMOR = TagImpl.get("repairs_netherite_armor");

  ItemTag REPAIRS_TURTLE_HELMET = TagImpl.get("repairs_turtle_helmet");

  ItemTag REPAIRS_WOLF_ARMOR = TagImpl.get("repairs_wolf_armor");

  ItemTag SAND = TagImpl.get("sand");

  ItemTag SAPLINGS = TagImpl.get("saplings");

  ItemTag SHEEP_FOOD = TagImpl.get("sheep_food");

  ItemTag SHOVELS = TagImpl.get("shovels");

  ItemTag SHULKER_BOXES = TagImpl.get("shulker_boxes");

  ItemTag SIGNS = TagImpl.get("signs");

  ItemTag SKELETON_PREFERRED_WEAPONS = TagImpl.get("skeleton_preferred_weapons");

  ItemTag SKULLS = TagImpl.get("skulls");

  ItemTag SLABS = TagImpl.get("slabs");

  ItemTag SMALL_FLOWERS = TagImpl.get("small_flowers");

  ItemTag SMELTS_TO_GLASS = TagImpl.get("smelts_to_glass");

  ItemTag SNIFFER_FOOD = TagImpl.get("sniffer_food");

  ItemTag SOUL_FIRE_BASE_BLOCKS = TagImpl.get("soul_fire_base_blocks");

  ItemTag SPRUCE_LOGS = TagImpl.get("spruce_logs");

  ItemTag STAIRS = TagImpl.get("stairs");

  ItemTag STONE_BRICKS = TagImpl.get("stone_bricks");

  ItemTag STONE_BUTTONS = TagImpl.get("stone_buttons");

  ItemTag STONE_CRAFTING_MATERIALS = TagImpl.get("stone_crafting_materials");

  ItemTag STONE_TOOL_MATERIALS = TagImpl.get("stone_tool_materials");

  ItemTag STRIDER_FOOD = TagImpl.get("strider_food");

  ItemTag STRIDER_TEMPT_ITEMS = TagImpl.get("strider_tempt_items");

  ItemTag SWORDS = TagImpl.get("swords");

  ItemTag TERRACOTTA = TagImpl.get("terracotta");

  ItemTag TRAPDOORS = TagImpl.get("trapdoors");

  ItemTag TRIM_MATERIALS = TagImpl.get("trim_materials");

  ItemTag TRIMMABLE_ARMOR = TagImpl.get("trimmable_armor");

  ItemTag TURTLE_FOOD = TagImpl.get("turtle_food");

  ItemTag VILLAGER_PICKS_UP = TagImpl.get("villager_picks_up");

  ItemTag VILLAGER_PLANTABLE_SEEDS = TagImpl.get("villager_plantable_seeds");

  ItemTag WALLS = TagImpl.get("walls");

  ItemTag WARPED_STEMS = TagImpl.get("warped_stems");

  ItemTag WART_BLOCKS = TagImpl.get("wart_blocks");

  ItemTag WITHER_SKELETON_DISLIKED_WEAPONS = TagImpl.get("wither_skeleton_disliked_weapons");

  ItemTag WOLF_FOOD = TagImpl.get("wolf_food");

  ItemTag WOODEN_BUTTONS = TagImpl.get("wooden_buttons");

  ItemTag WOODEN_DOORS = TagImpl.get("wooden_doors");

  ItemTag WOODEN_FENCES = TagImpl.get("wooden_fences");

  ItemTag WOODEN_PRESSURE_PLATES = TagImpl.get("wooden_pressure_plates");

  ItemTag WOODEN_SLABS = TagImpl.get("wooden_slabs");

  ItemTag WOODEN_STAIRS = TagImpl.get("wooden_stairs");

  ItemTag WOODEN_TOOL_MATERIALS = TagImpl.get("wooden_tool_materials");

  ItemTag WOODEN_TRAPDOORS = TagImpl.get("wooden_trapdoors");

  ItemTag WOOL = TagImpl.get("wool");

  ItemTag WOOL_CARPETS = TagImpl.get("wool_carpets");
}
