package me.moros.bending.api.platform.item;

/**
 * Code autogenerated, do not edit! v1.20.1
 */
@SuppressWarnings("unused")
interface Tags {
  ItemTag ACACIA_LOGS = TagImpl.get("acacia_logs");

  ItemTag ANVIL = TagImpl.get("anvil");

  ItemTag ARROWS = TagImpl.get("arrows");

  ItemTag AXES = TagImpl.get("axes");

  ItemTag AXOLOTL_TEMPT_ITEMS = TagImpl.get("axolotl_tempt_items");

  ItemTag BAMBOO_BLOCKS = TagImpl.get("bamboo_blocks");

  ItemTag BANNERS = TagImpl.get("banners");

  ItemTag BEACON_PAYMENT_ITEMS = TagImpl.get("beacon_payment_items");

  ItemTag BEDS = TagImpl.get("beds");

  ItemTag BIRCH_LOGS = TagImpl.get("birch_logs");

  ItemTag BOATS = TagImpl.get("boats");

  ItemTag BOOKSHELF_BOOKS = TagImpl.get("bookshelf_books");

  ItemTag BREAKS_DECORATED_POTS = TagImpl.get("breaks_decorated_pots");

  ItemTag BUTTONS = TagImpl.get("buttons");

  ItemTag CANDLES = TagImpl.get("candles");

  ItemTag CHERRY_LOGS = TagImpl.get("cherry_logs");

  ItemTag CHEST_BOATS = TagImpl.get("chest_boats");

  ItemTag CLUSTER_MAX_HARVESTABLES = TagImpl.get("cluster_max_harvestables");

  ItemTag COAL_ORES = TagImpl.get("coal_ores");

  ItemTag COALS = TagImpl.get("coals");

  ItemTag COMPASSES = TagImpl.get("compasses");

  ItemTag COMPLETES_FIND_TREE_TUTORIAL = TagImpl.get("completes_find_tree_tutorial");

  ItemTag COPPER_ORES = TagImpl.get("copper_ores");

  ItemTag CREEPER_DROP_MUSIC_DISCS = TagImpl.get("creeper_drop_music_discs");

  ItemTag CREEPER_IGNITERS = TagImpl.get("creeper_igniters");

  ItemTag CRIMSON_STEMS = TagImpl.get("crimson_stems");

  ItemTag DAMPENS_VIBRATIONS = TagImpl.get("dampens_vibrations");

  ItemTag DARK_OAK_LOGS = TagImpl.get("dark_oak_logs");

  ItemTag DECORATED_POT_INGREDIENTS = TagImpl.get("decorated_pot_ingredients");

  ItemTag DECORATED_POT_SHERDS = TagImpl.get("decorated_pot_sherds");

  ItemTag DIAMOND_ORES = TagImpl.get("diamond_ores");

  ItemTag DIRT = TagImpl.get("dirt");

  ItemTag DOORS = TagImpl.get("doors");

  ItemTag EMERALD_ORES = TagImpl.get("emerald_ores");

  ItemTag FENCE_GATES = TagImpl.get("fence_gates");

  ItemTag FENCES = TagImpl.get("fences");

  ItemTag FISHES = TagImpl.get("fishes");

  ItemTag FLOWERS = TagImpl.get("flowers");

  ItemTag FOX_FOOD = TagImpl.get("fox_food");

  ItemTag FREEZE_IMMUNE_WEARABLES = TagImpl.get("freeze_immune_wearables");

  ItemTag GOLD_ORES = TagImpl.get("gold_ores");

  ItemTag HANGING_SIGNS = TagImpl.get("hanging_signs");

  ItemTag HOES = TagImpl.get("hoes");

  ItemTag IGNORED_BY_PIGLIN_BABIES = TagImpl.get("ignored_by_piglin_babies");

  ItemTag IRON_ORES = TagImpl.get("iron_ores");

  ItemTag JUNGLE_LOGS = TagImpl.get("jungle_logs");

  ItemTag LAPIS_ORES = TagImpl.get("lapis_ores");

  ItemTag LEAVES = TagImpl.get("leaves");

  ItemTag LECTERN_BOOKS = TagImpl.get("lectern_books");

  ItemTag LOGS = TagImpl.get("logs");

  ItemTag LOGS_THAT_BURN = TagImpl.get("logs_that_burn");

  ItemTag MANGROVE_LOGS = TagImpl.get("mangrove_logs");

  ItemTag MUSIC_DISCS = TagImpl.get("music_discs");

  ItemTag NON_FLAMMABLE_WOOD = TagImpl.get("non_flammable_wood");

  ItemTag NOTEBLOCK_TOP_INSTRUMENTS = TagImpl.get("noteblock_top_instruments");

  ItemTag OAK_LOGS = TagImpl.get("oak_logs");

  ItemTag PICKAXES = TagImpl.get("pickaxes");

  ItemTag PIGLIN_FOOD = TagImpl.get("piglin_food");

  ItemTag PIGLIN_LOVED = TagImpl.get("piglin_loved");

  ItemTag PIGLIN_REPELLENTS = TagImpl.get("piglin_repellents");

  ItemTag PLANKS = TagImpl.get("planks");

  ItemTag RAILS = TagImpl.get("rails");

  ItemTag REDSTONE_ORES = TagImpl.get("redstone_ores");

  ItemTag SAND = TagImpl.get("sand");

  ItemTag SAPLINGS = TagImpl.get("saplings");

  ItemTag SHOVELS = TagImpl.get("shovels");

  ItemTag SIGNS = TagImpl.get("signs");

  ItemTag SLABS = TagImpl.get("slabs");

  ItemTag SMALL_FLOWERS = TagImpl.get("small_flowers");

  ItemTag SMELTS_TO_GLASS = TagImpl.get("smelts_to_glass");

  ItemTag SNIFFER_FOOD = TagImpl.get("sniffer_food");

  ItemTag SOUL_FIRE_BASE_BLOCKS = TagImpl.get("soul_fire_base_blocks");

  ItemTag SPRUCE_LOGS = TagImpl.get("spruce_logs");

  ItemTag STAIRS = TagImpl.get("stairs");

  ItemTag STONE_BRICKS = TagImpl.get("stone_bricks");

  ItemTag STONE_BUTTONS = TagImpl.get("stone_buttons");

  ItemTag STONE_CRAFTING_MATERIALS = TagImpl.get("stone_crafting_materials");

  ItemTag STONE_TOOL_MATERIALS = TagImpl.get("stone_tool_materials");

  ItemTag SWORDS = TagImpl.get("swords");

  ItemTag TALL_FLOWERS = TagImpl.get("tall_flowers");

  ItemTag TERRACOTTA = TagImpl.get("terracotta");

  ItemTag TOOLS = TagImpl.get("tools");

  ItemTag TRAPDOORS = TagImpl.get("trapdoors");

  ItemTag TRIM_MATERIALS = TagImpl.get("trim_materials");

  ItemTag TRIM_TEMPLATES = TagImpl.get("trim_templates");

  ItemTag TRIMMABLE_ARMOR = TagImpl.get("trimmable_armor");

  ItemTag VILLAGER_PLANTABLE_SEEDS = TagImpl.get("villager_plantable_seeds");

  ItemTag WALLS = TagImpl.get("walls");

  ItemTag WARPED_STEMS = TagImpl.get("warped_stems");

  ItemTag WART_BLOCKS = TagImpl.get("wart_blocks");

  ItemTag WOODEN_BUTTONS = TagImpl.get("wooden_buttons");

  ItemTag WOODEN_DOORS = TagImpl.get("wooden_doors");

  ItemTag WOODEN_FENCES = TagImpl.get("wooden_fences");

  ItemTag WOODEN_PRESSURE_PLATES = TagImpl.get("wooden_pressure_plates");

  ItemTag WOODEN_SLABS = TagImpl.get("wooden_slabs");

  ItemTag WOODEN_STAIRS = TagImpl.get("wooden_stairs");

  ItemTag WOODEN_TRAPDOORS = TagImpl.get("wooden_trapdoors");

  ItemTag WOOL = TagImpl.get("wool");

  ItemTag WOOL_CARPETS = TagImpl.get("wool_carpets");
}
