plugins {
    id("publish-conventions")
}

version = apiVersion()

dependencies {
    api(libs.math.core)
    api(libs.tasker.core)
    compileOnlyApi(libs.adventure.api)
    compileOnly(libs.caffeine)
}

sourceSets {
    main {
        java.srcDir(projectDir.resolve("src").resolve("autogenerated").resolve("java"))
    }
}

tasks.register("printVersionStatus") {
    doLast {
        println("STATUS=${if (isSnapshot()) "snapshot" else "release"}")
    }
}
