plugins {
    id("bending.publish")
}

version = apiVersion()

dependencies {
    api(libs.jspecify)
    api(libs.math.core)
    api(libs.tasker.core)
    compileOnlyApi(libs.adventure.api)
    compileOnly(libs.caffeine)
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.adventure.api)
    testRuntimeOnly(libs.junit.platform)
}

sourceSets {
    main {
        java.srcDir(projectDir.resolve("src").resolve("autogenerated").resolve("java"))
    }
}

tasks {
    register("printVersionStatus") {
        val isSnapshot = isSnapshot()
        doLast {
            println("STATUS=${if (isSnapshot) "snapshot" else "release"}")
        }
    }
    test {
        useJUnitPlatform()
    }
}
