name: Bending
version: '${version}'
loader: me.moros.bending.paper.BendingLoader
main: me.moros.bending.paper.BendingBootstrap
author: Moros
description: Bending plugin for PaperMC.
website: https://github.com/PrimordialMoros/Bending
api-version: '${mcVersion}'
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    MiniPlaceholders:
      load: BEFORE
      required: false
    GriefPrevention:
      load: BEFORE
      required: false
    Bolt:
      load: BEFORE
      required: false
    Towny:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
